(function(){
'use strict';
var S={tab:'dashboard',records:[],relationships:[],schemaReady:true,ready:false};
var TYPES={
  briefing:{label:'Briefing',plural:'Briefings & Acknowledgements',icon:'ti-users-group',colour:'blue'},
  verification:{label:'Field verification',plural:'Field Verification',icon:'ti-clipboard-check',colour:'green'},
  change_request:{label:'Change request',plural:'Change Requests',icon:'ti-git-pull-request',colour:'amber'},
  work_pack:{label:'Work pack',plural:'Work Packs',icon:'ti-package',colour:'blue'}
};
var baseLoad=window.loadSWMS,baseLoadList=window.swmsLoadList,baseNew=window.swmsNew,baseOpen=window.swmsOpen,basePayload=window.swmsPayload,baseAddStep=window.swmsAddStep,baseRows=window.swmsRows,baseBuildHtml=window.swmsBuildHtml,baseSave=window.swmsSaveToDocuments;
function e(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function nowDate(){return new Date().toISOString().slice(0,10);}
function id(){return typeof crypto!=='undefined'&&crypto.randomUUID?crypto.randomUUID():'swx-'+Date.now()+'-'+Math.random().toString(16).slice(2);}
function status(v){return String(v||'draft').toLowerCase().replace(/\s+/g,'_');}
function profile(){try{return (typeof prof!=='undefined'&&prof)||window.prof||{};}catch(_){return window.prof||{};}}
function pill(v){var s=status(v),tone=/approved|active|complete|pass|released/.test(s)?'green':/overdue|fail|stop|suspend|reject/.test(s)?'red':/review|pending|conditional|hold|due/.test(s)?'amber':'blue';return '<span class="swx-pill '+tone+'"><i class="ti ti-circle-filled"></i>'+e(s.replace(/_/g,' '))+'</span>';}
function recordLabel(r){return TYPES[r.record_type]?.label||String(r.record_type||'Record').replace(/_/g,' ');}
function docById(x){return (window.swmsAllData||swmsAllData||[]).find(function(d){return String(d.id)===String(x);});}
function docRef(d){return d?(d.doc_ref||d.reference_no||'DRAFT'):'Unlinked';}
function docTitle(d){return d?(d.title||'Untitled SWMS'):'No SWMS selected';}
function schemaMessage(){return '<div class="swx-note swx-warning"><b>Operational workspace setup required.</b> The existing SWMS register remains available. Run <code>swms_module_upgrade.sql</code> once to enable shared briefings, field verifications, changes and work packs.</div>';}

function ensureShell(){
  var page=document.getElementById('page-swms');if(!page||page.dataset.swxReady)return;
  page.dataset.swxReady='1';page.classList.add('swx-page');
  var header=page.querySelector('.page-header');
  if(header)header.outerHTML='<div class="swx-hero"><div><div class="swx-kicker">Plan safely · Brief clearly · Verify before work</div><h1>Safe Work Method Statements</h1><p>Build practical methods, connect risk and permit controls, brief the crew and confirm that actual site conditions match the approved plan.</p></div><div class="swx-hero-actions"><button class="swx-btn" onclick="swxPrintRegister()"><i class="ti ti-printer"></i>Print register</button><button class="swx-btn primary" onclick="swmsNew()"><i class="ti ti-plus"></i>New SWMS</button></div></div>';
  var hero=page.querySelector('.swx-hero');hero.insertAdjacentHTML('afterend','<nav class="swx-tabs" id="swx-tabs">'+[
    ['dashboard','ti-layout-dashboard','Dashboard'],['register','ti-file-description','SWMS Register'],['mywork','ti-list-check','My Work'],['briefing','ti-users-group','Briefings'],['verification','ti-clipboard-check','Field Verification'],['change_request','ti-git-pull-request','Change Requests'],['work_pack','ti-package','Work Packs']
  ].map(function(x){return '<button data-tab="'+x[0]+'" onclick="swxSwitch(\''+x[0]+'\')"><i class="ti '+x[1]+'"></i>'+x[2]+'</button>';}).join('')+'</nav>');
  var list=document.getElementById('swms-list-view');
  if(list){
    list.classList.add('swx-view');list.dataset.swxView='register';
    list.insertAdjacentHTML('afterbegin','<div class="swx-register-tools"><div><label>Search</label><input id="swx-search" placeholder="Code, activity, owner, site..." oninput="swxApplyRegisterFilters()"></div><div><label>Status</label><select id="swx-status" onchange="swxApplyRegisterFilters()"><option value="">All statuses</option><option value="draft">Draft</option><option value="pending_review">In review</option><option value="approved">Approved</option><option value="active">Active</option><option value="suspended">Suspended</option></select></div><div><label>Applicability</label><select id="swx-applicability" onchange="swxApplyRegisterFilters()"><option value="">All contexts</option><option value="generic">Generic</option><option value="project">Project</option><option value="site">Site</option><option value="task">Task specific</option></select></div><div><label>Review</label><select id="swx-review" onchange="swxApplyRegisterFilters()"><option value="">Any review date</option><option value="due">Due within 30 days</option><option value="overdue">Overdue</option></select></div><button class="swx-btn" onclick="swxResetRegister()"><i class="ti ti-refresh"></i>Reset</button></div>');
  }
  ['dashboard','mywork','briefing','verification','change_request','work_pack'].forEach(function(v){var el=document.createElement('section');el.id='swx-view-'+v;el.className='swx-view';el.dataset.swxView=v;list.parentNode.insertBefore(el,list);});
  ensureDrawer();ensureFormEnhancements();S.ready=true;
}
function ensureDrawer(){if(document.getElementById('swx-drawer-bg'))return;document.body.insertAdjacentHTML('beforeend','<div class="swx-drawer-bg" id="swx-drawer-bg" onclick="if(event.target===this)swxCloseDrawer()"><aside class="swx-drawer"><header class="swx-drawer-head"><div><span id="swx-drawer-kicker">Operational record</span><h2 id="swx-drawer-title">Record</h2></div><button class="swx-btn compact" onclick="swxCloseDrawer()"><i class="ti ti-x"></i></button></header><div class="swx-drawer-body" id="swx-drawer-body"></div><footer class="swx-drawer-foot" id="swx-drawer-foot"></footer></aside></div>');}
function openDrawer(title,body,foot,kicker){ensureDrawer();document.getElementById('swx-drawer-title').textContent=title;document.getElementById('swx-drawer-kicker').textContent=kicker||'Operational record';document.getElementById('swx-drawer-body').innerHTML=body;document.getElementById('swx-drawer-foot').innerHTML=foot||'';document.getElementById('swx-drawer-bg').classList.add('open');}
window.swxCloseDrawer=function(){document.getElementById('swx-drawer-bg')?.classList.remove('open');};

function ensureFormEnhancements(){
  var form=document.getElementById('swms-form3view');if(!form||form.dataset.swxEnhanced)return;form.dataset.swxEnhanced='1';
  var first=form.querySelector(':scope > div:nth-child(2)');
  if(first)first.insertAdjacentHTML('beforebegin','<div class="swx-readiness" id="swx-readiness"><div><h3>SWMS readiness</h3><p>Approval describes the safe method; the Permit module remains responsible for authorising work.</p></div><div class="swx-ready-item"><small>Revision</small><b id="swx-ready-revision">Rev 00</b></div><div class="swx-ready-item"><small>Method steps</small><b id="swx-ready-steps">0</b></div><div class="swx-ready-item"><small>Risk assessment</small><b id="swx-ready-risk">Not linked</b></div><div class="swx-ready-item"><small>Permit</small><b id="swx-ready-permit">Not required/linked</b></div></div>');
  var resources=Array.from(form.querySelectorAll('.card')).find(function(c){return /Resources & Controls/i.test(c.textContent);});
  if(resources)resources.insertAdjacentHTML('beforebegin','<div class="card swx-enhance" id="swx-context-card"><div class="card-title"><i class="ti ti-route"></i> Applicability, Responsibilities & Interfaces</div><div class="swx-enhance-grid"><div class="swx-field"><label>Applicability</label><select id="swx-app"><option value="generic">Generic activity</option><option value="project">Project specific</option><option value="site">Site specific</option><option value="task">Task / work-pack specific</option></select></div><div class="swx-field"><label>Person in charge</label><input id="swx-pic" placeholder="Responsible supervisor / PIC"></div><div class="swx-field"><label>Working conditions / shift</label><input id="swx-conditions" placeholder="Hours, weather or operating limits"></div><div class="swx-field two"><label>Boundaries and prohibited practices</label><textarea id="swx-boundaries" placeholder="What is included, excluded or must never be done?"></textarea></div><div class="swx-field"><label>SIMOPS / adjacent-work interfaces</label><textarea id="swx-simops" placeholder="Concurrent work, coordination and segregation"></textarea></div><div class="swx-field"><label>Isolation / design interface</label><textarea id="swx-isolation" placeholder="LOTO, drawing, calculation or hold-point references"></textarea></div><div class="swx-field"><label>Environmental controls</label><textarea id="swx-environment" placeholder="Noise, waste, spill, dust, emissions and community controls"></textarea></div><div class="swx-field"><label>Rescue limitations and capability</label><textarea id="swx-rescue" placeholder="Authorised rescue team, equipment, access and limitations"></textarea></div></div></div>');
  var sign=Array.from(form.querySelectorAll('.card')).find(function(c){return /^\s*Sign-off/i.test(c.textContent);});
  if(sign)sign.insertAdjacentHTML('afterend','<div class="card swx-related" id="swx-related-card"><div class="swx-panel-head"><div><h3>Execution records</h3><p>The same record IDs appear here and in the module-wide queues.</p></div></div><div class="swx-related-grid" id="swx-related-grid"></div></div>');
  form.addEventListener('input',updateReadiness);form.addEventListener('change',updateReadiness);
}
function updateReadiness(){var set=function(id,v){var x=document.getElementById(id);if(x)x.textContent=v;};set('swx-ready-revision',document.getElementById('swms-version')?.value||'Rev 00');set('swx-ready-steps',document.querySelectorAll('#swms-steps-body tr').length);set('swx-ready-risk',document.getElementById('swms-ra-ref')?.value?'Linked':'Not linked');set('swx-ready-permit',document.getElementById('swms-ptw-ref')?.value?'Linked':'Not required/linked');}

async function loadAux(){
  var a=await Promise.allSettled([api('/swms_operational_records?select=*'+cf()+'&order=created_at.desc'),api('/swms_relationships?select=*'+cf()+'&order=created_at.desc')]);S.records=a[0].status==='fulfilled'?(a[0].value||[]):[];S.relationships=a[1].status==='fulfilled'?(a[1].value||[]):[];S.schemaReady=a.every(function(x){return x.status==='fulfilled';});
  renderActive();refreshRelated();
}
function metric(icon,label,value){return '<article class="swx-metric"><i class="ti '+icon+'"></i><b>'+e(value)+'</b><span>'+e(label)+'</span></article>';}
function empty(title,text,action){return '<div class="swx-empty"><i class="ti ti-clipboard-off"></i><strong>'+e(title)+'</strong><span>'+e(text)+'</span>'+(action||'')+'</div>';}
function renderDashboard(){
  var docs=window.swmsAllData||swmsAllData||[],approved=docs.filter(function(d){return /approved|active/.test(status(d.approval_status||d.status));}).length,due=docs.filter(function(d){return d.review_date&&new Date(d.review_date)<=new Date(Date.now()+2592000000);}).length,brief=S.records.filter(function(r){return r.record_type==='briefing'&&!/complete|cancel/.test(status(r.status));}).length,verify=S.records.filter(function(r){return r.record_type==='verification'&&/fail|hold|stop|conditional/.test(status(r.work_decision||r.status));}).length;
  var recent=docs.slice(0,6).map(function(d){var p=window.swmsDecodePayload?swmsDecodePayload(d)||{}:{};var gaps=[];if(!(p.steps||[]).length)gaps.push('method steps');if(!p.risk_assessment_ref)gaps.push('risk assessment');if(!p.prepared_by)gaps.push('owner');return '<div class="swx-row"><div><strong>'+e(docRef(d)+' · '+docTitle(d))+'</strong><small>'+e(gaps.length?'Needs '+gaps.join(', '):'Core method information complete')+'</small></div>'+pill(d.approval_status||d.status)+'</div>';}).join('');
  return '<div class="swx-grid metrics">'+metric('ti-file-check','SWMS records',docs.length)+metric('ti-rosette-discount-check','Approved / active',approved)+metric('ti-calendar-alert','Review due 30 days',due)+metric('ti-users-group','Briefings open',brief)+metric('ti-shield-exclamation','Field holds / failures',verify)+'</div>'+(S.schemaReady?'':schemaMessage())+'<div class="swx-grid two"><section class="swx-panel"><div class="swx-panel-head"><div><h3>Method readiness</h3><p>Fast checks against the current structured SWMS content.</p></div><button class="swx-btn compact" onclick="swxSwitch(\'register\')">Open register</button></div><div class="swx-list">'+(recent||empty('No SWMS records','Create the first real SWMS for this company.'))+'</div></section><section class="swx-panel"><div class="swx-panel-head"><div><h3>Safety boundary</h3><p>Clear authority between connected modules.</p></div></div><div class="swx-note"><b>SWMS approval does not release work.</b><br>An applicable permit, crew briefing and field verification must be completed through their authorised workflows where required.</div><div class="swx-list"><div class="swx-row"><div><strong>Risk Assessment</strong><small>Owns the risk methodology and decisions.</small></div><span class="swx-pill green">Linked source</span></div><div class="swx-row"><div><strong>Permit to Work</strong><small>Owns issue, release, suspension and closure.</small></div><span class="swx-pill amber">Separate authority</span></div><div class="swx-row"><div><strong>Document Control</strong><small>Holds the controlled rendition and revision record.</small></div><span class="swx-pill blue">Governed copy</span></div></div></section></div>';
}
function renderQueue(type){
  var info=TYPES[type],rows=S.records.filter(function(r){return r.record_type===type;});
  var html=rows.map(function(r){var d=docById(r.swms_document_id);return '<div class="swx-row"><div><strong>'+e(r.reference||recordLabel(r)+' · '+(r.title||docTitle(d)))+'</strong><small>'+e(docRef(d)+' · '+(r.owner_name||r.assignee_name||'Unassigned')+(r.due_at?' · due '+new Date(r.due_at).toLocaleDateString('en-GB'):''))+'</small></div><div style="display:flex;gap:6px;align-items:center">'+pill(r.work_decision||r.status)+'<button class="swx-btn compact" onclick="swxOpenRecord(\''+e(r.id)+'\')"><i class="ti ti-chevron-right"></i></button></div></div>';}).join('');
  return (S.schemaReady?'':schemaMessage())+'<section class="swx-panel"><div class="swx-panel-head"><div><h3>'+e(info.plural)+'</h3><p>Shared operational records linked to the exact SWMS and revision.</p></div><button class="swx-btn primary" onclick="swxOpenRecordForm(\''+type+'\')"><i class="ti ti-plus"></i>New '+e(info.label)+'</button></div><div class="swx-list">'+(html||empty('No '+info.plural.toLowerCase(),'No authorised records exist in this company scope.'))+'</div></section>';
}
function renderMyWork(){var me=profile(),name=(me.full_name||'').toLowerCase(),uidv=me.id||'';var rows=S.records.filter(function(r){return String(r.owner_name||r.assignee_name||'').toLowerCase()===name||String(r.created_by||'')===String(uidv);});return (S.schemaReady?'':schemaMessage())+'<section class="swx-panel"><div class="swx-panel-head"><div><h3>My SWMS work</h3><p>Drafting, briefing, verification and change tasks assigned to you.</p></div></div><div class="swx-list">'+(rows.map(function(r){var d=docById(r.swms_document_id);return '<div class="swx-row"><div><strong>'+e(recordLabel(r)+' · '+(r.title||docTitle(d)))+'</strong><small>'+e(docRef(d)+' · '+(r.due_at?'due '+new Date(r.due_at).toLocaleDateString('en-GB'):'no due date'))+'</small></div>'+pill(r.work_decision||r.status)+'</div>';}).join('')||empty('No assigned SWMS work','Your current authorised queue is clear.'))+'</div></section>';}
function renderActive(){if(!S.ready)return;var el=document.getElementById('swx-view-'+S.tab);if(!el)return;if(S.tab==='dashboard')el.innerHTML=renderDashboard();else if(S.tab==='mywork')el.innerHTML=renderMyWork();else if(TYPES[S.tab])el.innerHTML=renderQueue(S.tab);}
window.swxSwitch=function(tab){ensureShell();S.tab=tab;document.querySelectorAll('#page-swms .swx-view').forEach(function(v){var active=v.dataset.swxView===tab;v.classList.toggle('active',active);v.style.display=active?'block':'none';});document.querySelectorAll('#swx-tabs button').forEach(function(b){b.classList.toggle('active',b.dataset.tab===tab);});if(tab==='register'){swxApplyRegisterFilters();}else renderActive();};
window.swxPrintRegister=function(){if(typeof swmsPrintRegister==='function')swmsPrintRegister();};
window.swxResetRegister=function(){['swx-search','swx-status','swx-applicability','swx-review'].forEach(function(x){var el=document.getElementById(x);if(el)el.value='';});swxApplyRegisterFilters();};
window.swxApplyRegisterFilters=function(){if(typeof window.swmsRenderList==='function')window.swmsRenderList();};

window.swmsRenderList=function(){
  var el=document.getElementById('swms-list');if(!el)return;var q=(document.getElementById('swx-search')?.value||'').toLowerCase(),st=document.getElementById('swx-status')?.value||'',app=document.getElementById('swx-applicability')?.value||'',review=document.getElementById('swx-review')?.value||'',today=new Date(),due30=new Date(Date.now()+2592000000);
  var rows=(window.swmsAllData||swmsAllData||[]).filter(function(x){var p=window.swmsDecodePayload?swmsDecodePayload(x)||{}:{},hay=[x.title,x.doc_ref,x.reference_no,x.department,x.dept,x.owner,x.doc_owner,x.location,p.location,p.contractor].join(' ').toLowerCase(),xs=status(x.approval_status||x.status);if(q&&!hay.includes(q))return false;if(st&&xs!==st&&!(st==='pending_review'&&/review|approval/.test(xs)))return false;if(app&&(p.applicability||'generic')!==app)return false;if(review){if(!x.review_date)return false;var d=new Date(x.review_date);if(review==='overdue'&&d>=today)return false;if(review==='due'&&(d<today||d>due30))return false;}return true;});
  if(!rows.length){el.innerHTML=empty('No matching SWMS','Adjust the filters or create a new safe work method statement.','<br><button class="swx-btn primary" style="margin-top:12px" onclick="swmsNew()"><i class="ti ti-plus"></i>Create SWMS</button>');return;}
  el.innerHTML='<div class="table-scroll"><table class="data-table" style="min-width:1040px"><thead><tr><th>Reference</th><th>Activity / scope</th><th>Applicability</th><th>Owner</th><th>Revision</th><th>Status</th><th>Review</th><th></th></tr></thead><tbody>'+rows.map(function(x){var p=window.swmsDecodePayload?swmsDecodePayload(x)||{}:{};return '<tr><td><b style="color:#087b68;font-family:monospace">'+e(docRef(x))+'</b></td><td><b>'+e(docTitle(x))+'</b><small style="display:block;color:#71848b;margin-top:3px">'+e((p.scope||x.scope||x.description||'').slice(0,120))+'</small></td><td>'+e((p.applicability||'generic').replace(/_/g,' '))+'</td><td>'+e(p.person_in_charge||x.owner||x.doc_owner||x.author||'-')+'</td><td>'+e(x.version||x.doc_version||p.version||'Rev 00')+'</td><td>'+pill(x.approval_status||x.status)+'</td><td>'+e(x.review_date?new Date(x.review_date).toLocaleDateString('en-GB'):'-')+'</td><td><button class="swx-btn compact" onclick="swmsOpen(\''+e(x.id)+'\')"><i class="ti ti-chevron-right"></i></button></td></tr>';}).join('')+'</tbody></table></div>';
};

function selectDocs(selected){return '<option value="">Select SWMS...</option>'+(window.swmsAllData||swmsAllData||[]).map(function(d){return '<option value="'+e(d.id)+'" '+(String(selected||'')===String(d.id)?'selected':'')+'>'+e(docRef(d)+' · '+docTitle(d))+'</option>';}).join('');}
function field(label,id,type,opts,value,full){var control=type==='textarea'?'<textarea id="'+id+'">'+e(value||'')+'</textarea>':type==='select'?'<select id="'+id+'">'+opts+'</select>':'<input id="'+id+'" type="'+(type||'text')+'" value="'+e(value||'')+'">';return '<div class="swx-field '+(full?'full':'')+'"><label>'+e(label)+'</label>'+control+'</div>';}
window.swxOpenRecordForm=function(type,swmsId){var t=TYPES[type],me=profile();if(!t)return;var body='<div class="swx-note">This '+e(t.label.toLowerCase())+' remains one shared record. Opening it from a selected SWMS or the global queue uses the same ID.</div><div class="swx-form">'+field('Linked SWMS','swx-r-swms','select',selectDocs(swmsId||window.swmsEditingId),'')+field('Revision','swx-r-revision','text',null,document.getElementById('swms-version')?.value||'')+field(type==='work_pack'?'Work-pack title':'Activity / record title','swx-r-title','text',null,'',true)+field(type==='briefing'?'Briefing leader':type==='verification'?'Verifier':'Owner','swx-r-owner','text',null,me.full_name||'')+field(type==='briefing'?'Briefing date':type==='verification'?'Verification due':'Target date','swx-r-due','date',null,nowDate())+field(type==='verification'?'Work decision':'Status','swx-r-status','select',type==='verification'?'<option value="pending">Pending</option><option value="pass">Release / Pass</option><option value="conditional_hold">Conditional hold</option><option value="hold">Hold / Do not start</option><option value="stop_work">Stop work</option>':'<option value="draft">Draft</option><option value="open">Open</option><option value="in_progress">In progress</option><option value="complete">Complete</option>','')+field(type==='briefing'?'Crew / participants':type==='work_pack'?'Project, site and work context':type==='change_request'?'Requested change and immediate controls':'Conditions, checks and evidence','swx-r-notes','textarea',null,'',true)+field('Reason / follow-up','swx-r-reason','textarea',null,'',true)+'</div>';openDrawer('New '+t.label,body,'<button class="swx-btn" onclick="swxCloseDrawer()">Cancel</button><button class="swx-btn primary" onclick="swxSaveRecord(\''+type+'\')"><i class="ti ti-device-floppy"></i>Save record</button>',t.plural);};
window.swxSaveRecord=async function(type){if(!S.schemaReady)return toast('Run swms_module_upgrade.sql before creating operational records.',false);var me=profile(),swmsId=document.getElementById('swx-r-swms')?.value||'',title=document.getElementById('swx-r-title')?.value.trim()||'';if(!swmsId||!title)return toast('Linked SWMS and title are required',false);var d=docById(swmsId),decision=document.getElementById('swx-r-status')?.value||'draft',prefix={briefing:'BRF',verification:'VER',change_request:'CHG',work_pack:'WPK'}[type],body={company_id:ccid(),swms_document_id:String(swmsId),revision_code:document.getElementById('swx-r-revision')?.value||d?.version||d?.doc_version||'Rev 00',record_type:type,reference:prefix+'-'+new Date().getFullYear()+'-'+String(Date.now()).slice(-6),title:title,status:type==='verification'?'open':decision,work_decision:type==='verification'?decision:null,owner_name:document.getElementById('swx-r-owner')?.value||null,assignee_name:document.getElementById('swx-r-owner')?.value||null,due_at:document.getElementById('swx-r-due')?.value||null,payload:{notes:document.getElementById('swx-r-notes')?.value||'',reason:document.getElementById('swx-r-reason')?.value||'',source_swms_ref:docRef(d)},idempotency_key:id(),created_by:me.id||null,updated_at:new Date().toISOString()};try{var rows=await api('/swms_operational_records',{m:'POST',p:'return=representation',b:body});if(rows?.[0])S.records.unshift(rows[0]);swxCloseDrawer();renderActive();refreshRelated();toast(TYPES[type].label+' saved');}catch(err){toast('Record not saved: '+err.message,false);}};
window.swxOpenRecord=function(recordId){var r=S.records.find(function(x){return String(x.id)===String(recordId);});if(!r)return;var d=docById(r.swms_document_id),body='<div class="swx-note"><b>'+e(docRef(d)+' · '+docTitle(d))+'</b><br>Revision '+e(r.revision_code||'-')+' · shared record ID '+e(r.id)+'</div><div class="swx-list"><div class="swx-row"><div><strong>Status / decision</strong><small>Operational outcome retained with this record.</small></div>'+pill(r.work_decision||r.status)+'</div><div class="swx-row"><div><strong>Owner</strong><small>'+e(r.owner_name||r.assignee_name||'Unassigned')+'</small></div></div><div class="swx-row"><div><strong>Due / performed</strong><small>'+e(r.due_at?new Date(r.due_at).toLocaleString('en-GB'):'Not specified')+'</small></div></div></div><div class="swx-panel" style="margin-top:12px"><b style="font-size:11px">Details</b><p style="font-size:11px;line-height:1.55;color:#5f757e">'+e(r.payload?.notes||r.payload?.reason||'No additional details recorded.')+'</p></div>';openDrawer(r.title||recordLabel(r),body,'<button class="swx-btn" onclick="swxCloseDrawer()">Close</button>',recordLabel(r));};

window.swmsAddStep=function(r){r=r||{};baseAddStep(r);var rows=document.querySelectorAll('#swms-steps-body tr'),tr=rows[rows.length-1];if(!tr)return;tr.dataset.stepId=r.stable_id||id();var ctl=tr.querySelector('.swms-controls')?.parentElement;if(ctl&&!ctl.querySelector('.swx-step-meta'))ctl.insertAdjacentHTML('beforeend','<div class="swx-step-meta"><select class="swx-hold"><option value="">No hold point</option><option value="supervisor" '+(r.hold_point==='supervisor'?'selected':'')+'>Supervisor hold</option><option value="permit_authority" '+(r.hold_point==='permit_authority'?'selected':'')+'>Permit authority hold</option><option value="technical" '+(r.hold_point==='technical'?'selected':'')+'>Technical hold</option></select><input class="swx-verify" placeholder="Verification / acceptance" value="'+e(r.verification||'')+'"></div>');updateReadiness();};
window.swmsRows=function(){var base=baseRows(),trs=Array.from(document.querySelectorAll('#swms-steps-body tr'));return base.map(function(r,i){var tr=trs[i];return Object.assign(r,{stable_id:tr?.dataset.stepId||id(),hold_point:tr?.querySelector('.swx-hold')?.value||'',verification:tr?.querySelector('.swx-verify')?.value||''});});};
window.swmsPayload=function(){var p=basePayload();return Object.assign(p,{applicability:document.getElementById('swx-app')?.value||'generic',person_in_charge:document.getElementById('swx-pic')?.value||'',working_conditions:document.getElementById('swx-conditions')?.value||'',boundaries:document.getElementById('swx-boundaries')?.value||'',simops:document.getElementById('swx-simops')?.value||'',isolation_interface:document.getElementById('swx-isolation')?.value||'',environmental_controls:document.getElementById('swx-environment')?.value||'',rescue_capability:document.getElementById('swx-rescue')?.value||'',steps:window.swmsRows()});};
function setExtra(p){[['swx-app','applicability'],['swx-pic','person_in_charge'],['swx-conditions','working_conditions'],['swx-boundaries','boundaries'],['swx-simops','simops'],['swx-isolation','isolation_interface'],['swx-environment','environmental_controls'],['swx-rescue','rescue_capability']].forEach(function(x){var el=document.getElementById(x[0]);if(el)el.value=p?.[x[1]]|| (x[0]==='swx-app'?'generic':'');});updateReadiness();refreshRelated();}
function hideModuleViews(){document.querySelectorAll('#page-swms .swx-view').forEach(function(v){v.classList.remove('active');v.style.display='none';});}
window.swmsNew=function(){ensureShell();baseNew();hideModuleViews();document.getElementById('swx-tabs').style.display='none';setExtra({});};
window.swmsOpen=function(docId){ensureShell();baseOpen(docId);hideModuleViews();document.getElementById('swx-tabs').style.display='none';var d=docById(docId),p=window.swmsDecodePayload?swmsDecodePayload(d)||{}:{};setExtra(p);};
window.swmsShowList=(function(base){return function(){base();var tabs=document.getElementById('swx-tabs');if(tabs)tabs.style.display='flex';swxSwitch('register');};})(window.swmsShowList);
window.swmsBuildHtml=function(){var html=baseBuildHtml(),p=window.swmsPayload(),extra='<div class="rpt-section"><div class="rpt-section-title">Applicability & Interfaces</div><div class="rpt-grid">'+fld('Applicability',String(p.applicability||'generic').replace(/_/g,' '))+fld('Person in charge',p.person_in_charge)+fld('Conditions / shift',p.working_conditions,true)+fld('Boundaries / prohibited work',p.boundaries,true)+fld('SIMOPS / adjacent work',p.simops,true)+fld('Isolation / design interface',p.isolation_interface,true)+fld('Environmental controls',p.environmental_controls,true)+fld('Rescue capability and limitations',p.rescue_capability,true)+'</div></div>';return html.replace('<div class="rpt-section"><div class="rpt-section-title secondary">Procedure Alignment',extra+'<div class="rpt-section"><div class="rpt-section-title secondary">Procedure Alignment');};
window.swmsSaveToDocuments=async function(){await baseSave();if(window.swmsEditingId||swmsEditingId){await syncRelationships(window.swmsEditingId||swmsEditingId);await loadAux();}};
async function syncRelationships(docId){if(!S.schemaReady)return;var me=profile(),p=window.swmsPayload(),revision=p.version||'Rev 00',links=[['risk_assessment',p.risk_assessment_ref],['permit',p.permit_ref]];for(var i=0;i<links.length;i++){var x=links[i];try{await api('/swms_relationships?company_id=eq.'+encodeURIComponent(ccid())+'&swms_document_id=eq.'+encodeURIComponent(docId)+'&revision_code=eq.'+encodeURIComponent(revision)+'&related_module=eq.'+x[0],{m:'DELETE',p:'return=minimal'});if(x[1])await api('/swms_relationships',{m:'POST',p:'return=minimal',b:{company_id:ccid(),swms_document_id:String(docId),revision_code:revision,related_module:x[0],related_record_id:String(x[1]),relationship_type:x[0]==='permit'?'interfaces_with':'derived_from',status:'active',applicability:{scope:p.applicability||'generic'},created_by:me.id||null}});}catch(_){}}}
function refreshRelated(){var el=document.getElementById('swx-related-grid');if(!el)return;var did=window.swmsEditingId||swmsEditingId;if(!did){el.innerHTML=empty('Save the SWMS first','Execution records can be linked after the SWMS has a stable identity.');return;}el.innerHTML=[['briefing','Briefings'],['verification','Verifications'],['change_request','Changes'],['work_pack','Work packs']].map(function(x){var n=S.records.filter(function(r){return r.record_type===x[0]&&String(r.swms_document_id)===String(did);}).length;return '<button class="swx-related-card" onclick="swxOpenRecordForm(\''+x[0]+'\',\''+e(did)+'\')"><i class="ti '+TYPES[x[0]].icon+'"></i><b>'+n+'</b><span>'+x[1]+' · add/open</span></button>';}).join('');}

window.swmsLoadList=async function(){var r=await baseLoadList();if(S.ready){window.swmsRenderList();renderActive();}return r;};
window.loadSWMS=async function(){ensureShell();var desired=S.tab;baseLoad();await loadAux();S.tab=desired;setTimeout(function(){if(!document.getElementById('swms-form3view')||document.getElementById('swms-form3view').style.display==='none')swxSwitch(desired||'dashboard');},80);};
try{if(typeof L!=='undefined')L.swms=window.loadSWMS;}catch(_){ }
})();
