const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const read=file=>fs.readFileSync(path.join(__dirname,'..',file),'utf8');
const current={companyId:'co-a',userId:'user-a',name:'Reviewer',role:'manager'};
const rows=[
  {id:'atex-1',company_id:'co-a',area_ref:'ATEX-001',area_name:'Solvent store',location:'Warehouse',plant_area:'Bay 2',zone_type:'zone_1',material_type:'gas_vapour',substance:'Toluene',source_of_release:'Filling point',ventilation_controls:'Mechanical extraction',ignition_controls:'Bonding and earthing',detection_controls:'LEL detector',responsible_person:'Alice',next_inspection_date:'2026-09-20',status:'controlled',linked_ra_ref:'RA-1',linked_permit_ref:'PTW-1',updated_at:'2026-09-10T10:00:00Z'},
  {id:'atex-2',company_id:'co-a',area_ref:'ATEX-002',area_name:'Dust transfer',location:'Production',zone_type:'zone_21',material_type:'dust',substance:'Powder',next_inspection_date:'2026-08-01',status:'action_required'},
  {id:'atex-3',company_id:'co-a',area_name:'Archived room',zone_type:'zone_2',material_type:'gas_vapour',substance:'Solvent',status:'archived',next_inspection_date:'2027-01-01'},
  {id:'foreign',company_id:'co-b',area_name:'Secret area',status:'controlled'},
  {id:'unscoped',area_name:'Unscoped area',status:'controlled'}
];
function runtime(){
  const identity={company:{id:'co-a'},profile:{id:'user-a',full_name:'Reviewer'},role:'manager'};let mounted,allowed=true,authenticated=true;
  const window={Date,navigator:{onLine:true},AurisPlatformServices:{ready:()=>true,auth:{isAuthenticated:()=>authenticated,current:()=>identity},rbac:{requireAccess:key=>{assert.equal(key,'atex');if(!allowed)throw Error('Access denied');}}},AurisViewEngine:{mount:(host,data,options)=>{mounted={data,options};return mounted;}}};
  vm.runInNewContext(read('auris-atex-list-workspace.js'),window);
  return {api:window.AurisAtexListWorkspace,identity,mounted:()=>mounted,deny:()=>{allowed=false;},signOut:()=>{authenticated=false;},window};
}
test('projection is tenant scoped and preserves hazardous-area controls and inspection meaning',()=>{const r=runtime(),before=JSON.stringify(rows),data=r.api.project(rows,current,{},new Date('2026-09-15T12:00:00Z'));assert.deepEqual(data.map(x=>x.id),['atex-1','atex-2','atex-3']);assert.equal(data[0].reference,'ATEX-001');assert.equal(data[0].zone,'Zone 1');assert.equal(data[0].inspection,'Due soon');assert.equal(data[0].linked_ra,'RA-1');assert.equal(data[1].inspection,'Overdue');assert.equal(data[1].attention,'Inspection overdue');assert.equal(JSON.stringify(rows),before);});
test('active status, zone and text filters combine safely',()=>{const r=runtime(),select=filters=>r.api.project(rows,current,{filters},new Date('2026-09-15T12:00:00Z')).map(x=>x.id);assert.deepEqual(select({status:'active'}),['atex-1','atex-2']);assert.deepEqual(select({status:'action_required'}),['atex-2']);assert.deepEqual(select({zone:'zone_1',search:'toluene'}),['atex-1']);assert.deepEqual(select({status:'active',zone:'zone_21'}),['atex-2']);});
test('unknown zone and status remain visible without unsafe relabelling',()=>{const r=runtime(),data=r.api.project([{id:'x',company_id:'co-a',area_name:'Unknown',zone_type:'zone_custom',status:'awaiting_review'}],current,{});assert.equal(data.length,1);assert.equal(data[0].zone,'zone custom');assert.equal(data[0].status,'awaiting review');});
test('shared ATEX register exposes exact open and manager edit actions',async()=>{const r=runtime(),calls=[];r.api.mount({},rows,{canEdit:true,openRecord:(id,c)=>calls.push(['open',id,c.companyId]),editRecord:(id,c)=>calls.push(['edit',id,c.companyId])});const m=r.mounted();assert.equal(m.options.moduleKey,'atex-areas');assert.deepEqual(Array.from(m.options.actions,x=>x.key),['open','edit']);await m.options.onAction('open',m.data[0]);await m.options.onAction('edit',m.data[0]);assert.deepEqual(calls,[['open','atex-1','co-a'],['edit','atex-1','co-a']]);for(const change of [x=>x.identity.company.id='co-b',x=>x.identity.profile.id='other',x=>x.identity.role='viewer',x=>x.deny(),x=>x.signOut()]){const x=runtime();x.api.mount({},rows,{canEdit:true,openRecord:()=>assert.fail('stale action')});const view=x.mounted();change(x);await assert.rejects(view.options.onAction('open',view.data[0]),/changed|denied|Sign in/);}});
test('release wiring publishes the ATEX register before the core loader',()=>{const html=read('index.html'),core=read('auris-core.js');assert.ok(html.indexOf('auris-atex-list-workspace.js?')<html.indexOf('auris-core.js?'));assert.match(core,/AurisAtexListWorkspace\.mount\(el,atexAreas/);assert.match(read('sw-assets.js'),/auris-atex-list-workspace\.js/);assert.match(read('scripts/verify-production-smoke.cjs'),/auris-atex-list-workspace\.js/);assert.match(read('scripts/verify-staging-acceptance.cjs'),/auris-atex-list-workspace\.js/);assert.doesNotMatch(read('auris-atex-list-workspace.js'),/\bfetch\(|\bapi\.request\(|\bPOST|\bPATCH|\bDELETE/);});
