const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const read=f=>fs.readFileSync(path.join(__dirname,'..',f),'utf8');
function runtime(extra={}){const state={companyId:'a',userId:'u',role:'manager'};const ctx={URL,URLSearchParams,location:{search:''},atexAreas:[],isMgr:()=>state.role==='manager',escH:v=>String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;'),AurisAtexListWorkspace:{session:()=>({...state}),assertSession:c=>{if(c.companyId!==state.companyId||c.userId!==state.userId||c.role!==state.role)throw Error('Session changed');}},api:async()=>[],...extra};vm.createContext(ctx);vm.runInContext(read('auris-atex-records.js'),ctx);return {ctx,state};}
test('ATEX viewing requests exact company record without opening editor',async()=>{const calls=[],{ctx}=runtime({api:async url=>{calls.push(url);return [{id:'r',company_id:'a',area_name:'Store'}];}});let viewed;ctx.atexShowRecord=row=>viewed=row;ctx.atexEdit=()=>assert.fail('editor opened');assert.equal(await ctx.atexOpenRecordRequest({record:'r',company:'a'}),true);assert.match(calls[0],/id=eq.r&company_id=eq.a/);assert.equal(viewed.area_name,'Store');});
test('foreign ATEX rows and mismatched links fail closed',async()=>{const {ctx}=runtime({api:async()=>[{id:'r',company_id:'b'}]});assert.equal(await ctx.atexOpenRecordRequest({record:'r'}),false);await assert.rejects(ctx.atexOpenRecordRequest({record:'r',company:'b'}),/company/);await assert.rejects(ctx.atexOpenRecordRequest({record:'r',table:'people'}),/Unsupported/);});
test('ATEX edit requires manager and restores routing flag after failure',async()=>{const {ctx,state}=runtime({location:{search:'?atexMode=edit'},api:async()=>[{id:'r',company_id:'a'}]});state.role='viewer';await assert.rejects(ctx.atexOpenRecordRequest({record:'r'}),/Manager/);state.role='manager';ctx.atexEdit=async()=>{throw Error('form failed');};await assert.rejects(ctx.atexOpenRecordRequest({record:'r'}),/form failed/);assert.equal(ctx.atexOpeningRecord,false);});
test('ATEX edit session rejects changed company, user and role',()=>{for(const key of ['companyId','userId','role']){const {ctx,state}=runtime();ctx.atexRecordContext={...state};state[key]='other';assert.throws(()=>ctx.atexAssertEditor(),/Session changed/);}const {ctx}=runtime();assert.throws(()=>ctx.atexAssertEditor(),/Reopen/);});
test('ATEX read-only content includes safety controls and escapes record text',()=>{const {ctx}=runtime();const html=ctx.atexRecordHtml({area_name:'<script>alert(1)</script>',zone_type:'zone_2',ventilation_controls:'Keep extraction running',linked_permit_ref:'PTW-123'});assert.match(html,/Keep extraction running/);assert.match(html,/PTW-123/);assert.match(html,/zone 2/);assert.doesNotMatch(html,/<script>|<input|<textarea|<select/);});
test('ATEX loading discards a response after company change',async()=>{const {ctx,state}=runtime();ctx.api=async()=>{state.companyId='b';return [{id:'r',company_id:'a'}];};await assert.rejects(ctx.atexOpenRecordRequest({record:'r'}),/Session changed/);});

test('opening ATEX editor preserves the selected permit reference',async()=>{
 const {ctx}=runtime();const controls=new Map();ctx.document={getElementById:id=>{if(!controls.has(id))controls.set(id,{value:'',style:{}});return controls.get(id);}};
 ctx.atexAreas=[{id:'r',linked_permit_ref:'PTW-001',linked_permit_type:'hot_work'}];ctx.atexOpeningRecord=true;
 ctx.atexLoadReferenceOptions=async(ra,permit)=>{ctx.document.getElementById('atex-permit').value=permit;};ctx.fillPersonSelect=()=>{};ctx.atexShowForm=()=>{};
 const core=read('auris-core.js');vm.runInContext(core.slice(core.indexOf('async function atexEdit(id){'),core.indexOf('function atexBack(){')),ctx);
 await ctx.atexEdit('r');assert.equal(controls.get('atex-permit').value,'PTW-001');
});
