const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');const root=path.resolve(__dirname,'..'),read=file=>fs.readFileSync(path.join(root,file),'utf8');
function runtime(){const window={console,Date,Promise};window.globalThis=window;vm.runInNewContext(read('auris-automation-engine.js'),window);return window;}
const rows=[{id:'a1',company_id:'co-a',status:'open',target_date:'2026-09-02',action_ref:'ACT-1'},{id:'a2',company_id:'co-a',status:'closed',target_date:'2026-08-01'},{id:'x',company_id:'co-b',status:'open',target_date:'2026-08-01',secret:'OTHER TENANT'}];
const rule={id:'rule-1',name:'Due reminder',actionType:'reminder',leadDays:7,overdueDays:0,intervalMinutes:60,status:'active'};
test('automation definitions allow only reviewed triggers and actions',()=>{const api=runtime().AurisAutomationEngine,value=api.definition({...rule,actionType:'webhook',moduleKey:'other',triggerType:'sql'});assert.equal(value.moduleKey,'actions');assert.equal(value.triggerType,'action_due');assert.equal(value.actionType,'reminder');assert.equal(value.intervalMinutes,60);});
test('planning excludes other companies and terminal records before creating exact jobs',()=>{const api=runtime().AurisAutomationEngine,result=api.plan(rows,rule,{context:()=>({companyId:'co-a',userId:'u1',role:'hse_manager'}),now:new Date('2026-09-01T08:00:00Z')});assert.equal(result.jobs.length,1);assert.equal(result.excluded,1);assert.equal(result.jobs[0].source.id,'a1');assert.equal(result.jobs[0].source.table,'action_tracker');assert.equal(JSON.stringify(result).includes('OTHER TENANT'),false);});
test('inactive rules are controlled no-ops and active execution uses governed queue adapter',async()=>{const api=runtime().AurisAutomationEngine,calls=[];assert.equal((await api.execute(rows,{...rule,status:'paused'},{context:()=>({companyId:'co-a'}),queue:x=>calls.push(x),now:new Date('2026-09-01T08:00:00Z')})).status,'controlled_noop');const result=await api.execute(rows,rule,{context:()=>({companyId:'co-a'}),queue:job=>{calls.push(job);return job.idempotencyKey;},now:new Date('2026-09-01T08:00:00Z')});assert.equal(result.executed,1);assert.equal(calls.length,1);});
test('persistence and scheduler enforce tenant admin, idempotency and service role boundaries',()=>{const sql=read('supabase/migrations/20260901050000_modular_foundation_19_automation.sql'),api=read('api/process-automations.js'),vercel=JSON.parse(read('vercel.json'));for(const marker of ['automation_rules','automation_executions','automation_require_admin','revision=p_expected_revision','FOR UPDATE SKIP LOCKED','unique(rule_id,source_record_id,event_key,recipient_key)','process_due_automation_rules','recipient_unavailable','action_tracker','notification_queue','audit_events','automation.rule_saved'])assert.match(sql,new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i'));assert.doesNotMatch(sql,/audit_logs/i);assert.match(sql,/revoke all on function public\.process_due_automation_rules[\s\S]*from public,anon,authenticated/i);assert.match(sql,/grant execute on function public\.process_due_automation_rules[\s\S]*to service_role/i);assert.match(api,/CRON_SECRET/);assert.match(api,/process_due_automation_rules/);assert.equal(vercel.crons.find(row=>row.path==='/api/process-automations').schedule,'*/5 * * * *');});
test('Automation Centre is role controlled, read-only previews are explicit and deployment assets exist',()=>{const centre=read('auris-automation-centre.js'),html=read('index.html'),css=read('auris-automation-centre.css'),manifest=read('sw-assets.js');for(const marker of ["['admin','hse_manager','sephs_admin']",'AurisAutomationEngine.plan','No notification, workflow transition or source mutation was performed.','save_automation_rule','set_automation_rule_status'])assert.match(centre,new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.match(html,/settings-automation-centre-card/);assert.match(html,/auris-automation-engine\.js\?v=20260901-19/);assert.match(html,/auris-automation-centre\.js\?v=20260901-19/);assert.match(css,/@media\(max-width:520px\)/);assert.match(css,/focus-visible/);assert.match(manifest,/auris-automation-engine\.js/);assert.match(manifest,/auris-automation-centre\.js/);});
