const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'../auris-chemical-records.js'),'utf8');
function runtime(extra={}){const state={companyId:'a',userId:'u',role:'manager'},ctx={URL,URLSearchParams,location:{search:''},chemData:[],isMgr:()=>state.role==='manager',escH:v=>String(v).replace(/</g,'&lt;'),AurisChemicalListWorkspace:{session:()=>({...state}),assertSession:c=>{if(c.companyId!==state.companyId||c.userId!==state.userId||c.role!==state.role)throw Error('Session changed');}},api:async()=>[],...extra};vm.createContext(ctx);vm.runInContext(source,ctx);return {ctx,state};}
test('chemical read requires exact company and record',async()=>{const {ctx}=runtime({api:async url=>{assert.match(url,/company_id=eq.a/);return url.startsWith('/chemical_register?')?[{id:'r',company_id:'a'}]:[];}});let shown=false;ctx.chemShowRecord=()=>{shown=true;};assert.equal(await ctx.chemOpenRecordRequest({record:'r',company:'a'}),true);assert.equal(shown,true);await assert.rejects(ctx.chemOpenRecordRequest({record:'r',company:'b'}),/company/);});
test('foreign records and changed sessions are discarded',async()=>{const {ctx,state}=runtime({api:async()=>[{id:'r',company_id:'b'}]});assert.equal(await ctx.chemOpenRecordRequest({record:'r'}),false);ctx.api=async()=>{state.companyId='b';return [];};await assert.rejects(ctx.chemOpenRecordRequest({record:'r'}),/Session changed/);});
test('chemical edit and save require manager in original context',async()=>{const {ctx,state}=runtime({location:{search:'?chemMode=edit'},api:async()=>[{id:'r',company_id:'a'}]});state.role='viewer';await assert.rejects(ctx.chemOpenRecordRequest({record:'r'}),/Manager/);state.role='manager';ctx.chemRecordContext={...state};state.userId='other';assert.throws(()=>ctx.chemAssertEditor(),/Session changed/);});
test('document links reject executable or credential-bearing URLs',()=>{const {ctx}=runtime();for(const value of ['javascript:alert(1)','data:text/html,test','https://user:pass@example.com','relative.pdf'])assert.equal(ctx.chemDocumentHref(value),'');assert.equal(ctx.chemDocumentHref('https://example.com/chemical.pdf'),'https://example.com/chemical.pdf');});
test('chemical fields are escaped, preserve zero, and contain no editing controls',()=>{const {ctx}=runtime();const html=ctx.chemRecordFields({persons_exposed:0,notes:'<script>bad</script>'},[['persons_exposed','Persons exposed'],['notes','Notes']]);assert.match(html,/>0</);assert.match(html,/&lt;script>/);assert.doesNotMatch(html,/<input|<textarea|<script/);});

test('record links preserve company and select chemical view or edit',()=>{const {ctx}=runtime({ccid:()=> 'a',deepLinkRecordUrl:record=>'https://example.com/?module='+record.module+'&company='+record.company_id+'&record='+record.id});const url=new URL(ctx.chemRecordHref('r','edit'));assert.equal(url.searchParams.get('module'),'chemical');assert.equal(url.searchParams.get('company'),'a');assert.equal(url.searchParams.get('chemMode'),'edit');});
test('edit route uses exact loaded record and resets opening flag',async()=>{const {ctx}=runtime({location:{search:'?chemMode=edit'},api:async()=>[{id:'r',company_id:'a',persons_exposed:0}]});ctx.chemEdit=id=>{assert.equal(id,'r');assert.equal(ctx.chemOpeningRecord,true);assert.equal(ctx.chemData[0].persons_exposed,0);};await ctx.chemOpenRecordRequest({record:'r'});assert.equal(ctx.chemOpeningRecord,false);});

const core=fs.readFileSync(path.join(__dirname,'../auris-core.js'),'utf8');
function coreFunction(ctx,name){const start=core.indexOf('function '+name+'('),end=core.indexOf('\n}',start)+2;vm.runInContext((core.slice(start-6,start)==='async '?'async ':'')+core.slice(start,end),ctx);}
test('real chemical editor preserves zero values',()=>{const controls={};const {ctx}=runtime({chemData:[{id:'r',company_id:'a',persons_exposed:0,quantity_stored:0}],document:{getElementById:id=>controls[id]||(controls[id]={style:{},value:''})},chemExposureValues:r=>r,displayRecordRef:()=> 'CHEM-1',chemClearAIReview:()=>{},chemUpdateRiskPreview:()=>{},chemRefreshSdsPreview:()=>{},chemShowForm:()=>{}});ctx.chemOpeningRecord=true;coreFunction(ctx,'chemEdit');ctx.chemEdit('r');assert.equal(controls['chem3persons'].value,0);assert.equal(controls['chem3qty'].value,0);});
test('real save blocks changed company before any upload or write',async()=>{let message='';const {ctx,state}=runtime({toast:text=>message=text});ctx.chemRecordContext={...state};state.companyId='b';coreFunction(ctx,'chemSave');await ctx.chemSave();assert.match(message,/Session changed/);});
