const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');
const root=path.resolve(__dirname,'..'),read=file=>fs.readFileSync(path.join(root,file),'utf8');
function runtime(){const values=new Map(),window={console,Date,Number,localStorage:{getItem:key=>values.get(key)||null,setItem:(key,value)=>values.set(key,value)},document:null};window.globalThis=window;vm.runInNewContext(read('auris-reporting-engine.js'),window);vm.runInNewContext(read('auris-dashboard-designer.js'),window);return {window,values};}
const definition={rowKey:'id',modes:['kpi','pivot','chart'],defaultMode:'kpi',defaultDimension:'module',defaultMeasure:'open',dimensions:[{key:'module',label:'Application'},{key:'status',label:'Status'}],measures:[{key:'items',label:'Items',operation:'count'},{key:'open',label:'Open',operation:'sum',field:'open_count'}]};
const rows=[{id:'1',company_id:'co-a',module:'events',status:'open',open_count:1,secret:'alpha'},{id:'2',company_id:'co-a',module:'risk',status:'closed',open_count:0,secret:'beta'},{id:'x',company_id:'co-b',module:'events',status:'open',open_count:1,secret:'OTHER COMPANY SECRET'}];
const input=[{key:'work',label:'My Work',rows,definition}],defaults={name:'Operations overview',widgets:[{id:'open-work',title:'Open work',sourceKey:'work',mode:'kpi',dimension:'module',measure:'open',size:'small'},{id:'by-module',title:'By application',sourceKey:'work',mode:'chart',dimension:'module',measure:'items',size:'wide'}]};
test('dashboard configuration accepts reviewed metadata and bounds widgets',()=>{const api=runtime().window.AurisDashboardDesigner,available=[{key:'work',label:'My Work',rows,definition:runtime().window.AurisReportingEngine.definition(definition)}],value=api.configuration({name:'A',widgets:Array.from({length:15},(_,i)=>({id:'w'+i,sourceKey:'work',mode:'unsafe',dimension:'bad',measure:'bad'}))},available);assert.equal(value.widgets.length,12);assert.equal(value.widgets[0].mode,'kpi');assert.equal(value.widgets[0].dimension,'module');assert.equal(value.widgets[0].measure,'open');});
test('dashboard diagnostics exclude other-company records before widgets calculate',()=>{const api=runtime().window.AurisDashboardDesigner;api.configure({context:()=>({companyId:'co-a',userId:'u-a'})});const result=api.diagnostics(input,{dashboardKey:'work-home',defaultConfiguration:defaults});assert.equal(result.widgets,2);assert.equal(result.authorisedRecords,4);assert.equal(result.excludedRecords,2);assert.equal(JSON.stringify(result).includes('OTHER COMPANY SECRET'),false);});
test('saved dashboard storage is company-user scoped metadata without record values',()=>{const env=runtime(),api=env.window.AurisDashboardDesigner;api.configure({context:()=>({companyId:'co-a',userId:'u-a'})});assert.equal(api.save('work-home',defaults,input),true);const entries=Array.from(env.values.entries());assert.equal(entries.length,1);assert.match(entries[0][0],/co-a:u-a:work-home$/);for(const forbidden of ['alpha','beta','OTHER COMPANY SECRET'])assert.equal(entries[0][1].includes(forbidden),false);const source=read('auris-dashboard-designer.js');assert.match(source,/auris360_dashboard_v1:/);assert.doesNotMatch(source,/<[^>]+\sstyle=/i);});
test('My Work and deployment publish the governed dashboard designer',()=>{const html=read('index.html'),work=read('auris-work-centre.js'),engine=read('auris-dashboard-designer.js'),css=read('auris-dashboard-designer.css'),manifest=read('sw-assets.js');assert.ok(html.indexOf('auris-reporting-engine.js?v=20260901-17')<html.indexOf('auris-dashboard-designer.js?v=20260901-18'));assert.ok(html.indexOf('auris-dashboard-designer.js?v=20260901-18')<html.indexOf('auris-work-centre.js?v=20260901-11'));for(const marker of ['data-work-insight="dashboard"','data-work-dashboard-designer','AurisDashboardDesigner.mount','dashboardKey:\'work-home\'','onDrillDown:function(rows)'])assert.match(work,new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));for(const marker of ["version:'1.0.0'",'configuration:configuration','save:save','mount:mount','diagnostics:diagnostics','12','AurisReportingEngine'])assert.match(engine,new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.match(css,/@media\(max-width:520px\)/);assert.match(css,/focus-visible/);assert.match(manifest,/auris-dashboard-designer\.js/);assert.match(manifest,/auris-dashboard-designer\.css/);});
