const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const read=file=>fs.readFileSync(path.join(__dirname,'..',file),'utf8');
const current={companyId:'co-a',userId:'user-a',name:'Reviewer',role:'manager'};
const equipment=[
  {id:'eq-1',company_id:'co-a',equipment_type:'fire_extinguisher',identifier:'FE-001',building:'Main',floor:'1',location:'Workshop',condition:'poor',next_inspection:'2026-09-01',next_service:'2026-10-01',serviced_by:'Facilities',status:'operational',updated_at:'2026-09-10'},
  {id:'eq-2',company_id:'co-a',equipment_type:'aed',identifier:'AED-001',building:'Main',floor:'0',location:'Reception',condition:'excellent',next_inspection:'2026-10-20',next_service:'2026-11-20',serviced_by:'Facilities',status:'operational'},
  {id:'foreign',company_id:'co-b',equipment_type:'aed',identifier:'AED-X',status:'operational'}
];
function runtime(){
  const identity={company:{id:'co-a'},profile:{id:'user-a',full_name:'Reviewer'},role:'manager'};let mounted,allowed=true,authenticated=true;
  const window={Date,navigator:{onLine:true},AurisPlatformServices:{ready:()=>true,auth:{isAuthenticated:()=>authenticated,current:()=>identity},rbac:{requireAccess:key=>{assert.equal(key,'emergency');if(!allowed)throw Error('Access denied');}}},AurisViewEngine:{mount:(host,data,options)=>{mounted={data,options};return mounted;}}};
  vm.runInNewContext(read('auris-emergency-list-workspace.js'),window);
  return {api:window.AurisEmergencyListWorkspace,identity,mounted:()=>mounted,deny:()=>{allowed=false;},signOut:()=>{authenticated=false;},window};
}
test('projection is tenant scoped and preserves emergency readiness dates and condition',()=>{const r=runtime(),before=JSON.stringify(equipment),data=r.api.project(equipment,current,{},new Date('2026-09-16T12:00:00Z'));assert.deepEqual(Array.from(data,x=>x.id),['eq-1','eq-2']);assert.equal(data[0].reference,'FE-001');assert.equal(data[0].inspection,'Overdue');assert.equal(data[0].service,'Due soon');assert.deepEqual(Array.from(data[0].attention_flags),['overdue','condition_risk']);assert.equal(data[1].title,'aed');assert.equal(JSON.stringify(equipment),before);});
test('emergency equipment filters combine type, status, attention and search',()=>{const r=runtime(),select=filters=>r.api.project(equipment,current,{filters},new Date('2026-09-16T12:00:00Z')).map(x=>x.id);assert.deepEqual(select({type:'aed'}),['eq-2']);assert.deepEqual(select({status:'operational',attention:'overdue'}),['eq-1']);assert.deepEqual(select({search:'reception',type:'aed'}),['eq-2']);});
test('unknown emergency equipment values remain visible without unsafe relabelling',()=>{const r=runtime(),data=r.api.project([{id:'x',company_id:'co-a',equipment_type:'special_unit',condition:'mystery',status:'awaiting_review'}],current,{});assert.equal(data.length,1);assert.equal(data[0].equipment_type,'special_unit');assert.equal(data[0].condition,'mystery');assert.equal(data[0].status,'awaiting review');});
test('shared emergency equipment register exposes guarded actions and protects sessions',async()=>{const r=runtime(),calls=[];r.api.mount({},equipment,{canEdit:true,openRecord:(id,c)=>calls.push(['open',id,c.companyId]),editRecord:(id,c)=>calls.push(['edit',id,c.companyId])});const m=r.mounted();assert.equal(m.options.moduleKey,'emergency-management');assert.deepEqual(Array.from(m.options.actions,x=>x.key),['open','edit']);await m.options.onAction('open',m.data[0]);await m.options.onAction('edit',m.data[0]);assert.deepEqual(calls,[['open','eq-1','co-a'],['edit','eq-1','co-a']]);for(const change of [x=>x.identity.company.id='co-b',x=>x.identity.profile.id='other',x=>x.identity.role='viewer',x=>x.deny(),x=>x.signOut()]){const x=runtime();x.api.mount({},equipment,{canEdit:true,openRecord:()=>assert.fail('stale action')});const view=x.mounted();change(x);await assert.rejects(view.options.onAction('open',view.data[0]),/changed|denied|Sign in/);}});
test('release wiring publishes the emergency equipment register before the core loader',()=>{const html=read('index.html'),core=read('auris-core.js');assert.ok(html.indexOf('auris-emergency-list-workspace.js?')<html.indexOf('auris-core.js?'));assert.match(core,/AurisEmergencyListWorkspace\.mount\(el,emEqData/);assert.match(read('sw-assets.js'),/auris-emergency-list-workspace\.js/);assert.match(read('scripts/verify-production-smoke.cjs'),/auris-emergency-list-workspace\.js/);assert.match(read('scripts/verify-staging-acceptance.cjs'),/auris-emergency-list-workspace\.js/);assert.doesNotMatch(read('auris-emergency-list-workspace.js'),/\bfetch\(|\bapi\.request\(|\bPOST|\bPATCH|\bDELETE/);});
