const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../auris-emergency-records.js'),'utf8');
function runtime(extra={}){const state={companyId:'a',userId:'u',role:'manager'},ctx={URL,URLSearchParams,location:{search:''},document:{getElementById:()=>null},emEqData:[],isMgr:()=>state.role==='manager',escH:v=>String(v).replace(/</g,'&lt;'),AurisEmergencyListWorkspace:{session:()=>({...state}),assertSession:c=>{if(c.companyId!==state.companyId||c.userId!==state.userId||c.role!==state.role)throw Error('Session changed');}},api:async()=>[],...extra};vm.createContext(ctx);vm.runInContext(source,ctx);return {ctx,state};}
test('equipment read enforces exact company and record',async()=>{const {ctx}=runtime({api:async url=>{assert.match(url,/company_id=eq.a/);return [{id:'r',company_id:'a'}];}});let shown=false;ctx.emEqShowRecord=()=>shown=true;assert.equal(await ctx.emEqOpenRecordRequest({record:'r',company:'a'}),true);assert.equal(shown,true);await assert.rejects(ctx.emEqOpenRecordRequest({record:'r',company:'b'}),/company/);ctx.api=async()=>[{id:'r',company_id:'b'}];assert.equal(await ctx.emEqOpenRecordRequest({record:'r'}),false);});
test('changed sessions and non-manager edit are rejected',async()=>{const {ctx,state}=runtime({location:{search:'?equipmentMode=edit'},api:async()=>[{id:'r',company_id:'a'}]});state.role='viewer';await assert.rejects(ctx.emEqOpenRecordRequest({record:'r'}),/Manager/);state.role='manager';ctx.api=async()=>{state.companyId='b';return [];};await assert.rejects(ctx.emEqOpenRecordRequest({record:'r'}),/Session changed/);});
test('edit loads exact record and resets entry flag',async()=>{const {ctx}=runtime({location:{search:'?equipmentMode=edit'},api:async()=>[{id:'r',company_id:'a'}]});ctx.emEqEdit=async id=>{assert.equal(id,'r');assert.equal(ctx.emEqOpeningRecord,true);assert.equal(ctx.emEqData[0].id,'r');};await ctx.emEqOpenRecordRequest({record:'r'});assert.equal(ctx.emEqOpeningRecord,false);});
test('view fields escape content and contain no editing controls',()=>{const {ctx}=runtime();const html=ctx.emEqRecordFields({floor:0,notes:'<script>bad</script>'},[['floor','Floor'],['notes','Notes']]);assert.match(html,/>0</);assert.match(html,/&lt;script>/);assert.doesNotMatch(html,/<input|<textarea|<script/);});
test('out-of-service action scopes writes and retains audit',async()=>{const calls=[],audits=[];const {ctx}=runtime({api:async(url,options)=>{calls.push({url,options});return [{id:'r',company_id:'a',status:'operational'}];},appConfirmAction:async()=>true,emAudit:(...args)=>audits.push(args),toast:()=>{}});assert.equal(await ctx.emEqRemoveRecord('r'),true);assert.equal(calls[1].options.m,'PATCH');assert.equal(calls[1].options.b.status,'out_of_service');assert.match(calls[1].url,/company_id=eq.a/);assert.equal(audits[0][0],'out_of_service');});
test('changing company during confirmation prevents equipment mutation',async()=>{let writes=0;const {ctx,state}=runtime({api:async(url,options)=>{if(options)writes++;return [{id:'r',company_id:'a',status:'out_of_service'}];},appConfirmDelete:async()=>{state.companyId='b';return true;}});await assert.rejects(ctx.emEqRemoveRecord('r'),/Session changed/);assert.equal(writes,0);});
test('empty mutation response is not reported as success',async()=>{const {ctx}=runtime({api:async(url,options)=>options?[]:[{id:'r',company_id:'a',status:'out_of_service'}],appConfirmDelete:async()=>true});await assert.rejects(ctx.emEqRemoveRecord('r'),/not changed/);});
test('active equipment loader mounts shared register after updating metrics',()=>{const core=fs.readFileSync(path.join(__dirname,'../auris-core.js'),'utf8');const loader=core.slice(core.indexOf('async function emEqLoad(){'),core.indexOf('function emEqShowForm()'));assert.match(loader,/emEqMountRegister\(el,emEqData,ft\)/);assert.ok(loader.indexOf("setM('em3eq-fe'")<loader.indexOf('emEqMountRegister'));});
