const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const read=file=>fs.readFileSync(path.join(__dirname,'..',file),'utf8');
const current={companyId:'co-a',userId:'user-a',name:'Reviewer',role:'manager'};
const inspections=[
  {id:'env-1',company_id:'co-a',inspection_date:'2026-08-20',inspector:'Asha',area:'Chemical store',inspection_type:'regulatory',findings:'Bund damaged',non_conformances:2,overall_rating:'poor',corrective_actions:'Repair bund',next_inspection_date:'2026-09-01',signed_off:false,notes:'Follow-up required',created_at:'2026-08-20'},
  {id:'env-2',company_id:'co-a',inspection_date:'2026-09-10',inspector:'Ben',area:'Office roof',inspection_type:'routine',findings:'Clear',non_conformances:0,overall_rating:'good',corrective_actions:'',next_inspection_date:'2026-10-05',signed_off:true,created_at:'2026-09-10'},
  {id:'foreign',company_id:'co-b',inspection_date:'2026-09-10',area:'Other site',overall_rating:'unacceptable'}
];
function runtime(){
  const identity={company:{id:'co-a'},profile:{id:'user-a',full_name:'Reviewer'},role:'manager'};let mounted,allowed=true,authenticated=true;
  const window={Date,navigator:{onLine:true},AurisPlatformServices:{ready:()=>true,auth:{isAuthenticated:()=>authenticated,current:()=>identity},rbac:{requireAccess:key=>{assert.equal(key,'esg');if(!allowed)throw Error('Access denied');}}},AurisViewEngine:{mount:(host,data,options)=>{mounted={data,options};return mounted;}}};
  vm.runInNewContext(read('auris-esg-list-workspace.js'),window);
  return {api:window.AurisEsgListWorkspace,identity,mounted:()=>mounted,deny:()=>{allowed=false;},signOut:()=>{authenticated=false;},window};
}
test('projection is tenant scoped and preserves environmental findings and next inspection state',()=>{const r=runtime(),before=JSON.stringify(inspections),data=r.api.project(inspections,current,{},new Date('2026-09-16T12:00:00Z'));assert.deepEqual(Array.from(data,x=>x.id),['env-1','env-2']);assert.equal(data[0].reference,'ENV-ENV-1');assert.equal(data[0].next_inspection,'Overdue');assert.deepEqual(Array.from(data[0].attention_flags),['rating_risk','open_non_conformance','next_overdue','signoff_pending']);assert.equal(data[1].signed_off,'Signed off');assert.equal(JSON.stringify(inspections),before);});
test('environmental filters combine type, rating, attention, sign-off and search',()=>{const r=runtime(),select=filters=>r.api.project(inspections,current,{filters},new Date('2026-09-16T12:00:00Z')).map(x=>x.id);assert.deepEqual(select({type:'regulatory'}),['env-1']);assert.deepEqual(select({rating:'good'}),['env-2']);assert.deepEqual(select({attention:'open_non_conformance'}),['env-1']);assert.deepEqual(select({signed:'true'}),['env-2']);assert.deepEqual(select({search:'chemical'}),['env-1']);});
test('unknown environmental values remain visible without unsafe relabelling',()=>{const r=runtime(),data=r.api.project([{id:'x',company_id:'co-a',inspection_date:'2026-09-10',inspection_type:'special',overall_rating:'mystery',next_inspection_date:'bad'}],current,{});assert.equal(data.length,1);assert.equal(data[0].type,'special');assert.equal(data[0].rating,'mystery');assert.equal(data[0].next_inspection,'Not scheduled');});
test('shared environmental register exposes guarded actions and protects sessions',async()=>{const r=runtime(),calls=[];r.api.mount({},inspections,{canEdit:true,openRecord:(id,c)=>calls.push(['open',id,c.companyId]),editRecord:(id,c)=>calls.push(['edit',id,c.companyId])});const m=r.mounted();assert.equal(m.options.moduleKey,'environmental-inspections');assert.deepEqual(Array.from(m.options.actions,x=>x.key),['open','edit']);await m.options.onAction('open',m.data[0]);await m.options.onAction('edit',m.data[0]);assert.deepEqual(calls,[['open','env-1','co-a'],['edit','env-1','co-a']]);for(const change of [x=>x.identity.company.id='co-b',x=>x.identity.profile.id='other',x=>x.identity.role='viewer',x=>x.deny(),x=>x.signOut()]){const x=runtime();x.api.mount({},inspections,{canEdit:true,openRecord:()=>assert.fail('stale action')});const view=x.mounted();change(x);await assert.rejects(view.options.onAction('open',view.data[0]),/changed|denied|Sign in/);}});
test('release wiring publishes the ESG register before the core loader',()=>{const html=read('index.html'),core=read('auris-core.js');assert.ok(html.indexOf('auris-esg-list-workspace.js?')<html.indexOf('auris-core.js?'));assert.match(core,/AurisEsgListWorkspace\.mount\(el,esgInspData/);assert.match(read('sw-assets.js'),/auris-esg-list-workspace\.js/);assert.match(read('scripts/verify-production-smoke.cjs'),/auris-esg-list-workspace\.js/);assert.match(read('scripts/verify-staging-acceptance.cjs'),/auris-esg-list-workspace\.js/);assert.doesNotMatch(read('auris-esg-list-workspace.js'),/\bfetch\(|\bapi\.request\(|\bPOST|\bPATCH|\bDELETE/);});
