const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const read=file=>fs.readFileSync(path.join(__dirname,'..',file),'utf8');
const current={companyId:'co-a',userId:'user-a',name:'Reviewer',role:'manager'};
const certs=[
  {id:'cert-1',company_id:'co-a',cert_number:'FC-001',cert_type:'fire_certificate',premises_name:'Main workshop',address:'1 Harbour Road',occupancy_type:'Factory',issuing_authority:'MFRS',issue_date:'2026-01-01',expiry_date:'2026-09-20',status:'valid',renewal_submitted:false,updated_at:'2026-09-10T10:00:00Z'},
  {id:'cert-2',company_id:'co-a',cert_number:'FC-002',cert_type:'fire_precaution',premises_name:'Warehouse',expiry_date:'2026-08-01',status:'expired',renewal_submitted:true},
  {id:'cert-3',company_id:'co-a',cert_number:'FC-003',cert_type:'occupation_permit',premises_name:'Office block',expiry_date:'2026-12-01',status:'pending_renewal'},
  {id:'foreign',company_id:'co-b',premises_name:'Other company',expiry_date:'2026-09-01',status:'valid'},
  {id:'unscoped',premises_name:'Unscoped',status:'valid'}
];
const inspections=[{id:'insp-1',company_id:'co-a',certificate_id:'cert-1'},{id:'insp-2',company_id:'co-a',certificate_id:'cert-1'},{id:'foreign-insp',company_id:'co-b',certificate_id:'cert-1'}];
const equipment=[{id:'eq-1',company_id:'co-a',certificate_id:'cert-1'},{id:'eq-2',company_id:'co-a',certificate_id:'cert-2'}];
function runtime(){
  const identity={company:{id:'co-a'},profile:{id:'user-a',full_name:'Reviewer'},role:'manager'};let mounted,allowed=true,authenticated=true;
  const window={Date,navigator:{onLine:true},AurisPlatformServices:{ready:()=>true,auth:{isAuthenticated:()=>authenticated,current:()=>identity},rbac:{requireAccess:key=>{assert.equal(key,'fire');if(!allowed)throw Error('Access denied');}}},AurisViewEngine:{mount:(host,data,options)=>{mounted={data,options};return mounted;}}};
  vm.runInNewContext(read('auris-fire-list-workspace.js'),window);
  return {api:window.AurisFireListWorkspace,identity,mounted:()=>mounted,deny:()=>{allowed=false;},signOut:()=>{authenticated=false;},window};
}
test('projection is tenant scoped and preserves expiry, renewal and linked compliance counts',()=>{const r=runtime(),before=JSON.stringify(certs),data=r.api.project(certs,current,{inspections,equipment},new Date('2026-09-15T12:00:00Z'));assert.deepEqual(data.map(x=>x.id),['cert-1','cert-2','cert-3']);assert.equal(data[0].reference,'FC-001');assert.equal(data[0].expiry,'Due soon');assert.equal(data[0].days_left,5);assert.equal(data[0].inspections,2);assert.equal(data[0].equipment,1);assert.equal(data[1].attention,'Expired');assert.equal(data[1].renewal,'Submitted');assert.equal(JSON.stringify(certs),before);});
test('certificate filters combine type, status, attention and search',()=>{const r=runtime(),select=filters=>r.api.project(certs,current,{filters,inspections,equipment},new Date('2026-09-15T12:00:00Z')).map(x=>x.id);assert.deepEqual(select({status:'expired'}),['cert-2']);assert.deepEqual(select({type:'occupation_permit'}),['cert-3']);assert.deepEqual(select({attention:'renewal_pending'}),['cert-2','cert-3']);assert.deepEqual(select({attention:'expiring_soon'}),['cert-1']);assert.deepEqual(select({search:'harbour',status:'valid'}),['cert-1']);});
test('unknown certificate values remain visible without unsafe relabelling',()=>{const r=runtime(),data=r.api.project([{id:'x',company_id:'co-a',premises_name:'Unknown',cert_type:'special',status:'awaiting_review'}],current,{});assert.equal(data.length,1);assert.equal(data[0].type,'special');assert.equal(data[0].status,'awaiting review');});
test('shared fire register exposes guarded open and manager edit actions',async()=>{const r=runtime(),calls=[];r.api.mount({},certs,{inspections,equipment,canEdit:true,openRecord:(id,c)=>calls.push(['open',id,c.companyId]),editRecord:(id,c)=>calls.push(['edit',id,c.companyId])});const m=r.mounted();assert.equal(m.options.moduleKey,'fire-certificates');assert.deepEqual(Array.from(m.options.actions,x=>x.key),['open','edit']);await m.options.onAction('open',m.data[0]);await m.options.onAction('edit',m.data[0]);assert.deepEqual(calls,[['open','cert-1','co-a'],['edit','cert-1','co-a']]);for(const change of [x=>x.identity.company.id='co-b',x=>x.identity.profile.id='other',x=>x.identity.role='viewer',x=>x.deny(),x=>x.signOut()]){const x=runtime();x.api.mount({},certs,{canEdit:true,openRecord:()=>assert.fail('stale action')});const view=x.mounted();change(x);await assert.rejects(view.options.onAction('open',view.data[0]),/changed|denied|Sign in/);}});
test('release wiring publishes the Fire Certificates register before the core loader',()=>{const html=read('index.html'),core=read('auris-core.js');assert.ok(html.indexOf('auris-fire-list-workspace.js?')<html.indexOf('auris-core.js?'));assert.match(core,/AurisFireListWorkspace\.mount\(workspace,fireAllCerts/);assert.match(read('sw-assets.js'),/auris-fire-list-workspace\.js/);assert.match(read('scripts/verify-production-smoke.cjs'),/auris-fire-list-workspace\.js/);assert.match(read('scripts/verify-staging-acceptance.cjs'),/auris-fire-list-workspace\.js/);assert.doesNotMatch(read('auris-fire-list-workspace.js'),/\bfetch\(|\bapi\.request\(|\bPOST|\bPATCH|\bDELETE/);});
