const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'../auris-fire-records.js'),'utf8');
function runtime(extra={}){const state={companyId:'a',userId:'u',role:'manager'},ctx={URL,URLSearchParams,location:{search:''},fireAllCerts:[],isMgr:()=>state.role==='manager',escH:v=>String(v).replace(/</g,'&lt;'),AurisFireListWorkspace:{session:()=>({...state}),assertSession:c=>{if(c.companyId!==state.companyId||c.userId!==state.userId||c.role!==state.role)throw Error('Session changed');}},api:async()=>[],...extra};vm.createContext(ctx);vm.runInContext(source,ctx);return {ctx,state};}
test('certificate read requires exact company and record',async()=>{const {ctx}=runtime({api:async url=>{assert.match(url,/company_id=eq.a/);return url.startsWith('/fire_certificates?')?[{id:'r',company_id:'a'}]:[];}});let shown=false;ctx.fireShowRecord=()=>{shown=true;};assert.equal(await ctx.fireOpenRecordRequest({record:'r',company:'a'}),true);assert.equal(shown,true);await assert.rejects(ctx.fireOpenRecordRequest({record:'r',company:'b'}),/company/);});
test('foreign records and changed sessions are discarded',async()=>{const {ctx,state}=runtime({api:async()=>[{id:'r',company_id:'b'}]});assert.equal(await ctx.fireOpenRecordRequest({record:'r'}),false);ctx.api=async()=>{state.companyId='b';return [];};await assert.rejects(ctx.fireOpenRecordRequest({record:'r'}),/Session changed/);});
test('certificate edit and save require manager in original context',async()=>{const {ctx,state}=runtime({location:{search:'?fireMode=edit'},api:async()=>[{id:'r',company_id:'a'}]});state.role='viewer';await assert.rejects(ctx.fireOpenRecordRequest({record:'r'}),/Manager/);state.role='manager';ctx.fireRecordContext={...state};state.userId='other';assert.throws(()=>ctx.fireAssertEditor(),/Session changed/);});
test('related rows are company and certificate scoped and failures are explicit',async()=>{const {ctx}=runtime({api:async url=>{assert.match(url,/certificate_id=eq.r/);if(url.includes('fire_equipment'))throw Error('offline');return [{company_id:'a',certificate_id:'r'},{company_id:'b',certificate_id:'r'},{company_id:'a',certificate_id:'other'}];}});const data=await ctx.fireReadHistory({id:'r'},ctx.AurisFireListWorkspace.session());assert.equal(data[0].rows.length,1);assert.match(ctx.fireHistoryHtml(data[1]),/could not be loaded/);assert.doesNotMatch(ctx.fireHistoryHtml(data[1]),/No related records/);});
test('document links reject executable or credential-bearing URLs',()=>{const {ctx}=runtime();for(const value of ['javascript:alert(1)','data:text/html,test','https://user:pass@example.com','relative.pdf'])assert.equal(ctx.fireDocumentHref(value),'');assert.equal(ctx.fireDocumentHref('https://example.com/certificate.pdf'),'https://example.com/certificate.pdf');});
test('certificate fields are escaped, preserve zero, and contain no editing controls',()=>{const {ctx}=runtime();const html=ctx.fireRecordFields({floor_area:0,notes:'<script>bad</script>'},[['floor_area','Area'],['notes','Notes']]);assert.match(html,/>0</);assert.match(html,/&lt;script>/);assert.doesNotMatch(html,/<input|<textarea|<script/);});
