const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../auris-fleet-records.js'),'utf8');
function runtime(extra={}){const state={companyId:'a',userId:'u',role:'manager'},ctx={URL,URLSearchParams,location:{search:''},fleetVehicles:[],isMgr:()=>state.role==='manager',AurisFleetListWorkspace:{session:()=>({...state}),assertSession:c=>{if(c.companyId!==state.companyId||c.userId!==state.userId||c.role!==state.role)throw Error('Session changed');}},api:async()=>[],fleetFuelMatchesVehicle:(f,v)=>f.vehicle_equipment===v.registration_number,...extra};vm.createContext(ctx);vm.runInContext(source,ctx);return {ctx,state};}
test('fleet history excludes foreign companies and equipment and reports failures',async()=>{const {ctx}=runtime({api:async url=>{assert.match(url,/company_id=eq.a/);if(url.includes('maintenance'))throw Error('offline');return [{company_id:'a',tool_id:'car',vehicle_equipment:'REG'},{company_id:'b',tool_id:'car',vehicle_equipment:'REG'},{company_id:'a',tool_id:'other',vehicle_equipment:'OTHER'}];}});const result=await ctx.fleetReadRecordHistory({id:'car',registration_number:'REG'},ctx.AurisFleetListWorkspace.session());assert.equal(result[0].rows.length,1);assert.equal(result[1].rows.length,1);assert.equal(result[2].error,true);});
test('stale accounts and roles cannot save fleet forms',()=>{for(const key of ['companyId','userId','role']){const {ctx,state}=runtime();const captured={...state};state[key]='changed';assert.throws(()=>ctx.fleetAssertEditor(captured),/Session changed/);}const {ctx,state}=runtime();state.role='viewer';assert.throws(()=>ctx.fleetAssertEditor({...state}),/Manager/);});
test('linked fleet record requires company ownership and actual vehicle',async()=>{const {ctx}=runtime({api:async()=>[{id:'car',company_id:'a',is_vehicle:false}]});await assert.rejects(ctx.fleetOpenLinkedRecord({record:'car',company:'b'}),/company/);assert.equal(await ctx.fleetOpenLinkedRecord({record:'car',company:'a'}),false);});
test('manager editor loads exact vehicle while viewer cannot edit',async()=>{const {ctx,state}=runtime({location:{search:'?fleetMode=edit'},api:async()=>[{id:'car',company_id:'a',is_vehicle:true}]});let opened;ctx.fleetOpenVehicleForm=id=>{assert.equal(ctx.fleetOpeningLinkedRecord,true);opened=id;};assert.equal(await ctx.fleetOpenLinkedRecord({record:'car'}),true);assert.equal(opened,'car');assert.equal(ctx.fleetOpeningLinkedRecord,false);state.role='viewer';await assert.rejects(ctx.fleetOpenLinkedRecord({record:'car'}),/Manager/);});
test('history arriving after company switch is discarded',async()=>{const {ctx,state}=runtime();const captured={...state};ctx.api=async()=>{state.companyId='b';return [];};await assert.rejects(ctx.fleetReadRecordHistory({id:'car'},captured),/Session changed/);});
test('large history explicitly advertises its display limit',async()=>{const {ctx}=runtime({api:async()=>Array.from({length:501},()=>({company_id:'a',tool_id:'car',equipment_id:'car',vehicle_equipment:'REG'}))});const result=await ctx.fleetReadRecordHistory({id:'car',registration_number:'REG'},ctx.AurisFleetListWorkspace.session());assert.ok(result.every(x=>x.limited&&x.rows.length===500));});
