const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const c={};vm.createContext(c);vm.runInContext(fs.readFileSync(path.join(__dirname,'../auris-form-draft.js'),'utf8'),c);
function setup(){const rows=new Map(),storage={getItem:k=>rows.get(k)||null,setItem:(k,v)=>rows.set(k,v),removeItem:k=>rows.delete(k)},opts={key:'draft',storage,context:{companyId:'c',userId:'u',role:'admin',year:2026,id:'new'},baseline:{name:'Original'},now:()=>100000,valid:value=>!!value&&typeof value.name==='string'};return {rows,storage,opts,open:()=>c.AurisFormDraft.create(opts)};}
test('clean forms create no recoverable draft; dirty values persist until explicit restoration',()=>{const h=setup(),a=h.open();a.capture({name:'Original'});assert.equal(h.rows.size,0);a.capture({name:'Draft'});const b=h.open();assert.equal(b.dirty({name:'Original'}),false);assert.equal(b.candidate().value.name,'Draft');assert.equal(b.capture({name:'Accidental input'}),false);assert.equal(b.restore().name,'Draft');assert.equal(b.candidate(),null);});
test('returning to initial values and discard clear recovery',()=>{const h=setup(),a=h.open();a.capture({name:'Draft'});a.capture({name:'Original'});assert.equal(h.rows.size,0);a.capture({name:'Draft'});a.discard();assert.equal(h.open().candidate(),null);});
for(const field of ['companyId','userId','role','year','id'])test('draft cannot restore into another '+field,()=>{const h=setup();h.open().capture({name:'Private draft'});h.opts.context={...h.opts.context,[field]:'other'};assert.equal(h.open().candidate(),null);});
test('changed loaded values block restoration while preserving text for review',()=>{const h=setup();h.open().capture({name:'Draft'});h.opts.baseline={name:'Changed by colleague'};const next=h.open();assert.equal(next.blocked(),true);assert.equal(next.restore(),null);assert.equal(next.candidate().value.name,'Draft');});
test('a started write protects recovery even if the page disappears before its response',()=>{const h=setup(),a=h.open();a.capture({name:'Draft'});a.protect({name:'Draft'});assert.equal(a.capture({name:'Changed after save'}),false);const next=h.open();assert.equal(next.blocked(),true);assert.equal(next.restore(),null);assert.equal(next.candidate().value.name,'Draft');next.discard();assert.equal(h.open().candidate(),null);});
test('expiry, future timestamps, invalid values and malformed JSON cannot be restored',()=>{for(const mutate of [d=>d.savedAt-=86400000,d=>d.savedAt++,d=>d.value=null]){const h=setup();h.open().capture({name:'Draft'});const d=JSON.parse(h.rows.get('draft'));mutate(d);h.rows.set('draft',JSON.stringify(d));assert.equal(h.open().candidate(),null);}const h=setup();h.rows.set('draft','<broken');assert.equal(h.open().candidate(),null);});
test('storage failure does not claim the draft was retained',()=>{const h=setup(),a=h.open();h.storage.setItem=()=>{throw Error('quota');};assert.equal(a.capture({name:'Draft'}),false);assert.match(a.error(),/only in this open form/);assert.equal(a.dirty({name:'Draft'}),true);});
test('failed protection removes an older restorable draft before allowing a write',()=>{const h=setup(),a=h.open();a.capture({name:'Draft'});h.storage.setItem=()=>{throw Error('quota');};a.protect({name:'Draft'});assert.equal(h.rows.size,0);assert.match(a.error(),/Keep this form open/);});
test('a write cannot proceed when neither marking nor removing the old draft is possible',()=>{const h=setup(),a=h.open();a.capture({name:'Draft'});h.storage.setItem=h.storage.removeItem=()=>{throw Error('blocked');};assert.throws(()=>a.protect({name:'Draft'}),/could not be protected/);});
