const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),read=file=>fs.readFileSync(path.join(root,file),'utf8');
function runtime(){const window={console,Date,URL,Promise,Set};window.globalThis=window;vm.runInNewContext(read('auris-integration-engine.js'),window);return window.AurisIntegrationEngine;}
const context={context:()=>({companyId:'co-a',userId:'reviewer-1',role:'hse_manager'})};

test('exact-record reconciliation requires identity, reference and source revision',()=>{const api=runtime(),valid={record_id:'11111111-1111-4111-8111-111111111111',action_ref:'ACT-22',expected_updated_at:'2026-09-02T08:00:00Z',title:'Guard update',status:'open',priority:'high',target_date:'2026-09-30'};let plan=api.importPlan('action_reconciliation',[valid],context);assert.equal(plan.executable,true);assert.equal(plan.accepted[0].company_id,'co-a');for(const [field,value,code] of [['record_id','bad','invalid_record_id'],['action_ref','','action_reference_required'],['expected_updated_at','','expected_revision_required']]){plan=api.importPlan('action_reconciliation',[{...valid,[field]:value}],context);assert.equal(plan.rejected[0].code,code);}plan=api.importPlan('action_reconciliation',[valid,valid],context);assert.equal(plan.rejected[0].code,'duplicate_reference');});

test('staging exposes only reviewed fields and strips tenant context',()=>{const api=runtime(),plan=api.importPlan('action_reconciliation',[{record_id:'11111111-1111-4111-8111-111111111111',action_ref:'ACT-22',expected_updated_at:'2026-09-02T08:00:00Z',title:'Guard update',description:'Reviewed',status:'in_progress',priority:'critical',target_date:'2026-09-30'}],context),staged=api.stagedReconciliation(plan);assert.equal(staged.mode,'staged');assert.equal(staged.rowCount,1);assert.equal(staged.rows[0].record_id,'11111111-1111-4111-8111-111111111111');assert.equal(Object.hasOwn(staged.rows[0],'company_id'),false);assert.deepEqual(Object.keys(staged.rows[0]),['record_id','action_ref','expected_updated_at','title','description','status','priority','target_date']);});

test('database execution is exact, atomic, service-role only and snapshot-backed',()=>{const sql=read('supabase/migrations/20260902030000_modular_foundation_22_reconciliation.sql');for(const marker of ['operation','target_record_id','expected_updated_at','before_data','stage_action_reconciliation','exact company action','export a fresh update template','apply_governed_data_batch','for update','revision conflict','rollback_action_import_batch','reverted_at','24 hours','produced new evidence','audit_events'])assert.match(sql,new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i'));assert.match(sql,/revoke all on function public\.apply_governed_data_batch\(uuid,uuid\) from public,anon,authenticated/i);assert.match(sql,/grant execute on function public\.apply_governed_data_batch\(uuid,uuid\) to service_role/i);assert.match(sql,/where id=target_id and company_id=p_company_id for share/i);assert.match(sql,/where id=imported\.target_record_id and company_id=batch\.company_id for update/i);});

test('Integration Centre provides separate update templates, validation and governed execution',()=>{const centre=read('auris-integration-centre.js'),worker=read('api/process-imports.js'),html=read('index.html');for(const marker of ['Export update template','Validate updates','Stage reviewed update','record_id:id','expected_updated_at:updated_at','action_reconciliation','stage_action_reconciliation','operation','status','Safe rollback'])assert.match(centre,new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i'));assert.match(worker,/apply_governed_data_batch/);assert.doesNotMatch(worker,/rpc\('apply_action_import_batch'/);assert.match(html,/modular-foundation-29/);assert.match(html,/auris-integration-centre\.js\?v=20260902-24/);});
