const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),read=file=>fs.readFileSync(path.join(root,file),'utf8');
function runtime(){const window={console,Date,URL,Promise,Set};window.globalThis=window;vm.runInNewContext(read('auris-integration-engine.js'),window);return window.AurisIntegrationEngine;}
const context={context:()=>({companyId:'co-a',userId:'requester-1',role:'hse_manager'})};

test('active create mappings rename reviewed columns and controlled values only',()=>{const api=runtime(),profile={id:'mapping-1',company_id:'co-a',name:'Contractor actions',operation:'create',field_map:{'External Ref':'action_ref','Summary':'title','State':'status','Urgency':'priority','Due On':'target_date'},value_map:{status:{OpenItem:'open',Working:'in_progress'},priority:{Urgent:'critical'}},mapping_fingerprint:'12345678901234567890123456789012',status:'active',revision:3},plan=api.mappedImport(profile,'External Ref,Summary,State,Urgency,Due On\nEXT-23,Guard repair,Working,Urgent,2026-10-01',context);assert.equal(plan.executable,true);assert.equal(plan.mappingProfileId,'mapping-1');assert.equal(plan.mappingRevision,3);assert.equal(plan.accepted[0].action_ref,'EXT-23');assert.equal(plan.accepted[0].status,'in_progress');assert.equal(plan.accepted[0].priority,'critical');const staged=api.stagedMappedImport(plan);assert.equal(staged.mode,'staged_mapped');assert.equal(staged.rows[0].company_id,undefined);assert.equal(staged.mappingProfileId,'mapping-1');});

test('mapping validation rejects hidden targets, duplicate targets and unsafe execution states',()=>{const api=runtime(),base={id:'mapping-1',company_id:'co-a',operation:'create',field_map:{Reference:'action_ref'},status:'active',revision:1};assert.throws(()=>api.mappingProfile({...base,field_map:{Reference:'company_id'}}),/not approved/);assert.throws(()=>api.mappingProfile({...base,field_map:{Reference:'action_ref',Duplicate:'action_ref'}}),/only once/);assert.throws(()=>api.mappingProfile({...base,field_map:{Title:'title'}}),/missing required field/);assert.throws(()=>api.mappingProfile({...base,field_map:{Reference:'action_ref'},value_map:{title:{x:'y'}}}),/limited to mapped status/);assert.throws(()=>api.mappedImport({...base,status:'draft'},'Reference\nEXT-1',context),/approved active/);assert.throws(()=>api.mappedImport({...base,company_id:'co-b'},'Reference\nEXT-1',context),/another company/);});

test('update mappings preserve exact identity and revision requirements',()=>{const api=runtime(),profile={id:'mapping-2',company_id:'co-a',name:'Legacy updates',operation:'update',field_map:{'Row ID':'record_id','Action No':'action_ref','Revision Time':'expected_updated_at','State':'status'},value_map:{status:{Working:'in_progress'}},mapping_fingerprint:'abcdefabcdefabcdefabcdefabcdefab',status:'active',revision:4},csv='Row ID,Action No,Revision Time,State\n11111111-1111-4111-8111-111111111111,ACT-23,2026-09-02T09:00:00Z,Working',plan=api.mappedImport(profile,csv,context);assert.equal(plan.moduleKey,'action_reconciliation');assert.equal(plan.accepted[0].record_id,'11111111-1111-4111-8111-111111111111');assert.equal(plan.accepted[0].expected_updated_at,'2026-09-02T09:00:00Z');assert.equal(plan.accepted[0].status,'in_progress');assert.throws(()=>api.mappedImport(profile,'Row ID,Action No,State\n11111111-1111-4111-8111-111111111111,ACT-23,Working',context),/missing source column Revision Time/);});

test('database profiles are tenant isolated, independently approved and exact-revision bound',()=>{const sql=read('supabase/migrations/20260902040000_modular_foundation_23_import_mappings.sql');for(const marker of ['import_mapping_profiles','field_map','value_map','mapping_fingerprint','row level security','save_import_mapping_profile','set_import_mapping_status','requester cannot decide','stage_mapped_action_batch','exact approved active mapping revision','mapping_profile_id','mapping_revision','Mapped import profile is no longer the exact approved active revision','audit_events'])assert.match(sql,new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i'));assert.match(sql,/create policy import_mapping_profiles_company_admin[\s\S]*actor\.company_id=import_mapping_profiles\.company_id/i);assert.match(sql,/revoke all on function public\.stage_mapped_action_batch[\s\S]*from public,anon/i);assert.match(sql,/grant execute on function public\.stage_mapped_action_batch[\s\S]*to authenticated/i);assert.doesNotMatch(sql,/execute\s+format|\beval\b/i);});

test('Integration Centre exposes reviewed profile editing and the existing approval pipeline',()=>{const centre=read('auris-integration-centre.js'),css=read('auris-integration-centre.css'),html=read('index.html');for(const marker of ['Reusable CSV mapping profiles','Column mappings','Controlled value aliases','Save mapping draft','mapping-review','mapping-active','mapping-rejected','mapping-paused','Validate with ','stage_mapped_action_batch','mapping_profile_id,mapping_revision,mapping_fingerprint'])assert.match(centre,new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i'));assert.match(css,/aic-mapping-editor/);assert.match(css,/@media\(max-width:420px\)/);assert.match(html,/modular-foundation-29/);assert.match(html,/auris-integration-engine\.js\?v=20260902-24/);});
