const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const context=vm.createContext({});vm.runInContext(fs.readFileSync('auris-risk-library.js','utf8'),context);const lib=context.AurisRiskLibrary;
const core=fs.readFileSync('auris-core.js','utf8');
function fn(name){const start=core.indexOf('function '+name+'(');return core.slice(start,core.indexOf('\n}',start)+2);}
vm.runInContext('var raMatrixSnapshot=null;function raRiskLevelFromScore(){throw Error("Unexpected fallback");}\n'+fn('raRiskLevelFromFactors'),context);
test('custom matrix validates every cell and preserves the original 5x5 defaults',()=>{const m=lib.defaultMatrix();assert.equal(lib.validateMatrix(m).cells[4][4],'Very High');for(let p=1;p<=5;p++)for(let s=1;s<=5;s++)assert.equal(context.raRiskLevelFromFactors(s,p),m.cells[p-1][s-1]);});
test('invalid and non-monotonic imported matrices are rejected',()=>{for(const change of [m=>m.cells.pop(),m=>m.cells[0].pop(),m=>m.cells[0][0]='Critical<script>',m=>m.cells[4][4]='Low',m=>m.severity=[],m=>m.version=2]){const m=lib.defaultMatrix();change(m);assert.throws(()=>lib.validateMatrix(m));}});
test('record snapshot determines print ratings independently of the current editor',()=>{const m=lib.defaultMatrix();m.cells[0][0]='Low';m.cells[0][1]='Low';m.cells[1][0]='Low';context.raMatrixSnapshot=m;assert.equal(context.raRiskLevelFromFactors(1,1),'Low');assert.equal(context.raRiskLevelFromFactors(1,1,null),'Very Low');assert.equal(context.raRiskLevelFromFactors(1,1,lib.defaultMatrix()),'Very Low');assert.match(core,/raRiskMatrixPrintHtml\(ra.risk_matrix_snapshot\|\|null\)/);});
test('template import strips record identity and rejects nested executable-shaped data',()=>{const template=lib.validateTemplate({version:1,kind:'assessment-template',name:'QA',type:'task',rows:[{id:'old',company_id:'foreign',hazard:'Lifting',rs:3,nested:{value:'bad'}}],matrix:lib.defaultMatrix()});assert.equal(template.rows[0].hazard,'Lifting');assert.equal(template.rows[0].id,undefined);assert.equal(template.rows[0].company_id,undefined);assert.equal(template.rows[0].nested,undefined);assert.throws(()=>lib.validateTemplate({...template,rows:Array(101).fill({})}));});
test('existing assessments load their saved matrix and custom saves require the schema',()=>{assert.match(fn('raOpen'),/savedMatrix=x.risk_matrix_snapshot\|\|null/);assert.match(core,/select=risk_matrix_snapshot&company_id=eq\./);assert.match(core,/risk_matrix_snapshot:raMatrixSnapshot/);});
test('stored PDF attachments become validated blobs without allowing arbitrary data URLs',()=>{const pdf=vm.createContext({Blob,Uint8Array,atob});vm.runInContext(fn('dcInlinePdfBlob'),pdf);assert.equal(pdf.dcInlinePdfBlob('data:text/html;base64,PHNjcmlwdD4='),null);assert.throws(()=>pdf.dcInlinePdfBlob('data:application/pdf;base64,PHNjcmlwdD4='));assert.equal(pdf.dcInlinePdfBlob('data:application/pdf;base64,'+Buffer.from('%PDF-1.4\n%%EOF').toString('base64')).type,'application/pdf');});
test('group photo validation excludes active content and oversized payloads',()=>{const c=vm.createContext({window:{}});vm.runInContext(fs.readFileSync('auris-attendance-photo.js','utf8'),c);const valid=c.window.AurisAttendancePhoto.valid;assert.equal(valid({data:'data:image/jpeg;base64,/9j/2Q=='}),true);for(const data of ['data:image/svg+xml;base64,PHN2Zz4=','javascript:alert(1)','data:image/jpeg;base64,'+'A'.repeat(1800000)])assert.equal(valid({data}),false);});
