const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const read=f=>fs.readFileSync(path.join(__dirname,'..',f),'utf8');
function harness(kind='objective'){
 const nodes={},store=new Map(),listeners={},modal={id:kind==='objective'?'obj-modal':'kpi-edit-modal',style:{display:'flex'},listeners:{},querySelector:s=>s==='[data-editor-draft]'?modal.bar:null,querySelectorAll:s=>s.includes('data-ind-row')?modal.rows:controls,addEventListener(k,fn){this.listeners[k]=fn;}};
 const c={console,Date,role:'admin',kpiSelectedColor:'#1D9E75',kpiIndicators:[],activeRole:()=>c.role,kpiObjectiveCheckContext(){if(!c.allowed)throw Error('Denied');},kpiDefinitionCheckContext(){if(!c.allowed)throw Error('Denied');},allowed:true,kpiXSelectedPlannedMonths:()=>[3,6,9,12],kpiXSetPlannedMonths(){},kpiXDefaultPlannedMonths:()=>[],kpiRenderObjectiveColour(){},kpiXEditorDraftKey:id=>'legacy:'+id,sessionStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)},addEventListener(k,fn){listeners[k]=fn;},document:{addEventListener(k,fn){listeners[k]=fn;},getElementById:id=>id===modal.id?modal:nodes[id]||null,createElement:()=>bar()}};
 function node(id,value=''){return nodes[id]={id,value,tagName:'INPUT',disabled:false,hidden:false,textContent:'',listeners:{},setAttribute(){},addEventListener(k,fn){this.listeners[k]=fn;},focus(){c.focus=id;},closest:()=>null,matches:()=>id==='close'};}
 function bar(){const parts={p:node('note'),'[data-draft-restore]':node('restore'),'[data-draft-discard]':node('discard'),details:node('preview')};parts.details.querySelector=()=>node('previewText');const element={setAttribute(){},querySelector:s=>parts[s],remove(){modal.bar=null;}};return element;}
 const ids=kind==='objective'?['obj-name','obj-code','obj-year']:['kpi-name','kpi-code','kpi-obj-sel','kpi-freq','kpi-description','kpi-resp','kpi-data-provider','kpi-data-source','kpi-reviewer','kpi-approver'];
 const controls=ids.map(id=>node(id,id.endsWith('name')?'Original':id==='obj-year'?'2026':''));controls.push(node('close'),node('save'));
 const title=node(kind==='objective'?'obj-modal-title':'kpi-modal-title');title.parentElement={insertAdjacentElement(_position,bar){modal.bar=bar;}};
 const ctx={companyId:'c',actorId:'u',viewYear:2026,year:2026,editId:kind==='objective'?'o':null,kpiId:kind==='kpi'?'k':null};modal[kind==='objective'?'_kpiObjectiveContext':'_kpiDefinitionContext']=ctx;
 function row(id,name){const fields={'.ind-name-input':{value:name},'.ind-target-input':{value:'4'},'.ind-op-input':{value:'gte'},'.ind-unit-input':{value:'count'},'.ind-ytd-input':{value:'sum'}};return {getAttribute:()=>id,querySelector:s=>fields[s]};}
 modal.rows=[row('i','Original indicator')];Object.defineProperty(node('kpi-indicators-list'),'innerHTML',{set(){modal.rows=[];}});c.kpiAddIndicatorRow=(name,target,op,unit,ytd,id)=>modal.rows.push(row(id,name));
 let answer;
 c.kpiEditorConfirmArchive=()=>new Promise(resolve=>{answer=resolve;});c.closeKpiModal=()=>{if(c.KpiEditorDrafts.close(modal))modal.style.display='none';};
 c.KpiEditorDraftFields={key:c.kpiXEditorDraftKey,selectedMonths:c.kpiXSelectedPlannedMonths,setMonths:c.kpiXSetPlannedMonths,defaultMonths:c.kpiXDefaultPlannedMonths};
 c.window=c;vm.createContext(c);vm.runInContext(read('auris-form-draft.js'),c);vm.runInContext(read('kpi-editor-drafts.js'),c);
 function begin(){modal.style.display='flex';c.KpiEditorDrafts.begin(modal);}
 begin();return {c,nodes,modal,store,listeners,begin,ctx,answer:v=>answer(v),name:nodes[ids[0]],capture:()=>c.KpiEditorDrafts.capture(modal),save:()=>c.KpiEditorDrafts.canSave(modal)};
}
for(const kind of ['objective','kpi']){
 test(kind+' dirty close keeps input until an explicit discard is confirmed',async()=>{const h=harness(kind);h.name.value='Unsaved';h.capture();h.c.closeKpiModal();assert.equal(h.modal.style.display,'flex');h.answer(false);await Promise.resolve();assert.equal(h.name.value,'Unsaved');assert.equal(h.store.size,1);h.c.closeKpiModal();h.answer(true);await Promise.resolve();assert.equal(h.modal.style.display,'none');assert.equal(h.store.size,0);});
 test(kind+' recovered draft requires a choice, locks Save, and restores exact input',()=>{const h=harness(kind);h.name.value='Recovered';h.capture();h.name.value='Original';h.begin();assert.equal(h.name.value,'Original');assert.equal(h.name.disabled,true);assert.equal(h.save(),false);h.nodes.restore.listeners.click();assert.equal(h.name.value,'Recovered');assert.equal(h.name.disabled,false);assert.equal(h.save(),true);});
 test(kind+' discard restores loaded values and clears recovery without requests',async()=>{const h=harness(kind);h.name.value='Discard me';h.capture();const work=h.nodes.discard.listeners.click();h.answer(true);await work;assert.equal(h.name.value,'Original');assert.equal(h.store.size,0);assert.equal(h.save(),true);});
 test(kind+' changed saved values and uncertain outcomes offer review, not replay',()=>{const h=harness(kind);h.name.value='Draft';h.capture();h.name.value='Changed record';h.begin();assert.equal(h.nodes.restore.disabled,true);assert.equal(h.modal._editorDraft.draft.candidate().value.fields[h.name.id],'Draft');assert.equal(h.save(),false);});
 test(kind+' role change blocks capture, restoration and save',()=>{const h=harness(kind);h.name.value='Private';h.capture();h.c.role='employee';const before=[...h.store];h.capture();assert.deepEqual([...h.store],before);assert.equal(h.save(),false);});
 test(kind+' beforeunload and module navigation retain unsaved input',()=>{const h=harness(kind);h.name.value='Keep';h.capture();let blocked=0;h.listeners.beforeunload({preventDefault(){blocked++;}});h.listeners['auris:module-before-leave']({preventDefault(){blocked++;}});assert.equal(blocked,2);assert.equal(h.modal.style.display,'flex');});
 test(kind+' success clears only this captured session, and closes without a discard prompt',()=>{const h=harness(kind);h.name.value='Save me';h.capture();h.c.KpiEditorDrafts.protect(h.modal);h.c.KpiEditorDrafts.complete(h.modal);h.c.closeKpiModal();assert.equal(h.modal.style.display,'none');assert.equal(h.store.size,0);});
 test(kind+' unconfirmed write is review-only after reopening',()=>{const h=harness(kind);h.name.value='Potentially saved';h.capture();h.c.KpiEditorDrafts.protect(h.modal);h.modal[kind==='objective'?'_kpiObjectiveUncertain':'_kpiDefinitionWritten']=true;h.c.closeKpiModal();h.modal._kpiObjectiveUncertain=false;h.modal._kpiDefinitionWritten=false;h.name.value='Original';h.begin();assert.equal(h.nodes.restore.disabled,true);assert.equal(h.save(),false);});
}
test('indicator identities survive explicit recovery even after a rename',()=>{const h=harness('kpi');h.modal.rows[0].querySelector('.ind-name-input').value='Renamed';h.capture();h.modal.rows[0].querySelector('.ind-name-input').value='Original indicator';h.begin();h.nodes.restore.listeners.click();assert.equal(h.modal.rows[0].getAttribute('data-indicator-id'),'i');assert.equal(h.modal.rows[0].querySelector('.ind-name-input').value,'Renamed');});
test('restoration waits for people refresh so late option loading cannot overwrite recovered people',()=>{const h=harness('kpi');h.name.value='Recovered';h.capture();h.name.value='Original';h.begin();const query=h.modal.querySelector;let pending=true;h.modal.querySelector=s=>s==='[aria-busy="true"]'&&pending?{}:query(s);h.c.KpiEditorDrafts.refresh(h.modal);assert.equal(h.nodes.restore.disabled,true);h.nodes.restore.listeners.click();assert.equal(h.name.value,'Original');pending=false;h.c.KpiEditorDrafts.refresh(h.modal);assert.equal(h.nodes.restore.disabled,false);h.nodes.restore.listeners.click();assert.equal(h.name.value,'Recovered');});
test('legacy drafts remain available for review without assuming a safe write outcome',()=>{const h=harness('kpi');h.store.set('legacy:k',JSON.stringify({savedAt:Date.now(),schemaVersion:3,fields:{'kpi-name':'Old draft'},indicators:[{indicatorId:'i',name:'Original indicator',target:4,operator:'gte',unit:'',ytd:'sum'}]}));h.begin();assert.equal(h.nodes.restore.disabled,true);assert.equal(h.modal._editorDraft.draft.candidate().value.indicators[0].indicatorId,'i');});
test('new role uses a separate recovery key without erasing an existing role draft',()=>{const h=harness();h.name.value='Admin draft';h.capture();const existing=[...h.store.keys()][0];h.c.role='manager';h.name.value='Original';h.begin();h.name.value='Manager draft';h.capture();assert.equal(h.store.size,2);assert.equal(JSON.parse(h.store.get(existing)).value.fields['obj-name'],'Admin draft');});
test('all persistence paths protect recovery before their first write and clear only on completion',()=>{for(const source of [read('kpi-definition-editor.js'),read('auris-core.js')])assert.match(source,/KpiEditorDrafts\.protect\(modal\)/);assert.match(read('auris-core.js'),/KpiEditorDrafts\.close\(e\)/);for(const file of ['auris-form-draft.js','kpi-editor-drafts.js'])assert.ok(read('index.html').includes(file));});

test('a changed server revision makes an older KPI draft review-only even when displayed fields match',()=>{const h=harness('kpi');h.ctx.revision=1;h.begin();h.name.value='Draft';h.capture();h.name.value='Original';h.ctx.revision=2;h.begin();assert.equal(h.nodes.restore.disabled,true);assert.equal(h.save(),false);assert.equal(h.modal._editorDraft.draft.candidate().value.fields['kpi-name'],'Draft');});

test('a changed objective revision makes the old draft review-only even when fields match',()=>{const h=harness('objective');h.ctx.revision=1;h.begin();h.name.value='Objective draft';h.capture();h.name.value='Original';h.ctx.revision=2;h.begin();assert.equal(h.nodes.restore.disabled,true);assert.equal(h.save(),false);assert.equal(h.modal._editorDraft.draft.candidate().value.fields['obj-name'],'Objective draft');});
