const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),core=fs.readFileSync(path.join(root,'auris-core.js'),'utf8'),editor=fs.readFileSync(path.join(root,'kpi-definition-editor.js'),'utf8'),upgrade=fs.readFileSync(path.join(root,'kpi-module-upgrade.js'),'utf8');
function harness(){
 const nodes={},calls=[],notices=[];let active=null;
 function node(id,value=''){return nodes[id]={id,value,style:{},dataset:{},disabled:false,children:[],setAttribute(k,v){this[k]=String(v);},getAttribute(k){return this[k]||null;},removeAttribute(k){delete this[k];},focus(){active=this;},prepend(n){this.children.unshift(n);},appendChild(n){this.children.push(n);},remove(){this.removed=true;},matches(s){return s.includes('h0139')&&id==='close';}};}
 for(const [id,value]of Object.entries({'kpi-name':'Safety','kpi-obj-sel':'o','kpi-code':'1.1','kpi-description':'Purpose','kpi-freq':'monthly','kpi-resp':'Person','kpi-data-provider':'Person','kpi-data-source':'Manual','kpi-reviewer':'Person','kpi-approver':'Person','kpi-status':'not_started','kpi-approval-status':'draft','kpi-modal-title':'','year-sel':'2026','save':'','close':''}))node(id,value);
 const list=node('kpi-indicators-list'),card=node('card'),modal=node('kpi-edit-modal');modal.style.display='flex';modal._kpiDefinitionContext={companyId:'c',actorId:'u',year:2026,kpiId:'k',revision:1,indicators:[]};
 const controls=Object.values(nodes).filter(n=>!['card','kpi-edit-modal','kpi-indicators-list'].includes(n.id));modal.querySelector=s=>s==='[data-kpi-definition-message]'?card.children.find(n=>!n.removed):card;modal.querySelectorAll=()=>controls;
 const original={id:'i',kpi_id:'k',company_id:'c',name:'Original',target_value:4,target_operator:'gte',unit:null,ytd_method:'sum',sort_order:0};
 function row(id,name){const n=node('row-'+list.children.length);n.setAttribute('data-indicator-id',id||'');const values={'.ind-name-input':name,'.ind-target-input':'4','.ind-op-input':'gte','.ind-unit-input':'','.ind-ytd-input':'sum'};n.querySelector=s=>s in values?{value:values[s]}:null;list.children.push(n);return n;}
 row('i','Renamed');modal._kpiDefinitionContext.indicators=[{...original}];
 const c={console:{error(){}},Date,document:{get activeElement(){return active;},getElementById:id=>nodes[id]||null,createElement:()=>node('message')},prof:{id:'u',company_id:'c'},isSA:()=>false,sephsCompanyContext:null,company:'c',kpiObjectiveCompany:()=>c.company,kpiObjectiveViewYear:()=>Number(nodes['year-sel'].value),isMgr:()=>c.allowed,allowed:true,KpiGovernedWorkflow:{canEdit:()=>c.editable},editable:true,kpiEditKpiId:'k',kpiObjectives:[{id:'o',company_id:'c',year:2026}],kpiKPIs:[{id:'k',company_id:'c',year:2026,status:'not_started',approval_status:'draft'}],kpiIndicators:[{...original}],kpiMonthlyData:{i:{8:{actual:4,ytd:4}}},toast:(...a)=>notices.push(a),toastActionError:(...a)=>notices.push(a),api:async(u,o)=>{calls.push({url:u,options:o});return c.response(u,o);},closeKpiModal:()=>{modal.style.display='none';},kpiLoadAll:async()=>{},kpiRenderOverview(){},kpiRenderMonthly(){},kpiUpdateMetrics(){},kpiRecalcAllYTD:async()=>{},stored:[{...original}],parent:{definition_revision:1,id:'k',company_id:'c',year:2026,status:'not_started',approval_status:'draft'},response:async(u,o)=>{
  if(u.startsWith('/kpi_monthly_data'))return u.includes('indicator_id=in.')?[{indicator_id:'i',company_id:'c',year:2026,month:8,actual:4,ytd:4}]:[];
  if(u==='/rpc/save_kpi_definition'){
   c.parent={...c.parent,...o.b.p_definition,definition_revision:c.parent.definition_revision+1};
   c.stored=o.b.p_indicators.map((i,index)=>({...i,id:i.id||'new-i',kpi_id:c.parent.id,company_id:'c',sort_order:index}));
   return {kpi:{...c.parent},indicators:c.stored.map(i=>({...i})),monthly:c.stored.some(i=>i.id==='i')?[{indicator_id:'i',company_id:'c',year:2026,month:8,actual:4,ytd:4}]:[]};
  }
  if(u.startsWith('/kpi_indicators')&&!o)return c.stored.map(n=>({...n}));
  throw new Error('Unexpected '+u);
 }};
 c.window=c;c.ccid=()=>c.company;vm.createContext(c);vm.runInContext(editor,c);
 return {c,nodes,list,modal,controls,calls,notices,original,row,writes:()=>calls.filter(x=>x.options),message:()=>card.children.find(n=>!n.removed)};
}
test('renaming an indicator updates its original ID and leaves its monthly history attached',async()=>{const h=harness();assert.equal((await h.c.kpiSaveKPI()).complete,true);assert.equal(h.writes().length,1);const row=h.writes()[0].options.b.p_indicators[0];assert.equal(row.id,'i');assert.equal(row.name,'Renamed');assert.equal(h.c.kpiMonthlyData.i[8].actual,4);});
test('same-name indicators are distinguished by ID rather than name',async()=>{const h=harness();h.c.stored.push({...h.original,id:'j'});h.c.kpiIndicators.push({...h.original,id:'j'});h.row('j','Original');assert.equal((await h.c.kpiSaveKPI()).complete,true);assert.deepEqual(Array.from(h.writes()[0].options.b.p_indicators,i=>i.id),['i','j']);});
test('retained IDs cannot point to another KPI',async()=>{const h=harness();h.list.children[0].setAttribute('data-indicator-id','foreign');await h.c.kpiSaveKPI();assert.equal(h.writes().length,0);assert.match(h.message().textContent,/indicator/i);});
test('duplicate row IDs are rejected before any write',async()=>{const h=harness();h.row('i','Duplicate');await h.c.kpiSaveKPI();assert.equal(h.writes().length,0);assert.match(h.message().textContent,/duplicate/i);});
test('removing an indicator with recorded data fails before the parent write',async()=>{const h=harness(),base=h.c.response;h.list.children=[];h.row('', 'New indicator');h.c.response=async(u,o)=>u.startsWith('/kpi_monthly_data')?[{id:'record'}]:base(u,o);await h.c.kpiSaveKPI();assert.equal(h.writes().length,0);assert.match(h.message().textContent,/monthly.*restore|restore.*monthly/i);assert.equal(h.modal.style.display,'flex');});
test('history lookup failure cannot be treated as no history',async()=>{const h=harness(),base=h.c.response;h.list.children=[];h.row('', 'New');h.c.response=async(u,o)=>u.startsWith('/kpi_monthly_data')?null:base(u,o);await h.c.kpiSaveKPI();assert.equal(h.writes().length,0);assert.ok(h.message());});
test('blank names on retained indicators are validation errors, not silent deletion',async()=>{const h=harness();h.list.children=[];h.row('i','');await h.c.kpiSaveKPI();assert.equal(h.calls.length,0);assert.ok(h.message());});
test('preflight and write endpoints are scoped to company and parent KPI',async()=>{const h=harness();await h.c.kpiSaveKPI();for(const call of h.calls.filter(x=>x.url.startsWith('/kpi_indicators'))){assert.match(call.url,/company_id=eq.c/);assert.match(call.url,/kpi_id=eq.k/);}const write=h.writes()[0];assert.equal(write.url,'/rpc/save_kpi_definition');assert.equal(write.options.b.p_company_id,'c');assert.equal(write.options.b.p_kpi_id,'k');assert.equal(write.options.b.p_expected_revision,1);assert.equal('created_by' in write.options.b.p_definition,false);});
for(const [label,change]of [['company',c=>c.company='other'],['account',c=>c.prof.id='other'],['year',c=>c.document.getElementById('year-sel').value='2027'],['permission',c=>c.allowed=false],['workflow',c=>c.editable=false]])test(label+' change blocks save',async()=>{const h=harness();change(h.c);await h.c.kpiSaveKPI();assert.equal(h.writes().length,0);assert.ok(h.message());});
test('duplicate saves and closing are blocked while history is checked',async()=>{const h=harness(),base=h.c.response;let release;h.c.response=(u,o)=>u.startsWith('/kpi_indicators')&&!o?new Promise(r=>release=()=>r(h.c.stored)):base(u,o);const first=h.c.kpiSaveKPI();await Promise.resolve();await h.c.kpiSaveKPI();assert.equal(h.modal._kpiDefinitionBusy,true);assert.equal(h.controls.every(n=>n.disabled),true);h.c.response=base;release();await first;assert.equal(h.writes().filter(x=>x.url==='/rpc/save_kpi_definition').length,1);});
test('a lost transaction response retains a disabled form and never repeats the write',async()=>{const h=harness(),base=h.c.response;h.c.response=async(u,o)=>{const result=await base(u,o);if(o)throw new Error('Response connection lost');return result;};await h.c.kpiSaveKPI();await h.c.kpiSaveKPI();assert.equal(h.writes().length,1);assert.equal(h.nodes.save.disabled,true);assert.equal(h.nodes.close.disabled,false);assert.match(h.message().textContent,/not be confirmed/i);assert.equal(h.c.stored[0].name,'Renamed');assert.equal(h.c.kpiIndicators[0].name,'Original');assert.equal(h.notices.length,0);});
test('empty update representation is never treated as success',async()=>{const h=harness(),base=h.c.response;h.c.response=async(u,o)=>o?[]:base(u,o);await h.c.kpiSaveKPI();assert.equal(h.notices.length,0);assert.equal(h.nodes.save.disabled,true);assert.ok(h.message());});
test('changed company after a write stops subsequent indicator requests',async()=>{const h=harness(),base=h.c.response;h.c.response=async(u,o)=>{const response=await base(u,o);if(o&&u==='/rpc/save_kpi_definition')h.c.company='other';return response;};await h.c.kpiSaveKPI();assert.equal(h.writes().length,1);assert.equal(h.c.kpiIndicators[0].name,'Original');assert.equal(h.notices.length,0);});
test('row builder stores identity and assigns names as values, not markup',()=>{const created=[],c={document:{getElementById:()=>({children:[],appendChild:n=>created.push(n)}),createElement:()=>({style:{},attributes:{},setAttribute(k,v){this.attributes[k]=v;},querySelector:()=>({})})}};vm.createContext(c);vm.runInContext(editor.slice(editor.indexOf('function kpiAddIndicatorRow('),editor.indexOf('function openKpiAddModal(')),c);c.kpiAddIndicatorRow('A "quoted" <name>',4,'gte','','sum','i');assert.equal(created[0].attributes['data-indicator-id'],'i');assert.ok(!created[0].innerHTML.includes('A "quoted" <name>'));});
test('drafts capture stable indicator IDs',()=>{assert.match(fs.readFileSync(path.join(root,'kpi-editor-drafts.js'),'utf8'),/indicatorId:row\.getAttribute\('data-indicator-id'\)/);});
test('historical removal offers restoration without throwing away other draft rows',async()=>{const h=harness(),base=h.c.response;h.list.children=[];h.row('','New draft row');h.c.response=async(u,o)=>u.startsWith('/kpi_monthly_data')?[{id:'history'}]:base(u,o);h.c.kpiAddIndicatorRow=(name,target,op,unit,ytd,id)=>h.row(id,name);await h.c.kpiSaveKPI();const alert=h.message();assert.equal(alert.children[0].textContent,'Restore indicator');alert.children[0].onclick();assert.equal(h.list.children.length,2);assert.equal(h.list.children[0].querySelector('.ind-name-input').value,'New draft row');assert.equal(h.list.children[1].getAttribute('data-indicator-id'),'i');assert.equal(h.writes().length,0);});
test('saving during people refresh leaves the draft editable and makes no request',async()=>{const h=harness();h.nodes['kpi-resp'].setAttribute('aria-busy','true');await h.c.kpiSaveKPI();assert.equal(h.calls.length,0);assert.equal(h.nodes.save.disabled,false);assert.match(h.message().textContent,/people list.*loading/i);});
test('a new indicator is created without changing existing IDs',async()=>{const h=harness();h.row('','New measure');assert.equal((await h.c.kpiSaveKPI()).complete,true);assert.deepEqual(Array.from(h.c.stored,i=>i.id),['i','new-i']);assert.equal(h.c.kpiMonthlyData.i[8].actual,4);});
test('a new KPI captures creator and receives its indicator without an existing ID',async()=>{const h=harness(),base=h.c.response;h.c.kpiEditKpiId=null;h.modal._kpiDefinitionContext.kpiId=null;h.c.stored=[];h.list.children=[];h.row('','New measure');h.c.response=async(u,o)=>u.startsWith('/kpi_monthly_data')?[]:base(u,o);assert.equal((await h.c.kpiSaveKPI()).complete,true);assert.equal(h.writes()[0].options.m,'POST');assert.equal(h.writes()[0].options.b.p_definition.created_by,'u');assert.equal(h.c.stored[0].kpi_id,'k');});
test('unused removed indicators are deleted only by exact scoped ID',async()=>{const h=harness();h.c.stored.push({...h.original,id:'unused',name:'Unused'});h.c.kpiIndicators.push({...h.original,id:'unused',name:'Unused'});assert.equal((await h.c.kpiSaveKPI()).complete,true);assert.equal(h.writes().length,1);assert.deepEqual(Array.from(h.c.stored,i=>i.id),['i']);assert.equal(h.c.kpiMonthlyData.i[8].actual,4);});
test('an incomplete transaction response leaves the original caches intact',async()=>{const h=harness(),base=h.c.response;h.c.response=async(u,o)=>{const response=await base(u,o);if(o)response.indicators=[];return response;};assert.equal((await h.c.kpiSaveKPI()).complete,false);assert.equal(h.c.kpiIndicators[0].name,'Original');assert.equal(h.nodes.save.disabled,true);assert.equal(h.notices.length,0);});
test('foreign monthly rows cannot be published into the local history cache',async()=>{const h=harness(),base=h.c.response;h.c.response=async(u,o)=>{const response=await base(u,o);if(o)response.monthly=[{indicator_id:'i',company_id:'foreign',year:2026,month:8,actual:99}];return response;};assert.equal((await h.c.kpiSaveKPI()).complete,false);assert.equal(h.c.kpiMonthlyData.i[8].actual,4);});
test('null targets do not validate as numeric zero',()=>{const h=harness();assert.equal(h.c.kpiDefinitionRowsMatch([{id:'i',target_value:null}],{target_value:0}),false);assert.equal(h.c.kpiDefinitionRowsMatch([{id:'i',target_value:0}],{target_value:null}),false);});
test('advanced target operators retain their original selected values when editing',()=>{const source=editor.slice(editor.indexOf('function kpiAddIndicatorRow('),editor.indexOf('function openKpiAddModal('));for(const op of ['zero','trend_up','trend_down'])assert.ok(source.includes('operator==="'+op+'"?"selected"'));});
test('pending editor close uses the core busy guard',()=>{const h=harness();h.modal._kpiDefinitionBusy=true;vm.runInContext(core.slice(core.indexOf('function closeKpiModal('),core.indexOf('function openKpiModal(')),h.c);assert.equal(h.c.closeKpiModal('kpi-edit-modal'),false);assert.equal(h.modal.style.display,'flex');});
test('draft recovery delegates to the shared lifecycle adapter',()=>{assert.match(upgrade,/function kpiXRestoreEditorDraft\(kpiId\)\{if\(window\.KpiEditorDrafts\)KpiEditorDrafts\.begin/);});

test('stale edits show a conflict without publishing or repeating the transaction',async()=>{const h=harness(),base=h.c.response;h.c.response=(u,o)=>o?Promise.reject(new Error('AURIS_KPI_EDIT_CONFLICT')):base(u,o);await h.c.kpiSaveKPI();assert.match(h.message().textContent,/changed after you opened.*No changes/);assert.equal(h.c.kpiIndicators[0].name,'Original');await h.c.kpiSaveKPI();assert.equal(h.writes().length,1);});
test('missing revision blocks an outdated editor before any network write',async()=>{const h=harness();delete h.modal._kpiDefinitionContext.revision;await h.c.kpiSaveKPI();assert.equal(h.calls.length,0);assert.match(h.message().textContent,/latest saved revision/);});
test('save uses the captured revision and indicator baseline despite refreshed caches',async()=>{const h=harness();h.c.kpiKPIs[0].definition_revision=99;h.c.kpiIndicators[0].name='Someone else';await h.c.kpiSaveKPI();assert.equal(h.writes()[0].options.b.p_expected_revision,1);assert.equal(h.writes()[0].options.b.p_expected_indicators[0].name,'Original');});
test('response with unchanged revision cannot confirm a save',async()=>{const h=harness(),base=h.c.response;h.c.response=async(u,o)=>{const result=await base(u,o);if(o)result.kpi.definition_revision=1;return result;};assert.equal((await h.c.kpiSaveKPI()).complete,false);assert.equal(h.notices.length,0);});
