const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),core=fs.readFileSync(path.join(root,'auris-core.js'),'utf8'),editor=fs.readFileSync(path.join(root,'kpi-definition-editor.js'),'utf8');
function deferred(){let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};}
function harness(edit=false){
 const nodes={},calls=[],notices=[];let active=null;
 function node(id,value=''){return nodes[id]={id,value,style:{},dataset:{},disabled:false,isConnected:true,children:[],listeners:{},tabIndex:0,setAttribute(k,v){this[k]=v;},getAttribute(k){return this[k];},removeAttribute(k){delete this[k];},focus(){active=this;},getClientRects(){return [{}];},addEventListener(k,fn){this.listeners[k]=fn;},prepend(el){this.children.unshift(el);},remove(){this.removed=true;},matches(s){return s.includes('h0129')&&id==='close';},parentElement:{querySelector(){return {setAttribute(){}};}}};}
 for(const [id,value]of Object.entries({'obj-name':'','obj-year':'2026','obj-code':'','obj-modal-title':'','obj-delete-btn':'','save':'','close':'','year-sel':'2026','launcher':''}))node(id,value);
 const controls=[nodes['obj-name'],nodes['obj-year'],nodes['obj-code'],nodes['obj-delete-btn'],nodes.save,nodes.close];
 const card=node('card'),modal=node('obj-modal');modal.style.display='none';modal.querySelector=s=>s==='[data-kpi-objective-message]'?card.children.find(n=>!n.removed):s.includes('h0129')?nodes.close:card;modal.querySelectorAll=()=>controls;modal.contains=el=>controls.includes(el)||el===nodes['obj-modal-title']||card.children.includes(el);
 const obj={id:'o',company_id:'company-a',year:2026,name:'Original',code:'1',color:'#1D9E75'};
 const c={console:{error(){}},Date,document:{get activeElement(){return active;},getElementById:id=>nodes[id]||null,createElement:()=>node('alert'),querySelectorAll:()=>[]},prof:{id:'user-a',company_id:'company-a'},sephsCompanyContext:'company-a',isSA:()=>true,ccid:()=>c.company,company:'company-a',kpiCanEdit:()=>c.allowed,allowed:true,kpiSelectedColor:'#1D9E75',kpiObjectives:[obj],kpiKPIs:[{id:'k'}],kpiIndicators:[{id:'i'}],kpiMonthlyData:{i:{8:{actual:4}}},toast:(...args)=>notices.push(args),actionErrorMessage:(_a,_m,msg)=>msg,api:async(url,options)=>{calls.push({url,options});return c.response(url,options);},kpiRenderOverview(){c.renders++;},kpiRenderMonthly(){},kpiUpdateMetrics(){},renders:0,kpiLoadAll:async()=>{},stored:null,response:async(url,options)=>{if(options){c.stored={id:edit?'o':'new',...options.b};return [c.stored];}if(url.includes('select=code'))return [{code:'1'},{code:'3'}];return c.stored?[c.stored]:[obj];}};
 c.window=c;vm.createContext(c);vm.runInContext(editor,c);
 vm.runInContext(core.slice(core.indexOf('function closeKpiModal('),core.indexOf('async function kpiDeleteObjective')),c);
 nodes.launcher.focus();c.openObjModal(edit?'o':null);nodes['obj-name'].value='Safer work';nodes['obj-year'].value='2026';
 return {c,nodes,modal,controls,obj,calls,notices,card,message:()=>card.children.find(n=>!n.removed),writes:()=>calls.filter(x=>x.options)};
}
test('objective validation is focused inside the retained form',async()=>{const h=harness();h.nodes['obj-name'].value='';await h.c.kpiSaveObjective();assert.equal(h.calls.length,0);assert.equal(h.message().role,'alert');assert.equal(h.c.document.activeElement,h.message());assert.equal(h.notices.length,0);});
test('objective year must be a whole valid reporting year',async()=>{const h=harness();h.nodes['obj-year'].value='2026oops';await h.c.kpiSaveObjective();assert.equal(h.calls.length,0);assert.match(h.message().textContent,/year/i);});
for(const [name,change]of [['company',c=>c.company='company-b'],['account',c=>c.prof={id:'user-b',company_id:'company-a'}],['reporting year',c=>c.document.getElementById('year-sel').value='2027'],['permission',c=>c.allowed=false]]){
 test(name+' change before save prevents requests',async()=>{const h=harness();change(h.c);await h.c.kpiSaveObjective();assert.equal(h.calls.length,0);assert.ok(h.message());});
 test(name+' change during code lookup prevents the POST',async()=>{const h=harness(),gate=deferred(),base=h.c.response;h.c.response=async(u,o)=>!o&&u.includes('select=code')?gate.promise:base(u,o);const work=h.c.kpiSaveObjective();change(h.c);gate.resolve([]);await work;assert.equal(h.writes().length,0);assert.ok(h.message());});
}
test('code lookup is company/year scoped and creation preserves field payload',async()=>{const h=harness();const result=await h.c.kpiSaveObjective();assert.equal(result.complete,true);assert.match(h.calls[0].url,/company_id=eq.company-a/);const write=h.writes()[0];assert.equal(write.options.p,'return=representation');assert.equal(write.options.b.company_id,'company-a');assert.equal(write.options.b.created_by,'user-a');assert.equal(write.options.b.code,'4');assert.equal(write.options.b.name,'Safer work');assert.equal(write.options.b.color,'#1D9E75');assert.equal(h.modal.style.display,'none');});
test('editing scopes PATCH and does not overwrite created_by',async()=>{const h=harness(true);await h.c.kpiSaveObjective();const write=h.writes()[0];assert.match(write.url,/id=eq.o/);assert.match(write.url,/company_id=eq.company-a/);assert.equal(write.options.m,'PATCH');assert.equal('created_by'in write.options.b,false);});
test('duplicate save and close/replacement are blocked during lookup',async()=>{const h=harness(),gate=deferred(),base=h.c.response;h.c.response=async(u,o)=>!o&&u.includes('select=code')?gate.promise:base(u,o);const first=h.c.kpiSaveObjective(),second=h.c.kpiSaveObjective();let snapshots;try{snapshots={calls:h.calls.length,disabled:h.controls.every(x=>x.disabled),closed:h.c.closeKpiModal('obj-modal'),opened:h.c.openObjModal('o'),name:h.nodes['obj-name'].value,active:h.c.document.activeElement.id};}finally{gate.resolve([]);await Promise.all([first,second]);}assert.equal(snapshots.calls,1);assert.equal(snapshots.disabled,true);assert.equal(snapshots.closed,false);assert.equal(snapshots.opened,false);assert.equal(snapshots.name,'Safer work');assert.equal(snapshots.active,'obj-modal-title');assert.equal(h.writes().length,1);});
test('opening another objective cannot discard an existing visible draft',()=>{const h=harness();assert.equal(h.c.openObjModal('o'),false);assert.equal(h.nodes['obj-name'].value,'Safer work');assert.equal(h.c.kpiEditObjId,null);});
test('lookup failure retains input and exposes safe text-only feedback',async()=>{const h=harness();h.c.response=async()=>{throw new Error('<img onerror=alert(1)>');};await h.c.kpiSaveObjective();assert.equal(h.modal.style.display,'flex');assert.equal(h.nodes['obj-name'].value,'Safer work');assert.equal(h.nodes.save.disabled,false);assert.match(h.message().textContent,/<img/);assert.equal(h.message().innerHTML,undefined);assert.equal(h.notices.length,0);});
test('unconfirmed write failure advises checking existing records before retry',async()=>{const h=harness(),base=h.c.response;h.c.response=async(u,o)=>o?Promise.reject(new Error('Network unavailable')):base(u,o);await h.c.kpiSaveObjective();assert.match(h.message().textContent,/could not be confirmed/i);assert.match(h.message().textContent,/before retry/i);assert.equal(h.nodes['obj-name'].value,'Safer work');});
test('missing returned identity cannot be reported as success or automatically repeated',async()=>{const h=harness(),base=h.c.response;h.c.response=async(u,o)=>o?[]:base(u,o);await h.c.kpiSaveObjective();await h.c.kpiSaveObjective();assert.equal(h.writes().length,1);assert.equal(h.nodes.save.disabled,true);assert.equal(h.nodes.close.disabled,false);assert.equal(h.notices.length,0);});
test('confirmed save with refresh failure is retained and not duplicated',async()=>{const h=harness(),base=h.c.response;h.c.response=async(u,o)=>!o&&!u.includes('select=code')?Promise.reject(new Error('Refresh unavailable')):base(u,o);const result=await h.c.kpiSaveObjective();await h.c.kpiSaveObjective();assert.equal(result.saved,true);assert.equal(result.complete,false);assert.equal(h.writes().length,1);assert.equal(h.nodes.save.disabled,true);assert.equal(h.nodes.close.disabled,false);assert.equal(h.modal.style.display,'flex');assert.equal(h.nodes['obj-name'].value,'Safer work');assert.match(h.message().textContent,/saved/i);assert.equal(h.notices.length,0);});
test('late saved response after company switch cannot publish into the new company cache',async()=>{const h=harness(),gate=deferred(),entered=deferred(),base=h.c.response;h.c.response=async(u,o)=>{if(o){entered.resolve();return gate.promise;}return base(u,o);};const work=h.c.kpiSaveObjective();await entered.promise;h.c.company='company-b';h.c.kpiObjectives=[{id:'company-b-record'}];gate.resolve([{id:'saved',company_id:'company-a',year:2026,name:'Safer work',code:'4',color:'#1D9E75'}]);await work;assert.equal(h.calls.length,2);assert.equal(h.c.kpiObjectives[0].id,'company-b-record');assert.equal(h.c.renders,0);assert.equal(h.nodes.save.disabled,true);});
test('refresh verifies the saved fields and identity before success',async()=>{const h=harness(),base=h.c.response;h.c.response=async(u,o)=>!o&&!u.includes('select=code')?[{id:'different',company_id:'company-a'}]:base(u,o);const result=await h.c.kpiSaveObjective();assert.equal(result.complete,false);assert.equal(h.notices.length,0);assert.equal(h.c.kpiObjectives[0],h.obj);});
test('objective refresh never erases unrelated KPI/indicator/monthly caches',async()=>{const h=harness();await h.c.kpiSaveObjective();assert.equal(h.c.kpiKPIs[0].id,'k');assert.equal(h.c.kpiIndicators[0].id,'i');assert.equal(h.c.kpiMonthlyData.i[8].actual,4);assert.equal(h.c.kpiObjectives[0].name,'Safer work');assert.ok(h.c.renders>0);});
test('render failure after persistence keeps a saved outcome and disabled Save',async()=>{const h=harness();h.c.kpiRenderOverview=()=>{throw new Error('Display unavailable');};const result=await h.c.kpiSaveObjective();assert.equal(result.saved,true);assert.equal(result.complete,false);assert.equal(h.nodes.save.disabled,true);assert.equal(h.notices.length,0);});
test('close restores available launcher and fresh reopening releases partial-save controls',async()=>{const h=harness(),base=h.c.response;h.c.response=async(u,o)=>!o&&!u.includes('select=code')?Promise.reject(new Error('Refresh unavailable')):base(u,o);await h.c.kpiSaveObjective();h.c.closeKpiModal('obj-modal');assert.equal(h.c.document.activeElement,h.nodes.launcher);h.c.openObjModal(null);assert.equal(h.nodes.save.disabled,false);assert.equal(h.nodes['obj-name'].value,'');});
test('editing a foreign or removed objective is rejected before requests',async()=>{const h=harness(true);h.obj.company_id='company-b';await h.c.kpiSaveObjective();assert.equal(h.calls.length,0);assert.ok(h.message());});
test('hidden stale form cannot save or look up a code',async()=>{const h=harness();h.c.closeKpiModal('obj-modal');await h.c.kpiSaveObjective();assert.equal(h.calls.length,0);});
test('late objective-list response never replaces a changed company cache',async()=>{const h=harness(),base=h.c.response;h.c.response=async(u,o)=>{const result=await base(u,o);if(u.includes('order=sort_order')){h.c.company='company-b';h.c.kpiObjectives=[{id:'new-company'}];}return result;};const result=await h.c.kpiSaveObjective();assert.equal(result.saved,true);assert.equal(result.complete,false);assert.equal(h.c.kpiObjectives[0].id,'new-company');assert.equal(h.c.renders,0);});
test('saving for a different objective year preserves the selected scorecard year',async()=>{const h=harness(),base=h.c.response;h.nodes['obj-year'].value='2027';h.c.response=async(u,o)=>u.includes('order=sort_order')?[h.obj]:base(u,o);const result=await h.c.kpiSaveObjective();assert.equal(result.complete,true);assert.equal(h.writes()[0].options.b.year,2027);assert.equal(h.nodes['year-sel'].value,'2026');assert.equal(h.c.kpiObjectives[0],h.obj);assert.match(h.notices[0][0],/2027/);});
test('new-objective launcher cannot change the year of a retained form',()=>{const h=harness();h.nodes['obj-year'].value='2025';h.c.isMgr=()=>true;h.c.kpiXSelectedYear=()=>2026;const module=fs.readFileSync(path.join(root,'kpi-module-upgrade.js'),'utf8');vm.runInContext(module.slice(module.indexOf('function kpiXOpenNewObjective()'),module.indexOf('function kpiXOpenNewKpi()')),h.c);h.c.kpiXOpenNewObjective();assert.equal(h.nodes['obj-year'].value,'2025');assert.equal(h.nodes['obj-name'].value,'Safer work');});
test('an edited objective moved to another year is not mistaken for a missing save',async()=>{const h=harness(true),base=h.c.response;h.nodes['obj-year'].value='2027';h.c.response=async(u,o)=>u.includes('order=sort_order')?[]:base(u,o);const result=await h.c.kpiSaveObjective();assert.equal(result.saved,true);assert.equal(result.complete,true);assert.equal(h.c.kpiObjectives.length,0);assert.equal(h.modal.style.display,'none');assert.match(h.notices[0][0],/updated.*2027/);});
