const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),core=fs.readFileSync(path.join(root,'auris-core.js'),'utf8');
function deferred(){let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};}
function harness(){
 const nodes={},calls=[],notices=[],confirmations=[];let active=null;
 const field=(id,value='')=>nodes[id]={id,value,style:{},dataset:{},disabled:false,isConnected:true,children:[],setAttribute(k,v){this[k]=v;},focus(){active=this;},prepend(el){this.children.unshift(el);},remove(){this.removed=true;},addEventListener(){},getClientRects(){return [{}];},matches(selector){return selector.includes('h0143')&&id==='cancel';}};
 for(const id of ['entry-actual','entry-ytd','entry-comment','entry-root-cause','entry-evidence','entry-modal-title','entry-kpi-name','entry-kpi-target','entry-month-label','kpi-clear-btn','save','cancel'])field(id);
 field('year-sel','2025');const panel=field('panel'),modal=field('kpi-entry-modal');modal.style.display='none';modal.querySelector=()=>panel.children.find(x=>!x.removed);modal.querySelectorAll=()=>controls;modal.contains=el=>controls.includes(el)||panel.children.includes(el);
 const controls=Object.values(nodes).filter(el=>!['panel','kpi-entry-modal','year-sel'].includes(el.id));
 modal.querySelector=selector=>selector==='[data-kpi-entry-message]'?panel.children.find(x=>!x.removed):panel;
 const kpi={id:'k',name:'Toolbox talks',company_id:'a',approval_status:'locked'},ind={id:'i',kpi_id:'k',name:'Talk count',ytd_method:'sum'};
 const row={id:'m8',indicator_id:'i',company_id:'a',year:2025,month:8,actual:4,ytd:4,comment:'Recorded evidence'};
 const c={console,Date,document:{readyState:'loading',getElementById:id=>nodes[id],get activeElement(){return active;},createElement:()=>field('alert'),querySelectorAll:()=>[],addEventListener(){}},prof:{id:'user-a'},company:'a',allowed:true,workflowAllowed:true,ccid:()=>c.company,kpiCanEdit:()=>c.allowed,KpiGovernedWorkflow:{canEnterMonthly:()=>c.workflowAllowed},kpiKPIs:[kpi],kpiIndicators:[ind],kpiObjectives:[{id:'o',name:'Safety'}],kpiMonthlyData:{i:{8:row},other:{1:{actual:9}}},kpiEntryIndicatorId:null,kpiEntryMonth:0,kpiEntryYear:2025,KPI_MONTHS:['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],kpiFmtTarget:()=>4,stored:[row],renderCount:0,kpiRenderOverview(){c.renderCount++;},kpiRenderMonthly(){},kpiUpdateMetrics(){},toast:(...args)=>notices.push(args),toastActionError:(...args)=>notices.push(args),confirm:async()=>true,appConfirmAction:async opts=>{confirmations.push(opts);return c.confirm();},api:async(url,options)=>{calls.push({url,options});return c.response(url,options);},response:async(url,options)=>{if(options?.m==='DELETE'){c.stored=c.stored.filter(r=>r.month!==8);return null;}if(options?.m==='PATCH')return null;if(url.startsWith('/objectives'))return [{id:'o',name:'Safety'}];if(url.startsWith('/kpis_v2'))return [kpi];if(url.startsWith('/kpi_indicators'))return [ind];if(url.startsWith('/kpi_monthly_data'))return c.stored;throw new Error('Unexpected request');}};
 c.window=c;vm.createContext(c);
 vm.runInContext(core.slice(core.indexOf('function closeKpiModal(id)'),core.indexOf('async function kpiDeleteObjective')),c);
 vm.runInContext(core.slice(core.indexOf('function kpiCalcYTD(indicatorId'),core.indexOf('// -- SOP MODULE HELPERS')),c);
 vm.runInContext(core.slice(core.indexOf('async function kpiLoadAll('),core.indexOf('function kpiUpdateMetrics()')),c);
 c.kpiOpenEntry('i','k',8);nodes['entry-comment'].value='Unsaved explanation';nodes['entry-root-cause'].value='Retain root';nodes['entry-evidence'].value='Retain evidence';nodes['kpi-clear-btn'].focus();
 return {c,nodes,modal,panel,controls,calls,notices,confirmations,kpi,ind,row,message:()=>panel.children.find(x=>!x.removed),deletes:()=>calls.filter(x=>x.options?.m==='DELETE')};
}
test('clear requires manager permission before requesting confirmation',async()=>{const h=harness();h.c.allowed=false;await h.c.kpiClearEntry();assert.equal(h.confirmations.length,0);assert.equal(h.deletes().length,0);assert.match(h.message().textContent,/manager/i);});
test('cancel preserves data, separated fields and returns focus to Clear',async()=>{const h=harness();h.c.confirm=async()=>false;const result=await h.c.kpiClearEntry();assert.equal(result.cancelled,true);assert.equal(h.deletes().length,0);assert.equal(h.c.kpiMonthlyData.i[8],h.row);assert.equal(h.nodes['entry-comment'].value,'Unsaved explanation');assert.equal(h.c.document.activeElement,h.nodes['kpi-clear-btn']);assert.equal(h.nodes.save.disabled,false);});
test('confirmation names the captured KPI, indicator, month and irreversible effect',async()=>{const h=harness();h.c.confirm=async()=>false;await h.c.kpiClearEntry();const text=JSON.stringify(h.confirmations[0]);for(const value of ['Aug','2025','Toolbox talks','Talk count','cannot be undone'])assert.ok(text.includes(value),value);});
for(const [name,change]of [['company',c=>c.company='b'],['account',c=>c.prof={id:'other'}],['month',c=>c.kpiEntryMonth=7],['year',c=>c.document.getElementById('year-sel').value='2026'],['permission',c=>c.allowed=false],['workflow',c=>c.workflowAllowed=false]]){
 test(name+' changing during confirmation prevents deletion',async()=>{const h=harness();h.c.confirm=async()=>{change(h.c);return true;};await h.c.kpiClearEntry();assert.equal(h.deletes().length,0);assert.ok(h.message());});
}
test('only one confirmation may run and other entry actions remain blocked',async()=>{const h=harness(),gate=deferred();h.c.confirm=()=>gate.promise;const work=h.c.kpiClearEntry(),duplicate=h.c.kpiClearEntry();try{assert.equal(h.confirmations.length,1);assert.equal(h.c.kpiOpenEntry('i','k',7),false);const save=await h.c.kpiSaveEntry();assert.equal(save.complete,false);assert.equal(h.calls.length,0);}finally{gate.resolve(false);await Promise.all([work,duplicate]);}});
test('pending delete disables controls, retains title focus and rejects another delete',async()=>{const h=harness(),gate=deferred(),entered=deferred(),base=h.c.response;h.c.response=async(u,o)=>{if(o?.m==='DELETE'){entered.resolve();await gate.promise;}return base(u,o);};const work=h.c.kpiClearEntry();let duplicate;try{await entered.promise;assert.ok(h.controls.every(x=>x.disabled));assert.equal(h.c.document.activeElement,h.nodes['entry-modal-title']);duplicate=h.c.kpiClearEntry();}finally{gate.resolve();await Promise.all([work,duplicate]);}assert.equal(h.deletes().length,1);});
test('deletion is explicitly scoped to captured company, indicator, year and month',async()=>{const h=harness();const result=await h.c.kpiClearEntry();const url=h.deletes()[0].url;for(const part of ['company_id=eq.a','indicator_id=eq.i','year=eq.2025','month=eq.8'])assert.ok(url.includes(part),part);assert.equal(result.cleared,true);assert.equal(result.complete,true);assert.equal(h.modal.style.display,'none');});
test('failed deletion keeps values with focused in-form feedback and no success toast',async()=>{const h=harness();h.c.response=async()=>{throw new Error('Network unavailable');};const result=await h.c.kpiClearEntry();assert.equal(result.cleared,false);assert.equal(h.c.kpiMonthlyData.i[8],h.row);assert.equal(h.nodes['entry-comment'].value,'Unsaved explanation');assert.equal(h.nodes.save.disabled,false);assert.equal(h.modal.style.display,'flex');assert.equal(h.message().role,'alert');assert.equal(h.c.document.activeElement,h.message());assert.equal(h.notices.length,0);});
test('confirmed clear with failed YTD work is latched and cannot be resaved or recleared',async()=>{const h=harness(),base=h.c.response;h.c.response=async(u,o)=>{if(!o&&u.includes('order=month'))throw new Error('YTD unavailable');return base(u,o);};const result=await h.c.kpiClearEntry();assert.equal(result.cleared,true);assert.equal(result.complete,false);assert.equal(h.modal._kpiEntryCleared,true);assert.equal(h.nodes.save.disabled,true);assert.equal(h.nodes.cancel.disabled,false);assert.match(h.message().textContent,/cleared.*summary|refresh/i);await h.c.kpiSaveEntry();await h.c.kpiClearEntry();assert.equal(h.deletes().length,1);assert.equal(h.confirmations.length,1);});
test('reload failure does not erase unrelated caches or misreport the clear',async()=>{const h=harness(),base=h.c.response;h.c.response=async(u,o)=>{if(u.startsWith('/objectives'))throw new Error('Reload unavailable');return base(u,o);};await h.c.kpiClearEntry();assert.equal(h.c.kpiMonthlyData.i[8],undefined);assert.equal(h.c.kpiMonthlyData.other[1].actual,9);assert.equal(h.c.kpiKPIs[0],h.kpi);assert.equal(h.modal.style.display,'flex');assert.equal(h.notices.length,0);});
test('late clear response does not change the new company cache or run follow-up requests',async()=>{const h=harness(),base=h.c.response;h.c.response=async(u,o)=>{const result=await base(u,o);if(o?.m==='DELETE'){h.c.company='b';h.c.kpiMonthlyData={newCompany:true};}return result;};await h.c.kpiClearEntry();assert.equal(h.calls.length,1);assert.equal(h.c.kpiMonthlyData.newCompany,true);assert.equal(h.c.renderCount,0);assert.match(h.message().textContent,/cleared/i);});
test('reload must verify that the cleared month is absent before reporting success',async()=>{const h=harness(),base=h.c.response;h.c.response=async(u,o)=>u.includes('/kpi_monthly_data?select')?[h.row]:base(u,o);const result=await h.c.kpiClearEntry();assert.equal(result.complete,false);assert.equal(h.modal.style.display,'flex');assert.match(h.message().textContent,/still.*present|still.*visible/i);assert.equal(h.notices.length,0);});
test('clearing recalculates remaining YTD using the existing arithmetic',async()=>{const h=harness();h.c.stored.push({...h.row,id:'m9',month:9,actual:6,ytd:10});await h.c.kpiClearEntry();const patch=h.calls.find(x=>x.options?.m==='PATCH');assert.match(patch.url,/month=eq.9/);assert.match(patch.url,/company_id=eq.a/);assert.equal(patch.options.b.ytd,6);});
test('partial clear permits a fresh entry only after explicit close and reopen',async()=>{const h=harness(),base=h.c.response;h.c.response=async(u,o)=>u.startsWith('/objectives')?Promise.reject(new Error('Reload unavailable')):base(u,o);await h.c.kpiClearEntry();assert.equal(h.c.kpiOpenEntry('i','k',8),false);h.c.closeKpiModal('kpi-entry-modal');h.c.kpiOpenEntry('i','k',8);assert.equal(h.modal._kpiEntryCleared,false);assert.equal(h.nodes['entry-actual'].value,'');assert.equal(h.nodes['kpi-clear-btn'].style.display,'none');});
test('no stored monthly record means no confirmation or deletion',async()=>{const h=harness();delete h.c.kpiMonthlyData.i[8];await h.c.kpiClearEntry();assert.equal(h.confirmations.length,0);assert.equal(h.deletes().length,0);assert.match(h.message().textContent,/no.*stored|no.*saved/i);});
test('a closed form cannot clear its stale entry context',async()=>{const h=harness();h.c.closeKpiModal('kpi-entry-modal');await h.c.kpiClearEntry();assert.equal(h.confirmations.length,0);assert.equal(h.deletes().length,0);});
test('a partial save cannot immediately be cleared as another operation',async()=>{const h=harness();h.modal._kpiEntrySaved=true;await h.c.kpiClearEntry();assert.equal(h.deletes().length,0);assert.equal(h.confirmations.length,0);});
test('error details are rendered as text, never executable HTML',async()=>{const h=harness();h.c.response=async()=>{throw new Error('<img onerror=alert(1)>');};await h.c.kpiClearEntry();assert.match(h.message().textContent,/<img/);assert.equal(h.message().innerHTML,undefined);});
