const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..');
function deferred(){let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};}
function harness(){
  const nodes={},calls=[],links=[],toasts=[],timers=[];
  function element(){return {value:'',style:{},dataset:{},disabled:false,children:[],listeners:{},attributes:{},setAttribute(k,v){this.attributes[k]=v;},getAttribute(k){return this.attributes[k];},removeAttribute(k){delete this.attributes[k];},addEventListener(k,fn){this.listeners[k]=fn;},focus(){document.activeElement=this;this.focused=true;},prepend(el){this.children.unshift(el);},remove(){this.removed=true;delete nodes[this.id];},querySelector(selector){if(selector==='.kpi-x-drawer-body')return this.body;if(selector==='[data-kpi-action-message]')return this.body&&this.body.children.find(el=>el.attributes['data-kpi-action-message']);if(selector==='[data-kpi-action-save]')return this.save;if(selector[0]==='#')return this.fields&&this.fields[selector.slice(1)];return null;},querySelectorAll(){return this.controls||[];},closest(){return null;},get isConnected(){return !this.removed;},set innerHTML(html){this.html=html;if(html.includes('kpi-x-action-title')){this.body=element();this.fields={};for(const [key,value] of Object.entries({title:'Recover KPI 1.1 - Safety',description:'Arrange additional talks',owner:'Alice',due:'2026-10-01',priority:'high'})){const field=element();field.id='kpi-x-action-'+key;field.value=value;this.fields[field.id]=field;nodes[field.id]=field;}this.save=element();this.save.closest=selector=>selector==='[data-kpi-action-save]'?this.save:null;this.close=element();this.close.closest=selector=>selector==='[data-kpi-action-close]'?this.close:null;this.controls=[...Object.values(this.fields),this.save,this.close];}},get innerHTML(){return this.html||'';}};}
  const document={readyState:'loading',activeElement:element(),addEventListener(){},getElementById:id=>nodes[id]||null,querySelectorAll:()=>[],createElement:element,body:{appendChild(el){nodes[el.id]=el;}}};
  const c={console,Date,document,setTimeout(fn){timers.push(fn);},kpiKPIs:[{id:'k',code:'1.1',name:'Safety',company_id:'company-a',objective_id:'o'}],kpiObjectives:[],kpiIndicators:[],kpiMonthlyData:{},prof:{id:'user-a',company_id:'company-a'},ccid:()=>c.company,company:'company-a',toast:(...args)=>toasts.push(args),nextCompanyRef:async()=> 'MAP-KPI-2026-001',api:async(url,options)=>{calls.push({url,options});return c.response();},response:async()=>[{id:'saved',action_ref:'MAP-KPI-2026-001'}],relationshipCreate:async(...args)=>{links.push(args);return c.linkResponse();},linkResponse:async()=>true};
  c.window=c;vm.createContext(c);let source=fs.readFileSync(path.join(root,'kpi-module-upgrade.js'),'utf8');const boot="if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',kpiXBoot);else kpiXBoot();";assert.ok(source.includes(boot));source=source.replace(boot,'window.qa={save:kpiXSaveAction,setRender:function(fn){kpiXRenderActions=fn;}};');vm.runInContext(source,c);c.qa.setRender(()=>{c.renders=(c.renders||0)+1;});
  const open=()=>{c.kpiXCreateAction('k');return nodes['kpi-x-action-modal'];};
  const save=modal=>c.qa.save('k',modal,modal.save);
  const click=(modal,target)=>modal.listeners.click({target,preventDefault(){},stopPropagation(){}});
  const message=modal=>modal.querySelector('[data-kpi-action-message]');
  return {c,nodes,calls,links,toasts,open,save,click,message,document};
}
test('clicking outside the recovery action form retains the draft',()=>{const h=harness(),modal=h.open();h.click(modal,modal);assert.equal(modal.removed,undefined);assert.equal(modal.fields['kpi-x-action-description'].value,'Arrange additional talks');});
test('opening the same recovery action twice does not discard an unsaved form',()=>{const h=harness(),modal=h.open();h.c.kpiXCreateAction('k');assert.equal(h.nodes['kpi-x-action-modal'],modal);});
test('required-field feedback is focused inside the form with values retained',async()=>{const h=harness(),modal=h.open();modal.fields['kpi-x-action-description'].value='';await h.save(modal);assert.match(h.message(modal).textContent,/required/i);assert.equal(h.message(modal).attributes.role,'alert');assert.equal(h.document.activeElement,h.message(modal));assert.equal(h.calls.length,0);assert.equal(h.toasts.length,0);assert.equal(modal.fields['kpi-x-action-title'].value,'Recover KPI 1.1 - Safety');});
test('reference errors retain the form and show text safely instead of a hidden toast',async()=>{const h=harness(),modal=h.open();h.c.nextCompanyRef=async()=>{throw new Error('<img src=x onerror=alert(1)>');};await h.save(modal);assert.match(h.message(modal).textContent,/<img/);assert.equal(h.message(modal).innerHTML,'');assert.equal(modal.save.disabled,false);assert.equal(h.calls.length,0);assert.equal(modal.removed,undefined);});
test('repeated validation reuses one in-form message',async()=>{const h=harness(),modal=h.open();modal.fields['kpi-x-action-description'].value='';await h.save(modal);const first=h.message(modal);await h.save(modal);assert.ok(first);assert.equal(h.message(modal),first);assert.equal(modal.body.children.length,1);});
test('a second save while reference allocation waits cannot create a duplicate',async()=>{const h=harness(),modal=h.open(),gate=deferred();let allocations=0;h.c.nextCompanyRef=()=>{allocations++;return gate.promise;};const first=h.save(modal),second=h.save(modal);assert.equal(allocations,1);h.click(modal,modal.close);assert.equal(modal.removed,undefined);gate.resolve('MAP-1');await Promise.all([first,second]);assert.equal(h.calls.length,1);assert.equal(h.links.length,1);});
test('switching company before save prevents reference allocation and record creation',async()=>{const h=harness(),modal=h.open();let allocations=0;h.c.nextCompanyRef=async()=>{allocations++;};h.c.company='company-b';await h.save(modal);assert.equal(allocations,0);assert.equal(h.calls.length,0);assert.match(h.message(modal).textContent,/company|account/i);});
test('switching account during reference allocation prevents the POST',async()=>{const h=harness(),modal=h.open(),gate=deferred();h.c.nextCompanyRef=()=>gate.promise;const work=h.save(modal);h.c.prof={id:'user-b',company_id:'company-a'};gate.resolve('MAP-1');await work;assert.equal(h.calls.length,0);assert.match(h.message(modal).textContent,/company|account/i);});
test('removing the selected KPI while reference allocation waits prevents the POST',async()=>{const h=harness(),modal=h.open(),gate=deferred();h.c.nextCompanyRef=()=>gate.promise;const work=h.save(modal);h.c.kpiKPIs=[];gate.resolve('MAP-1');await work;assert.equal(h.calls.length,0);assert.match(h.message(modal).textContent,/KPI/i);});
test('successful save preserves the established action payload and source link',async()=>{const h=harness(),modal=h.open();await h.save(modal);assert.equal(h.calls.length,1);const {url,options}=h.calls[0];assert.equal(url,'/action_tracker');assert.equal(options.m,'POST');assert.equal(options.b.company_id,'company-a');assert.equal(options.b.created_by,'user-a');assert.equal(options.b.source_id,'k');assert.equal(options.b.source_module,'kpi');assert.equal(options.b.source_table,'kpis');assert.equal(options.b.status,'open');assert.equal(options.b.requires_verification,true);assert.equal(options.b.description,'Arrange additional talks');assert.equal(h.links[0][3].company_id,'company-a');assert.equal(modal.removed,true);assert.equal(h.c.renders,1);});
test('a failed optional relationship cannot offer a second action creation',async()=>{const h=harness(),modal=h.open();h.c.linkResponse=async()=>{throw new Error('link unavailable');};await h.save(modal);assert.equal(modal.removed,undefined);assert.match(h.message(modal).textContent,/saved/i);assert.match(h.message(modal).textContent,/link/i);assert.equal(modal.save.disabled,true);await h.save(modal);assert.equal(h.calls.length,1);});
test('a render error after successful persistence never reports action not saved',async()=>{const h=harness(),modal=h.open();h.c.qa.setRender(()=>{throw new Error('render failed');});await h.save(modal);await h.save(modal);assert.equal(h.calls.length,1);assert.ok(h.toasts.every(([text])=>!/^Action not saved/i.test(text)));});
test('a late successful POST after company switch cannot link or refresh the new company',async()=>{const h=harness(),modal=h.open(),gate=deferred(),entered=deferred();h.c.response=()=>{entered.resolve();return gate.promise;};const work=h.save(modal);await entered.promise;h.c.company='company-b';gate.resolve([{id:'saved',action_ref:'MAP-1'}]);await work;assert.equal(h.calls.length,1);assert.equal(h.calls[0].options.b.company_id,'company-a');assert.equal(h.links.length,0);assert.equal(h.c.renders,undefined);assert.equal(modal.save.disabled,true);assert.match(h.message(modal).textContent,/saved.*original company/i);});
test('an unconfirmed network failure warns to check records before retrying',async()=>{const h=harness(),modal=h.open();h.c.response=async()=>{throw new Error('Network unavailable');};await h.save(modal);assert.equal(modal.removed,undefined);assert.equal(modal.save.disabled,false);assert.match(h.message(modal).textContent,/could not be confirmed/i);assert.match(h.message(modal).textContent,/Master Action Plan.*before retrying/i);});
test('a missing record id is not reported as successful persistence',async()=>{const h=harness(),modal=h.open();h.c.response=async()=>[{}];await h.save(modal);assert.equal(modal.removed,undefined);assert.match(h.message(modal).textContent,/could not be confirmed/i);assert.equal(h.links.length,0);});
test('explicit close remains available while idle and restores launcher focus',()=>{const h=harness(),launcher=h.document.activeElement,modal=h.open();h.click(modal,modal.close);assert.equal(modal.removed,true);assert.equal(launcher.focused,true);});
