const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8'),editor=read('kpi-definition-editor.js'),core=read('auris-core.js'),html=read('index.html'),css=read('kpi-module-upgrade.css');
const palette=[['Green','#1D9E75'],['Blue','#185FA5'],['Brown','#854F0B'],['Purple','#6B21A8'],['Dark green','#0F6E56'],['Red','#DC2626'],['Teal blue','#0369A1']];
function harness(colour='#1D9E75',withoutLegacyColour=false){
 const nodes={},listeners={},writes=[];let active;
 const node=id=>nodes[id]={id,value:'',dataset:{},style:{},disabled:false,isConnected:true,children:[],nodeType:1,setAttribute(k,v){this[k]=String(v);},getAttribute(k){return this[k]??null;},addEventListener(){},focus(){active=this;},getClientRects(){return this.style.display==='none'?[]:[{}];},matches(s){return id==='close'&&s.includes('h0129');},prepend(n){this.children.unshift(n);},remove(){this.removed=true;},parentElement:{querySelector:()=>({setAttribute(){}})}};
 for(const id of ['obj-code','obj-name','obj-year','obj-delete-btn','obj-modal-title','year-sel','close','save','launcher','kpi-color-selection'])node(id);
 nodes['year-sel'].value='2026';const picker=node('kpi-color-picker'),buttons=palette.map(([name,value],i)=>{const n=node('colour-'+i);n['aria-label']=name;n['data-objective-color']=value;n['data-auris-onclick']='h'+(130+i).toString().padStart(4,'0');return n;});picker.querySelectorAll=()=>buttons;picker.querySelector=()=>buttons[0];
 const modal=node('obj-modal'),card=node('card');modal.style.display='none';modal.querySelector=s=>s.includes('-message]')?card.children.find(n=>!n.removed):s.includes('h0129')?nodes.close:card;const controls=[nodes['obj-code'],nodes['obj-name'],nodes['obj-year'],nodes['obj-delete-btn'],nodes.close,nodes.save,...buttons];modal.querySelectorAll=()=>controls;modal.contains=n=>controls.includes(n)||n===nodes['obj-modal-title']||card.children.includes(n);
 const original={id:'o',company_id:'c',year:2026,name:'Safety',code:'1',color:colour};const c={Date,document:{getElementById:id=>nodes[id]||null,get activeElement(){return active;},querySelectorAll:()=>buttons,createElement:()=>node('alert'),addEventListener(type,fn){listeners[type]=fn;}},prof:{id:'u',company_id:'c'},ccid:()=> 'c',kpiCanEdit:()=>true,kpiSelectedColor:colour,kpiObjectives:[original],kpiRenderOverview(){},kpiRenderMonthly(){},kpiUpdateMetrics(){},toast(){},api:async(u,o)=>{if(o){writes.push(o);c.stored={id:'o',...o.b};}return [c.stored||original];}};if(withoutLegacyColour)delete c.kpiSelectedColor;c.window=c;vm.createContext(c);vm.runInContext(editor,c);vm.runInContext(core.slice(core.indexOf('function closeKpiModal('),core.indexOf('async function kpiDeleteObjective')),c);vm.runInContext(read('auris-static-event-handlers.js'),c);nodes.launcher.focus();
 return {c,nodes,modal,buttons,controls,writes,listeners,open:()=>c.openObjModal('o'),selected:()=>buttons.filter(n=>n['aria-pressed']==='true')};
}
test('all seven colour options are named non-submit native buttons using the existing CSP routes',()=>{
 const group=html.slice(html.indexOf('<div id="kpi-color-picker"'),html.indexOf('id="obj-delete-btn"'));
 assert.match(group,/role="group" aria-label="Objective colour"/);
 assert.equal((group.match(/data-objective-color=/g)||[]).length,7);
 palette.forEach(([name,colour],i)=>{const tag=[...group.matchAll(/<button\b[^>]+>/g)].map(m=>m[0]).find(t=>t.includes('data-objective-color="'+colour+'"'));assert.ok(tag,name);assert.match(tag,/type="button"/);assert.ok(tag.includes('aria-label="'+name+'"'));assert.match(tag,/aria-pressed="(?:true|false)"/);assert.ok(tag.includes('data-auris-onclick="h'+(130+i).toString().padStart(4,'0')+'"'));});
 assert.doesNotMatch(group,/<div[^>]*class="kpi-color-dot/);
});
test('selection has a non-colour visual marker, an announcement, and 44px targets',()=>{assert.match(html,/id="kpi-color-selection"[^>]*aria-live="polite"/);assert.match(css,/#obj-modal \.kpi-color-dot\{[^}]*width:44px[^}]*height:44px/);assert.match(css,/\.kpi-color-dot\[aria-pressed="true"\]::after\{content:"✓"/);});
for(const [name,colour]of palette)test('opening restores the saved '+name+' selection without inline-handler parsing',()=>{const h=harness(colour.toLowerCase());h.open();assert.equal(h.selected().length,1);assert.equal(h.selected()[0].getAttribute('data-objective-color'),colour);assert.equal(h.nodes['kpi-color-selection'].textContent,'Selected colour: '+name);assert.equal(h.c.kpiSelectedColor,colour.toLowerCase());});
test('unknown saved colour is retained, not silently replaced by Green',async()=>{const h=harness('#abcdef');h.open();assert.equal(h.selected().length,0);assert.match(h.nodes['kpi-color-selection'].textContent,/saved colour.*not in this palette/i);await h.c.kpiSaveObjective();assert.equal(h.writes[0].b.color,'#abcdef');});
test('new objective resets selection and announcement to Green',()=>{const h=harness('#DC2626');h.open();h.c.closeKpiModal('obj-modal');h.c.openObjModal();assert.equal(h.selected().length,1);assert.equal(h.selected()[0],h.buttons[0]);assert.equal(h.c.kpiSelectedColor,'#1D9E75');assert.equal(h.nodes['kpi-color-selection'].textContent,'Selected colour: Green');});
test('existing CSP click dispatch selects exactly one colour without writing or closing',()=>{const h=harness();h.open();h.listeners.click({target:h.buttons[3]});assert.equal(h.c.kpiSelectedColor,'#6B21A8');assert.equal(h.selected().length,1);assert.equal(h.selected()[0],h.buttons[3]);assert.equal(h.modal.style.display,'flex');assert.equal(h.writes.length,0);h.listeners.click({target:h.buttons[3]});assert.equal(h.selected().length,1);});
for(const state of ['_kpiObjectiveBusy','_kpiObjectiveSaved','_kpiObjectiveUncertain'])test(state+' blocks colour changes',()=>{const h=harness();h.open();h.modal[state]=true;h.c.kpiSelectColor('#DC2626',h.buttons[5]);assert.equal(h.c.kpiSelectedColor,'#1D9E75');assert.equal(h.selected()[0],h.buttons[0]);});
test('disabled swatches, hidden editors and mismatched elements cannot change colour',()=>{const h=harness();h.open();h.buttons[5].disabled=true;h.c.kpiSelectColor('#DC2626',h.buttons[5]);h.c.kpiSelectColor('#6B21A8',h.buttons[1]);assert.equal(h.c.kpiSelectedColor,'#1D9E75');h.c.closeKpiModal('obj-modal');h.c.kpiSelectColor('#6B21A8',h.buttons[3]);assert.equal(h.c.kpiSelectedColor,'#1D9E75');});
test('non-palette values cannot be selected and no visual state is injected',()=>{const h=harness();h.open();h.c.kpiSelectColor('url(https://invalid.test/image)',h.buttons[1]);assert.equal(h.c.kpiSelectedColor,'#1D9E75');assert.equal(h.selected()[0],h.buttons[0]);});
test('successful save persists the chosen colour and reopening restores it',async()=>{const h=harness();h.open();h.c.kpiSelectColor('#185FA5',h.buttons[1]);const result=await h.c.kpiSaveObjective();assert.equal(result.complete,true);assert.equal(h.writes[0].b.color,'#185FA5');h.open();assert.equal(h.selected()[0],h.buttons[1]);assert.equal(h.nodes['kpi-color-selection'].textContent,'Selected colour: Blue');});
test('pending save disables colour buttons and failed save restores them without losing selection',async()=>{const h=harness();h.open();h.c.kpiSelectColor('#DC2626',h.buttons[5]);let reject;h.c.api=()=>new Promise((_r,j)=>{reject=j;});const work=h.c.kpiSaveObjective();assert.ok(h.buttons.every(n=>n.disabled));h.c.kpiSelectColor('#185FA5',h.buttons[1]);assert.equal(h.c.kpiSelectedColor,'#DC2626');reject(new Error('Synthetic failure'));await work;assert.ok(h.buttons.every(n=>!n.disabled));assert.equal(h.selected()[0],h.buttons[5]);assert.equal(h.modal.style.display,'flex');});

test('editor initialises colour without a legacy global before first objective creation',()=>{const h=harness(undefined,true);h.c.openObjModal();assert.equal(h.modal.style.display,'flex');assert.equal(h.c.kpiSelectedColor,'#1D9E75');assert.equal(h.selected()[0],h.buttons[0]);});
