const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('kpi-monthly-review.js','utf8');
function harness(){
 const node=()=>({innerHTML:'',className:'',isConnected:true,addEventListener(){},remove(){this.removed=true;},focus(){},querySelector(){return {focus(){}};}}),host=node();
 const c={console,Date,document:{activeElement:node(),body:{appendChild(){}},getElementById(){return {value:'2025'};},createElement(){return host;}},company:'a',user:'owner',ccid:()=>c.company,prof:{id:'owner'},activeRole:()=>c.role,role:'admin',api:async(url,opts)=>{c.calls.push([url,opts.b]);return c.reply(url,opts.b);},calls:[],appConfirmAction:async()=>true};
 c.route={submitter:'owner',reviewer:'reviewer',approver:'approver',submitter_name:'Owner',reviewer_name:'Reviewer',approver_name:'Approver',self_approval:false,config_version:1};
 c.preview={company_id:'a',year:2025,month:8,review:null,snapshot:[{kpi_id:'k',kpi_name:'Safe <KPI>',indicator_id:'i',indicator:{name:'Count'},result_month:8,result:{actual:0,ytd:0,comment:'<script>unsafe</script>'}}],route:c.route,fingerprint:'fingerprint',missing:0,period_open:false};
 c.reply=async(url,b)=>{if(url.includes('get_kpi'))return structuredClone(c.preview);let row={id:'r',company_id:'a',year:2025,month:8,status:({submit:'submitted',verify:'verified',approve:'approved',request_revision:'revision_requested',reject:'rejected',request_reopen:'reopen_requested',allow_reopen:'revision_requested',deny_reopen:'approved'})[b.p_action],revision:(b.p_expected_revision||0)+1,snapshot:c.preview.snapshot,route:c.route,fingerprint:'fingerprint',submitted_by:'owner'};c.preview.review=row;return row;};
 c.window=c;vm.createContext(c);vm.runInContext(source.replace('root.KpiMonthlyReview=','root.qa={getState:()=>state,load:load,act:act,available:available,render:render};root.KpiMonthlyReview='),c);
 return {c,host,async open(){await c.KpiMonthlyReview.open({year:2025,month:8});return c.qa.getState();},writes:()=>c.calls.filter(([url])=>url.includes('transition_'))};
}
test('submission records exact preview and preserves zero and escaped evidence',async()=>{const h=harness(),s=await h.open();assert.match(h.host.innerHTML,/Safe &lt;KPI&gt;/);assert.match(h.host.innerHTML,/&lt;script&gt;/);assert.match(h.host.innerHTML,/>0<\/td>/);await h.c.qa.act(s,'submit');assert.equal(h.writes().length,1);assert.equal(h.writes()[0][1].p_fingerprint,'fingerprint');assert.equal(h.writes()[0][1].p_expected_id,null);assert.equal(s.data.review.status,'submitted');assert.match(h.host.innerHTML,/Submitted saved/);});
test('missing, future and ambiguous route previews cannot submit',async()=>{for(const change of [{missing:1},{period_open:true},{snapshot:[]},{route:{error:'Ambiguous account'}}]){const h=harness();Object.assign(h.c.preview,change);const s=await h.open();await h.c.qa.act(s,'submit');assert.equal(h.writes().length,0);}});
test('only current assigned reviewer or approver sees decisions',async()=>{const h=harness(),s=await h.open();await h.c.qa.act(s,'submit');assert.deepEqual(Array.from(h.c.qa.available(s)),[]);h.c.prof.id='reviewer';await h.open();let next=h.c.qa.getState();assert.ok(h.c.qa.available(next).includes('verify'));await h.c.qa.act(next,'verify');assert.equal(next.data.review.status,'verified');h.c.prof.id='approver';next=await h.open();await h.c.qa.act(next,'approve');assert.equal(next.data.review.status,'approved');});
test('stale decision and lost acknowledgement retain selectable reason and prohibit retries',async()=>{for(const outcome of ['conflict','lost','bad']){const h=harness();let s=await h.open();await h.c.qa.act(s,'submit');h.c.prof.id='reviewer';s=await h.open();s.reason='Retain this evidence';h.c.reply=async()=>{if(outcome==='bad')return {id:'foreign',company_id:'b'};throw Error(outcome==='conflict'?'AURIS_MONTH_REVIEW_CONFLICT':'Lost response');};await h.c.qa.act(s,'verify');assert.equal(s.reason,'Retain this evidence');assert.equal(s.uncertain,true);assert.match(h.host.innerHTML,/<textarea[^>]+readonly/);const count=h.writes().length;await h.c.qa.act(s,'verify');assert.equal(h.writes().length,count);assert.match(h.host.innerHTML,/Reload review/);}});
test('duplicate confirmation and cancelled decisions do not write twice',async()=>{const h=harness(),s=await h.open();let resolve;h.c.appConfirmAction=()=>new Promise(r=>resolve=r);const pending=h.c.qa.act(s,'submit');await h.c.qa.act(s,'submit');assert.equal(h.writes().length,0);resolve(false);await pending;assert.equal(h.writes().length,0);assert.equal(s.busy,false);});
test('reason is required for revision and successful revision requires a fresh preview',async()=>{const h=harness();let s=await h.open();await h.c.qa.act(s,'submit');h.c.prof.id='reviewer';s=await h.open();await h.c.qa.act(s,'request_revision');assert.equal(h.writes().length,1);s.reason='Correct the reference';await h.c.qa.act(s,'request_revision');assert.equal(s.data.review.status,'revision_requested');assert.equal(s.uncertain,true);});
test('company changes during confirmation or response never publish a foreign result',async()=>{for(const phase of ['confirm','request']){const h=harness(),s=await h.open();if(phase==='confirm')h.c.appConfirmAction=async()=>{h.c.company='b';return true;};else{const reply=h.c.reply;h.c.reply=async(...args)=>{h.c.company='b';return reply(...args);};}await h.c.qa.act(s,'submit');assert.equal(h.writes().length,phase==='confirm'?0:1);assert.match(h.host.innerHTML,/Company or account changed/);assert.doesNotMatch(h.host.innerHTML,/Safe|Submitted saved/);}});
test('out of order preview responses are discarded',async()=>{const h=harness();let first;h.c.reply=()=>new Promise(r=>first=r);const opening=h.open(),s=h.c.qa.getState();h.c.reply=async()=>({...h.c.preview,month:9});s.month=9;await h.c.qa.load(s);first({...h.c.preview});await opening;assert.equal(s.data.month,9);});
