const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),core=fs.readFileSync(path.join(root,'auris-core.js'),'utf8'),editor=fs.readFileSync(path.join(root,'kpi-definition-editor.js'),'utf8');
function deferred(){let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};}
function harness(kind='kpi'){
 const nodes={},calls=[],notices=[],confirmations=[],cleared=[];let active;
 function node(id,value=''){return nodes[id]={id,value,style:{},dataset:{},disabled:false,isConnected:true,children:[],setAttribute(k,v){this[k]=String(v);},getAttribute(k){return this[k]||null;},focus(){active=this;},prepend(n){this.children.unshift(n);},remove(){this.removed=true;},matches(s){return id==='close'&&s.includes(kind==='objective'?'h0129':'h0139');},getClientRects(){return [{}];}};}
 const modal=node(kind==='objective'?'obj-modal':'kpi-edit-modal');modal.style.display='flex';
 const card=node('card'),save=node('save'),close=node('close'),archive=node('archive'),name=node('name','Unsaved name'),title=node(kind==='objective'?'obj-modal-title':'kpi-modal-title'),year=node('year-sel','2026'),controls=[save,close,archive,name];
 modal.querySelector=s=>s.includes('-message]')?card.children.find(n=>!n.removed):card;modal.querySelectorAll=()=>controls;modal.contains=el=>controls.includes(el)||el===title||card.children.includes(el);
 const obj={id:'o',company_id:'c',year:2026,name:'Safety objective',code:'1',color:'#1D9E75'},kpi={id:'k',company_id:'c',year:2026,objective_id:'o',name:'Toolbox talks',code:'1.1',status:'not_started',approval_status:'draft',lifecycle_revision:2};
 const c={console:{error(){}},Date,Set,Map,document:{get activeElement(){return active;},getElementById:id=>nodes[id]||null,createElement:()=>node('message')},prof:{id:'u',company_id:'c'},company:'c',ccid:()=>c.company,isSA:()=>false,isMgr:()=>c.allowed,kpiCanEdit:()=>c.allowed,allowed:true,editable:true,KpiGovernedWorkflow:{canEdit:k=>c.editable&&['draft','rejected','revision_requested'].includes(k.approval_status||'draft')},kpiEditKpiId:'k',kpiObjectives:[{...obj}],kpiKPIs:[{...kpi}],kpiIndicators:[{id:'i',kpi_id:'k'},{id:'unrelated-i',kpi_id:'unrelated'}],kpiMonthlyData:{i:{8:{actual:4}},'unrelated-i':{8:{actual:8}}},storedObjectives:[{...obj}],storedKpis:[{...kpi}],toast:(...a)=>notices.push(a),toastActionError:(...a)=>notices.push(a),appConfirmAction:async options=>{confirmations.push(options);return c.confirm(options);},confirm:async()=>true,api:async(u,o)=>{calls.push({url:u,options:o});return c.response(u,o);},ohArchivedText:n=>'[Archived 2026-09-09] '+n,kpiRenderOverview(){c.renders++;},kpiRenderMonthly(){},kpiUpdateMetrics(){},renders:0,kpiLoadAll:async()=>{},kpiXClearEditorDraft:id=>cleared.push(id),response:async(u,o)=>{
  const url=new URL('http://fixture.local'+u),data=url.pathname==='/objectives'?c.storedObjectives:url.pathname==='/kpis_v2'?c.storedKpis:null;if(!data)throw new Error('Unexpected '+u);
  const rows=data.filter(row=>[...url.searchParams].every(([key,val])=>{if(['select','limit'].includes(key))return true;return val==='is.null'?row[key]==null:String(row[key])===val.slice(3);}));
  if(o){assert.equal(o.m,'PATCH');rows.forEach(row=>Object.assign(row,o.b));}return rows.map(row=>({...row}));
 }};c.window=c;vm.createContext(c);vm.runInContext(editor,c);vm.runInContext(core.slice(core.indexOf('function closeKpiModal('),core.indexOf('function kpiCalcYTD(')),c);
 c.kpiEditObjId='o';modal._kpiObjectiveContext={companyId:'c',actorId:'u',viewYear:2026,editId:'o'};modal._kpiDefinitionContext={companyId:'c',actorId:'u',year:2026,kpiId:'k'};archive.focus();
 return {c,modal,nodes,controls,calls,notices,confirmations,cleared,obj,kpi,archive:()=>kind==='objective'?c.kpiDeleteObjective():c.kpiDeleteKPI(),writes:()=>calls.filter(x=>x.options),message:()=>card.children.find(n=>!n.removed)};
}
for(const kind of ['kpi','objective']){
 test(kind+' confirmation names the stored record and cancellation retains draft/focus',async()=>{const h=harness(kind);h.c.confirm=async()=>false;await h.archive();assert.equal(h.writes().length,0);assert.equal(h.nodes.name.value,'Unsaved name');assert.equal(h.modal.style.display,'flex');assert.equal(h.c.document.activeElement,h.nodes.archive);assert.match(JSON.stringify(h.confirmations),kind==='objective'?/Safety objective/:/Toolbox talks/);assert.equal(h.nodes.save.disabled,false);});
 test(kind+' successful archive is scoped, verified and never deletes history',async()=>{const h=harness(kind);const result=await h.archive();assert.equal(result.complete,true);assert.equal(h.modal.style.display,'none');assert.equal(h.c.kpiKPIs.length,0);assert.equal(h.c.kpiMonthlyData.i[8].actual,4);assert.equal(h.c.kpiIndicators[0].id,'unrelated-i');assert.equal(h.c.kpiMonthlyData['unrelated-i'][8].actual,8);assert.equal(h.cleared[0],'k');for(const call of h.calls)assert.match(call.url,/company_id=eq.c/);for(const call of h.writes()){assert.equal(call.options.m,'PATCH');assert.equal(call.options.p,'return=representation');}assert.ok(h.calls.length>h.writes().length);assert.equal(h.notices.length,1);if(kind==='objective')assert.equal(h.c.kpiObjectives.length,0);else assert.equal(h.c.kpiObjectives.length,1);});
 for(const [label,change]of [['company',c=>c.company='other'],['account',c=>c.prof.id='other'],['year',c=>c.document.getElementById('year-sel').value='2027'],['record',c=>{c.kpiEditKpiId='other';c.kpiEditObjId='other';}],['permission',c=>c.allowed=false]])test(kind+' '+label+' change during confirmation stops writes',async()=>{const h=harness(kind);h.c.confirm=async()=>{change(h.c);return true;};await h.archive();assert.equal(h.writes().length,0);assert.ok(h.message());assert.equal(h.notices.length,0);});
 test(kind+' duplicate archive/save/close/replacement is blocked during confirmation',async()=>{const h=harness(kind),gate=deferred(),entered=deferred();h.c.confirm=()=>{entered.resolve();return gate.promise;};const work=h.archive();await entered.promise;await h.archive();await(kind==='objective'?h.c.kpiSaveObjective():h.c.kpiSaveKPI());assert.equal(h.c.closeKpiModal(h.modal.id),false);assert.equal(kind==='objective'?h.c.openObjModal('o'):h.c.openKpiAddModal('k'),false);assert.equal(h.controls.every(n=>n.disabled),true);gate.resolve(false);await work;assert.equal(h.confirmations.length,1);assert.equal(h.writes().length,0);assert.equal(h.nodes.save.disabled,false);});
 test(kind+' preflight failure stays inside the form and allows retry',async()=>{const h=harness(kind);h.c.response=async()=>{throw new Error('<img> network unavailable');};await h.archive();assert.equal(h.confirmations.length,0);assert.equal(h.writes().length,0);assert.equal(h.notices.length,0);assert.match(h.message().textContent,/<img>/);assert.equal(h.message().innerHTML,undefined);assert.equal(h.message().role,'alert');assert.equal(h.c.document.activeElement,h.message());assert.equal(h.nodes.save.disabled,false);});
 test(kind+' unknown write outcome blocks automatic retry and leaves Close available',async()=>{const h=harness(kind),base=h.c.response;h.c.response=async(u,o)=>{if(o)throw new Error('Connection lost');return base(u,o);};await h.archive();await h.archive();await(kind==='objective'?h.c.kpiSaveObjective():h.c.kpiSaveKPI());assert.equal(h.writes().length,1);assert.equal(h.nodes.save.disabled,true);assert.equal(h.nodes.archive.disabled,true);assert.equal(h.nodes.close.disabled,false);assert.equal(h.notices.length,0);assert.match(h.message().textContent,/could not be confirmed/i);assert.equal(h.cleared.length,0);});
 test(kind+' missing returned row is not archive success',async()=>{const h=harness(kind),base=h.c.response;h.c.response=(u,o)=>o?[]:base(u,o);await h.archive();assert.equal(h.notices.length,0);assert.equal(h.nodes.save.disabled,true);assert.equal(h.nodes.close.disabled,false);assert.equal(h.c.kpiKPIs.length,1);});
 test(kind+' refresh failure retains partial outcome without clearing caches or drafts',async()=>{const h=harness(kind),base=h.c.response;h.c.response=(u,o)=>!o&&h.writes().length?Promise.reject(new Error('Read unavailable')):base(u,o);await h.archive();assert.equal(h.notices.length,0);assert.equal(h.modal.style.display,'flex');assert.equal(h.c.kpiKPIs.length,1);assert.equal(h.c.kpiMonthlyData.i[8].actual,4);assert.equal(h.cleared.length,0);assert.match(h.message().textContent,/confirmed|archived/i);assert.equal(h.nodes.close.disabled,false);});
 test(kind+' company change after write cannot change the new company cache',async()=>{const h=harness(kind),base=h.c.response;h.c.response=async(u,o)=>{const rows=await base(u,o);if(o){h.c.company='other';h.c.kpiKPIs=[{id:'other'}];}return rows;};await h.archive();assert.equal(h.writes().length,1);assert.equal(h.c.kpiKPIs[0].id,'other');assert.equal(h.c.renders,0);assert.equal(h.notices.length,0);});
 test(kind+' hidden form cannot archive from stale global IDs',async()=>{const h=harness(kind);h.modal.style.display='none';await h.archive();assert.equal(h.calls.length,0);assert.equal(h.confirmations.length,0);});
 test(kind+' controlled KPI state blocks archiving before confirmation',async()=>{const h=harness(kind);h.c.storedKpis[0].approval_status='locked';await h.archive();assert.equal(h.writes().length,0);assert.equal(h.confirmations.length,0);assert.match(h.message().textContent,/workflow|review|locked|controlled/i);});
 test(kind+' workflow changed after confirmation stops the archive',async()=>{const h=harness(kind);h.c.confirm=async()=>{h.c.storedKpis[0].approval_status='submitted';return true;};await h.archive();assert.equal(h.writes().length,0);assert.ok(h.message());});
 test(kind+' late list failure never claims success',async()=>{const h=harness(kind);h.c.kpiRenderOverview=()=>{throw new Error('Render failed');};await h.archive();assert.equal(h.notices.length,0);assert.equal(h.nodes.save.disabled,true);assert.equal(h.nodes.close.disabled,false);});
}
test('objective cascade uses server children, including those outside the displayed year',async()=>{const h=harness('objective');h.c.storedKpis.push({...h.kpi,id:'second',year:2025});await h.archive();assert.equal(h.writes().length,3);assert.match(JSON.stringify(h.confirmations),/2/);assert.equal(h.c.storedKpis[1].status,'archived');});
test('objective cascade refuses a changed child set after confirmation',async()=>{const h=harness('objective');h.c.confirm=async()=>{h.c.storedKpis.push({...h.kpi,id:'added'});return true;};await h.archive();assert.equal(h.writes().length,0);assert.ok(h.message());});
test('objective failure after one child archive never announces full completion',async()=>{const h=harness('objective'),base=h.c.response;h.c.storedKpis.push({...h.kpi,id:'second'});h.c.response=(u,o)=>o&&u.includes('id=eq.second')?Promise.reject(new Error('Second update failed')):base(u,o);await h.archive();assert.equal(h.writes().length,2);assert.equal(h.c.storedObjectives[0].name,h.obj.name);assert.equal(h.notices.length,0);assert.match(h.message().textContent,/1.*confirmed/i);assert.equal(h.nodes.close.disabled,false);});
test('objective cannot be archived if a new active child appears during writes',async()=>{const h=harness('objective'),base=h.c.response;h.c.response=async(u,o)=>{const rows=await base(u,o);if(o&&u.startsWith('/kpis_v2'))h.c.storedKpis.push({...h.kpi,id:'late'});return rows;};await h.archive();assert.equal(h.writes().filter(x=>x.url.startsWith('/objectives')).length,0);assert.equal(h.notices.length,0);assert.ok(h.message());});
test('archive rejects missing workflow services instead of broadening permissions',async()=>{const h=harness();h.c.KpiGovernedWorkflow=null;await h.archive();assert.equal(h.writes().length,0);assert.match(h.message().textContent,/workflow/i);});
test('archive conditional updates retain original lifecycle revision and state',async()=>{const h=harness();await h.archive();assert.match(h.writes()[0].url,/lifecycle_revision=eq.2/);assert.match(h.writes()[0].url,/approval_status=eq.draft/);assert.match(h.writes()[0].url,/status=eq.not_started/);});
test('objective editor explicitly overrides the hidden archive class only in edit mode',()=>{assert.match(editor,/if \(delBtn\) delBtn\.style\.display = 'inline-flex'/);assert.match(editor,/if \(delBtn\) delBtn\.style\.display = 'none'/);});
test('objective without children can be archived without changing any KPI',async()=>{const h=harness('objective');h.c.storedKpis=[];h.c.kpiKPIs=[];assert.equal((await h.archive()).complete,true);assert.equal(h.writes().length,1);assert.ok(h.writes()[0].url.startsWith('/objectives'));});
test('already archived children are retained without rewriting their lifecycle',async()=>{const h=harness('objective');h.c.storedKpis.push({...h.kpi,id:'old',status:'archived',approval_status:'locked'});assert.equal((await h.archive()).complete,true);assert.equal(h.writes().length,2);assert.equal(h.c.storedKpis[1].approval_status,'locked');});
test('unavailable child list never means an empty cascade',async()=>{const h=harness('objective'),base=h.c.response;h.c.response=(u,o)=>u.includes('objective_id=eq.o')?null:base(u,o);await h.archive();assert.equal(h.writes().length,0);assert.equal(h.confirmations.length,0);});
test('foreign child data fails closed before any confirmation or write',async()=>{const h=harness('objective'),base=h.c.response;h.c.response=(u,o)=>u.includes('objective_id=eq.o')?[{...h.kpi,company_id:'other'}]:base(u,o);await h.archive();assert.equal(h.writes().length,0);assert.equal(h.confirmations.length,0);});
test('saturated child response cannot silently truncate the planned cascade',async()=>{const h=harness('objective');h.c.storedKpis=Array.from({length:1000},(_,i)=>({...h.kpi,id:'k'+i}));await h.archive();assert.equal(h.writes().length,0);assert.equal(h.confirmations.length,0);});
test('concurrent workflow change at PATCH returns no row and cannot be success',async()=>{const h=harness(),base=h.c.response;h.c.response=(u,o)=>{if(o)h.c.storedKpis[0].approval_status='submitted';return base(u,o);};await h.archive();assert.equal(h.c.storedKpis[0].status,'not_started');assert.equal(h.notices.length,0);assert.equal(h.nodes.save.disabled,true);});
test('returned archive identity must match the confirmed KPI',async()=>{const h=harness(),base=h.c.response;h.c.response=async(u,o)=>{const rows=await base(u,o);if(o)rows[0].id='other';return rows;};await h.archive();assert.equal(h.c.kpiKPIs[0].id,'k');assert.equal(h.notices.length,0);assert.equal(h.nodes.close.disabled,false);});
test('archive actions use accurate visible labels without renaming public dispatcher handlers',()=>{const html=fs.readFileSync(path.join(root,'index.html'),'utf8');assert.match(html, /id="obj-delete-btn"[^>]*data-auris-onclick="h0137"[^>]*>.*?<\/i>Archive objective<\/button>/);assert.match(html,/id="kpi-delete-btn"[^>]*data-auris-onclick="h0141"[^>]*>.*?<\/i>Archive KPI<\/button>/);});
