const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8'),editor=read('kpi-definition-editor.js'),core=read('auris-core.js');
function harness(kind='kpi'){
 const nodes={};let active;
 function node(id){const n={id,value:'',style:{},dataset:{},tabIndex:0,disabled:false,isConnected:true,children:[],listeners:{},visibility:'visible',parentElement:{querySelector:()=>({setAttribute(){}})},setAttribute(k,v){this[k]=v;if(k==='tabindex')this.tabIndex=Number(v);},getAttribute(k){return this[k];},appendChild(n){this.children.push(n);},focus(){active=this;},getClientRects(){return this.hidden||this.style.display==='none'?[]:[{}];},closest(s){return s.includes('role=')?this.innerDialog||null:this.inert?{}:null;},matches(){return this.fieldsetDisabled||false;},addEventListener(k,fn){(this.listeners[k]??=new Set()).add(fn);},removeEventListener(k,fn){this.listeners[k]?.delete(fn);}};nodes[id]=n;return n;}
 for(const id of ['kpi-name','kpi-code','kpi-obj-sel','kpi-description','kpi-freq','kpi-resp','kpi-data-provider','kpi-data-source','kpi-reviewer','kpi-approver','kpi-status','kpi-approval-status','kpi-delete-btn','kpi-indicators-list','obj-name','obj-code','obj-year','obj-delete-btn','year-sel'])node(id);
 const modal=node(kind==='objective'?'obj-modal':'kpi-edit-modal'),title=node(kind==='objective'?'obj-modal-title':'kpi-modal-title'),first=node('close'),middle=node('name'),last=node('save'),launcher=node('launcher'),body=node('body');
 modal.style.display='none';modal.controls=[first,middle,last];modal.querySelector=s=>s.includes('data-auris-onclick')?first:null;modal.querySelectorAll=()=>modal.controls;modal.contains=n=>n===title||modal.controls.includes(n)||n?.parentModal===modal;
 const c={document:{getElementById:id=>nodes[id]||null,get activeElement(){return active;},body,createElement:()=>node('option')},getComputedStyle:n=>({visibility:n.visibility}),prof:{id:'u',company_id:'c'},ccid:()=> 'c',isMgr:()=>c.allowed,kpiCanEdit:()=>c.allowed,allowed:true,kpiObjectives:[],kpiKPIs:[],kpiIndicators:[],kpiEditKpiId:null,kpiSelectedColor:'#1D9E75',fillPplDrops(){},setSelectValueWithFallback(id,value){nodes[id].value=value;},toast(){},appConfirmAction:async()=>true};c.window=c;vm.createContext(c);vm.runInContext(editor,c);vm.runInContext(core.slice(core.indexOf('function closeKpiModal('),core.indexOf('async function kpiDeleteObjective')),c);c.kpiAddIndicatorRow=()=>{};
 nodes['year-sel'].value='2026';launcher.focus();
 const open=()=>kind==='objective'?c.openObjModal():c.openKpiAddModal();
 const key=(options={},target=modal)=>{const e={key:'Tab',shiftKey:false,preventDefault(){this.defaultPrevented=true;},...options};for(const fn of target.listeners.keydown||[])fn(e);return e;};
 return {c,node,nodes,modal,title,first,middle,last,launcher,body,open,key,get active(){return active;}};
}
for(const kind of ['objective','kpi']){
 test(kind+' opening focuses its named title and installs one local keyboard guard',()=>{const h=harness(kind);h.open();assert.equal(h.active,h.title);assert.equal(h.modal['aria-modal'],'true');assert.equal(h.title.tabIndex,-1);assert.equal(h.modal.listeners.keydown.size,1);h.c.closeKpiModal(h.modal.id);h.open();assert.equal(h.modal.listeners.keydown.size,1);});
 test(kind+' Tab from title reaches first control; Shift+Tab reaches last',()=>{const h=harness(kind);h.open();assert.equal(h.key().defaultPrevented,true);assert.equal(h.active,h.first);h.title.focus();h.key({shiftKey:true});assert.equal(h.active,h.last);});
 test(kind+' boundary keys wrap; internal Tab stays native',()=>{const h=harness(kind);h.open();h.last.focus();h.key();assert.equal(h.active,h.first);h.key({shiftKey:true});assert.equal(h.active,h.last);h.middle.focus();assert.equal(h.key().defaultPrevented,undefined);assert.equal(h.active,h.middle);});
 test(kind+' new controls participate without rebinding',()=>{const h=harness(kind);h.open();const added=h.node('new-indicator');h.modal.controls.push(added);added.focus();h.key();assert.equal(h.active,h.first);h.first.focus();h.key({shiftKey:true});assert.equal(h.active,added);});
 test(kind+' a focused validation message re-enters the form in either direction',()=>{const h=harness(kind);h.open();const alert=h.node('alert');alert.tabIndex=-1;alert.parentModal=h.modal;h.modal.controls.push(alert);alert.focus();h.key();assert.equal(h.active,h.first);alert.focus();h.key({shiftKey:true});assert.equal(h.active,h.last);});
 test(kind+' disabled pending controls leave focus on the title',()=>{const h=harness(kind);h.open();h.modal.controls.forEach(n=>n.disabled=true);assert.equal(h.key().defaultPrevented,true);assert.equal(h.active,h.title);assert.equal(h.key({shiftKey:true}).defaultPrevented,true);});
 test(kind+' hidden editor and non-Tab shortcuts are untouched',()=>{const h=harness(kind);h.open();h.middle.value='Retained draft';for(const options of [{key:'Escape'},{key:'Enter'},{key:'ArrowDown'},{ctrlKey:true},{altKey:true},{metaKey:true},{defaultPrevented:true}]){const e=h.key(options);assert.equal(e.defaultPrevented,options.defaultPrevented);assert.equal(h.modal.style.display,'flex');assert.equal(h.middle.value,'Retained draft');}h.modal.style.display='none';assert.equal(h.key().defaultPrevented,undefined);});
 test(kind+' explicit close restores original launcher and clears the reference',()=>{const h=harness(kind);h.open();h.c.closeKpiModal(h.modal.id);assert.equal(h.active,h.launcher);assert.equal(h.modal[kind==='objective'?'_kpiObjectiveReturnFocus':'_kpiDefinitionReturnFocus'],null);assert.equal(h.modal.style.display,'none');});
 test(kind+' busy editor cannot close or replace the saved return point',()=>{const h=harness(kind);h.open();h.modal[kind==='objective'?'_kpiObjectiveBusy':'_kpiDefinitionBusy']=true;const key=kind==='objective'?'_kpiObjectiveReturnFocus':'_kpiDefinitionReturnFocus';assert.equal(h.c.closeKpiModal(h.modal.id),false);assert.equal(h.open(),false);assert.equal(h.modal[key],h.launcher);assert.equal(h.modal.style.display,'flex');});
 test(kind+' lost launcher falls back to the visible module control',()=>{const h=harness(kind);h.open();h.launcher.isConnected=false;const fallback=h.node(kind==='objective'?'kpi-x-new-objective':'kpi-x-new-kpi');h.c.closeKpiModal(h.modal.id);assert.equal(h.active,fallback);});
 test(kind+' hidden fallback uses reporting-year control, never body',()=>{const h=harness(kind);h.body.focus();h.open();const fallback=h.node(kind==='objective'?'kpi-x-new-objective':'kpi-x-new-kpi');fallback.hidden=true;h.c.closeKpiModal(h.modal.id);assert.equal(h.active,h.nodes['year-sel']);});
 test(kind+' closing after navigation does not steal external focus',()=>{const h=harness(kind);h.open();const outside=h.node('outside');outside.focus();h.c.closeKpiModal(h.modal.id);assert.equal(h.active,outside);h.open();h.modal.style.display='none';h.c.closeKpiModal(h.modal.id);assert.equal(h.active,h.title);});
 test(kind+' failed permission check does not bind or capture focus',()=>{const h=harness(kind);h.c.allowed=false;assert.equal(h.open(),false);assert.equal(h.active,h.launcher);assert.equal(h.modal._kpiEditorFocusBound,undefined);});
}
for(const [name,change]of [['hidden',n=>n.hidden=true],['disabled',n=>n.disabled=true],['disabled fieldset',n=>n.fieldsetDisabled=true],['negative tabindex',n=>n.tabIndex=-1],['inert or aria-hidden ancestor',n=>n.inert=true],['visibility hidden',n=>n.visibility='hidden'],['visibility collapse',n=>n.visibility='collapse'],['detached',n=>n.isConnected=false]])test('Tab skips '+name+' controls',()=>{const h=harness();h.open();change(h.first);h.key();assert.equal(h.active,h.middle);});
test('positive tabindex order is respected before normal tab order',()=>{const h=harness();h.open();h.last.tabIndex=1;h.middle.tabIndex=2;h.key();assert.equal(h.active,h.last);h.key({shiftKey:true});assert.equal(h.active,h.first);h.key();assert.equal(h.active,h.last);});
test('an inner dialog handles its own keyboard events',()=>{const h=harness();h.open();const inner=h.node('inner');inner.parentModal=h.modal;h.first.innerDialog=inner;h.first.focus();assert.equal(h.key({shiftKey:true}).defaultPrevented,undefined);});
for(const outcome of ['confirm','cancel','failure'])test('archive confirmation guard is temporary: '+outcome,async()=>{
 const h=harness();h.open();const overlay=h.node('app-confirm3modal'),dialog=h.node('confirm-dialog'),title=h.node('app-confirm3title'),cancel=h.node('cancel'),ok=h.node('ok');overlay.querySelector=()=>dialog;dialog.querySelectorAll=()=>[cancel,ok];dialog.contains=n=>[cancel,ok].includes(n);
 let resolve,reject;h.c.appConfirmAction=()=>new Promise((r,j)=>{resolve=r;reject=j;});const work=h.c.kpiEditorConfirmArchive(h.modal,{message:'Synthetic archive'});assert.equal(dialog.listeners.keydown.size,1);
 cancel.focus();h.key({shiftKey:true},dialog);assert.equal(h.active,ok);h.key({},dialog);assert.equal(h.active,cancel);assert.equal(h.modal.style.display,'flex');
 if(outcome==='failure'){reject(new Error('Unavailable'));await assert.rejects(work,/Unavailable/);}else{resolve(outcome==='confirm');assert.equal(await work,outcome==='confirm');}assert.equal(dialog.listeners.keydown.size,0);
});
test('missing custom confirmation retains the existing safe confirmation API',async()=>{const h=harness();let calls=0;h.c.appConfirmAction=async options=>{calls++;assert.equal(options.message,'Archive?');return false;};assert.equal(await h.c.kpiEditorConfirmArchive(h.modal,{message:'Archive?'}),false);assert.equal(calls,1);});
test('no Escape-to-discard or document-wide trap is added to definition editors',()=>{assert.doesNotMatch(editor,/document\.addEventListener\(['"](?:focusin|keydown)/);assert.doesNotMatch(editor,/event\.key===['"]Escape/);assert.match(core,/if\(!accepted\).*cancelled=true[^\n]*\n title\?\.focus\(\)/);});
