const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..');
function harness(){
  const nodes={},listeners={},timers=[];
  const element=()=>({innerHTML:'',value:'all',style:{},querySelector:()=>null,querySelectorAll:()=>[],setAttribute(key,value){this[key]=value;},focus(options){this.focused=options||true;},scrollIntoView(options){this.scrolled=options;}});
  const drawerBody=element();drawerBody.prepend=function(el){this.message=el;};
  const drawer=element();drawer.querySelector=selector=>selector==='.kpi-x-drawer-body'?drawerBody:drawerBody.message||null;drawer.remove=()=>{drawer.removed=true;delete nodes['kpi-x-drawer'];};nodes['kpi-x-drawer']=drawer;
  ['search','status','objective','owner','frequency'].forEach(key=>nodes['kpi-x-'+key]=element());nodes['kpi-x-search'].value='';nodes['year-sel']={value:'2025'};
  const head=element(),body=element();nodes['kpi-monthly-table']={querySelector:()=>head};nodes['kpi-monthly-body']=body;
  const rows={};body.querySelectorAll=()=>Object.values(rows).filter(row=>body.innerHTML.includes('data-kpi-id="'+row.id+'"'));
  const decoy=element(),c={console,Date,document:{readyState:'loading',addEventListener(type,fn){listeners[type]=fn;},getElementById:id=>nodes[id]||null,createElement:element,querySelector:selector=>selector.startsWith('[data-kpi-id=')?decoy:null,querySelectorAll:()=>[]},sessionStorage:{setItem(){}},localStorage:{getItem:()=>null},setTimeout(fn){timers.push(fn);},CSS:{escape:String},kpiCanEdit:()=>false,kpiKPIs:[],kpiObjectives:[{id:'o',name:'Safety'}],kpiIndicators:[],kpiMonthlyData:{},kpiConfigPublished:{targets:{critical_override:true}},toast(message){c.lastToast=message;}};
  c.window=c;vm.createContext(c);const source=fs.readFileSync(path.join(root,'kpi-module-upgrade.js'),'utf8'),marker="if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',kpiXBoot);else kpiXBoot();";assert.ok(source.includes(marker));vm.runInContext(source.replace(marker,'window.qa={state:kpiXState};'),c);vm.runInContext(fs.readFileSync(path.join(root,'auris-module-event-handlers-batch-3.js'),'utf8'),c);
  function add(id='target',extra={}){const k={id,name:'Target KPI',objective_id:'o',frequency:'monthly',...extra};c.kpiKPIs.push(k);c.kpiIndicators.push({id:'i-'+id,kpi_id:id,name:'Reported value',target_value:100,target_operator:'gte'});const row=element();row.id=String(id);row.getAttribute=()=>row.id;rows[id]=row;return row;}
  function click(id='target'){const node={nodeType:1,parentElement:null,getAttribute:key=>key==='data-auris-module-onclick'?'d0024':key==='data-auris-module-args'?encodeURIComponent(JSON.stringify([id])):null};listeners.click({target:node,cancelBubble:false,preventDefault(){}});}
  return {c,nodes,body,head,drawer,drawerBody,rows,decoy,timers,add,click,state:c.qa.state};
}
test('Open Monthly Data clears restrictions that would hide the selected KPI',()=>{const h=harness();h.add();Object.assign(h.state,{status:'on_track',objective:'other',owner:'other',frequency:'annual',search:'absent'});h.click();assert.equal(h.state.tab,'monthly');assert.match(h.body.innerHTML,/data-kpi-id="target"/);for(const key of ['status','objective','owner','frequency']){assert.equal(h.state[key],'all');assert.equal(h.nodes['kpi-x-'+key].value,'all');}assert.equal(h.nodes['kpi-x-search'].value,'');});
test('the real drawer handler focuses and reveals the matching monthly row synchronously',()=>{const h=harness(),row=h.add();h.click();assert.equal(h.drawer.removed,true);assert.equal(row.tabindex,'-1');assert.equal(row.focused.preventScroll,true);assert.equal(row.scrolled.block,'center');assert.equal(row.scrolled.inline,'start');assert.equal(h.timers.length,0);});
test('a matching node outside the monthly table is never targeted',()=>{const h=harness(),row=h.add();h.click();h.timers.forEach(fn=>fn());assert.ok(row.scrolled);assert.equal(h.decoy.scrolled,undefined);});
test('annual and quarterly table views and reporting year survive record navigation',()=>{for(const period of ['annual','quarterly']){const h=harness();h.add('target',{frequency:'annual'});h.state.period=period;h.click();assert.equal(h.state.period,period);assert.equal(h.nodes['year-sel'].value,'2025');assert.match(h.head.innerHTML,period==='annual'?/>Annual</:/>Q1</);}});
test('unknown or obsolete KPI keeps the drawer and current filters intact',()=>{const h=harness();h.add();h.state.status='on_track';h.state.tab='scorecard';h.click('gone');assert.equal(h.drawer.removed,undefined);assert.equal(h.state.tab,'scorecard');assert.equal(h.state.status,'on_track');assert.match(h.drawerBody.message.textContent,/no longer available/i);assert.equal(h.drawerBody.message.role,'alert');});
test('KPI without measurement indicators explains setup instead of silently closing',()=>{const h=harness();h.add();h.c.kpiIndicators=[];h.click();assert.equal(h.drawer.removed,undefined);assert.match(h.drawerBody.message.textContent,/measurement indicator/i);});
test('KPI without a loaded parent objective does not claim to open a missing row',()=>{const h=harness();h.add('target',{objective_id:'gone'});h.click();assert.equal(h.drawer.removed,undefined);assert.match(h.drawerBody.message.textContent,/objective/i);});
test('unavailable monthly table gives visible feedback without navigating away',()=>{const h=harness();h.add();delete h.nodes['kpi-monthly-table'];h.state.tab='scorecard';h.click();assert.equal(h.drawer.removed,undefined);assert.equal(h.state.tab,'scorecard');assert.match(h.drawerBody.message.textContent,/unavailable/i);});
test('repeated errors reuse one alert and place focus on it inside the drawer',()=>{const h=harness();h.click('gone');const message=h.drawerBody.message;h.click('gone');assert.equal(h.drawerBody.message,message);assert.equal(message.tabindex,'-1');assert.ok(message.focused);});
test('non-editable and locked KPIs remain read-only when their monthly rows are opened',()=>{const h=harness();h.add('target',{approval_status:'locked'});h.c.KpiGovernedWorkflow={canEnterMonthly:()=>false};const before=JSON.stringify([h.c.kpiKPIs,h.c.kpiIndicators,h.c.kpiMonthlyData,h.c.kpiConfigPublished]);h.click();assert.doesNotMatch(h.body.innerHTML,/data-kpi-month-entry=/);const afterKpis=h.c.kpiKPIs.map(({_kpiX,_computed_status,...k})=>k);assert.equal(JSON.stringify([afterKpis,h.c.kpiIndicators,h.c.kpiMonthlyData,h.c.kpiConfigPublished]),before);});
test('numeric KPI identifiers resolve through the same drawer event arguments',()=>{const h=harness(),row=h.add(42);h.click('42');assert.equal(h.drawer.removed,true);assert.ok(row.focused);});
test('no delayed callback can scroll a later tab or tenant after navigation',()=>{const h=harness();h.add();h.click();h.c.kpiXSwitchTab('dashboard');h.c.kpiKPIs=[];assert.equal(h.timers.length,0);});
