const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),source=fs.readFileSync(path.join(root,'kpi-module-upgrade.js'),'utf8');
function harness(date='2026-01-15T12:00:00Z',year=2026,excluded=true,frequency='monthly',plannedMonths=[]){
 class Clock extends Date{constructor(...args){super(...(args.length?args:[date]));}static now(){return new Clock().getTime();}}
 const element=()=>({innerHTML:'',querySelector:()=>null,querySelectorAll:()=>[]}),head=element(),nodes={'year-sel':{value:String(year)},'kpi-objectives-container':element(),'kpi-x-dashboard':element(),'kpi-x-reports-view':element(),'kpi-monthly-body':element(),'kpi-monthly-table':{querySelector:()=>head}};
 const c={Date:Clock,console,document:{readyState:'loading',addEventListener(){},getElementById:id=>nodes[id]||null},localStorage:{getItem:()=>null},kpiCanEdit:()=>true,kpiKPIs:[{id:'k',objective_id:'o',name:'Test KPI',frequency,planned_months:plannedMonths}],kpiObjectives:[{id:'o',name:'Test objective'}],kpiIndicators:[{id:'i',kpi_id:'k',name:'Test indicator',target_operator:'gte',target_value:100}],kpiMonthlyData:{i:{1:{month:1,actual:20,ytd:20},8:{month:8,actual:40,ytd:60},12:{month:12,actual:99,ytd:159}}},kpiConfigPublished:{cycles:{current_period_excluded:excluded},targets:{critical_override:true},calculations:{aggregation:'average'}}};c.window=c;vm.createContext(c);
 const boot="if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',kpiXBoot);else kpiXBoot();";assert.ok(source.includes(boot));
 vm.runInContext(source.replace(boot,'window.qa={latest:kpiXLatestRow,previous:kpiXPreviousRow,cutoff:kpiXCompilationMonth,metrics:kpiXMetrics,monthly:kpiXRenderMonthly,scorecard:kpiXRenderScorecard,due:kpiXDueMonth};'),c);
 return {c,nodes,q:c.qa,ytd(){c.qa.monthly();const match=nodes['kpi-monthly-body'].innerHTML.match(/<td><strong>([^<]*)<\/strong><\/td><td>[^<]*<\/td><td>/);assert.ok(match,'monthly summary YTD cell');return match[1];}};
}
for(const method of ['latest','previous'])test(method+' honours explicit zero as no compiled period',()=>{const h=harness();assert.equal(h.q[method]('i',0),null);assert.equal(h.q[method]('i','0'),null);});
for(const cutoff of [undefined,null])test('omitted/null cutoff retains the legacy December default: '+cutoff,()=>{const h=harness();assert.equal(h.q.latest('i',cutoff).month,12);assert.equal(h.q.previous('i',cutoff).month,8);});
test('explicit positive cutoffs retain inclusive latest and exclusive previous lookup',()=>{const h=harness();for(let month=1;month<=12;month++){const expectedLatest=month===12?12:month>=8?8:1,expectedPrevious=month>8?8:month>1?1:null;assert.equal(h.q.latest('i',month)?.month??null,expectedLatest);assert.equal(h.q.previous('i',month)?.month??null,expectedPrevious);}});
test('missing indicator and negative cutoff produce no result',()=>{const h=harness();for(const method of ['latest','previous']){assert.equal(h.q[method]('missing',0),null);assert.equal(h.q[method]('missing',12),null);assert.equal(h.q[method]('i',-1),null);}});
for(const frequency of ['monthly','quarterly','annual'])test('January exclusion does not leak a later YTD into '+frequency+' reporting',()=>{const h=harness(undefined,2026,true,frequency);assert.equal(h.q.cutoff(),0);assert.equal(h.q.metrics().achievement,null);assert.equal(h.ytd(),'—');});
for(const excluded of [true,false])test('future reporting year stays uncompiled with stored rows, exclusion='+excluded,()=>{const h=harness('2026-09-15T12:00:00Z',2027,excluded);assert.equal(h.q.cutoff(),0);assert.equal(h.ytd(),'—');assert.equal(h.q.metrics().achievement,null);});
for(const excluded of [true,false])test('past reporting year still uses December, exclusion='+excluded,()=>{const h=harness('2026-09-15T12:00:00Z',2025,excluded);assert.equal(h.q.cutoff(),12);assert.equal(h.ytd(),'159');assert.equal(h.q.metrics().achievement,99);});
test('January inclusion exposes January only, not a pre-existing later record',()=>{const h=harness(undefined,2026,false);assert.equal(h.q.cutoff(),1);assert.equal(h.ytd(),'20');assert.equal(h.q.metrics().achievement,20);});
test('changing the published exclusion toggle refreshes YTD without changing stored rows',()=>{const h=harness(),before=JSON.stringify(h.c.kpiMonthlyData);assert.equal(h.ytd(),'—');h.c.kpiConfigPublished.cycles.current_period_excluded=false;assert.equal(h.ytd(),'20');h.c.kpiConfigPublished.cycles.current_period_excluded=true;assert.equal(h.ytd(),'—');assert.equal(JSON.stringify(h.c.kpiMonthlyData),before);});
test('a genuine measured zero is preserved when January is included',()=>{const h=harness(undefined,2026,false);h.c.kpiMonthlyData.i[1]={month:1,actual:0,ytd:0};assert.equal(h.ytd(),'0');assert.equal(h.q.metrics().achievement,0);});
test('December exclusion still uses November-or-earlier history, inclusion uses December',()=>{const h=harness('2026-12-15T12:00:00Z');assert.equal(h.q.cutoff(),11);assert.equal(h.ytd(),'60');h.c.kpiConfigPublished.cycles.current_period_excluded=false;assert.equal(h.q.cutoff(),12);assert.equal(h.ytd(),'159');});
test('backdated annual result is compiled only when its recorded month is reached',()=>{const h=harness('2026-09-15T12:00:00Z',2026,true,'annual');h.c.kpiMonthlyData.i={9:{month:9,actual:1,ytd:1}};assert.equal(h.q.due(h.c.kpiKPIs[0],8,'i'),0);assert.equal(h.q.metrics().achievement,null);h.c.kpiMonthlyData.i={8:{month:8,actual:1,ytd:1}};assert.equal(h.q.due(h.c.kpiKPIs[0],8,'i'),8);assert.equal(h.ytd(),'1');});
test('planned months control periodic KPI due dates',()=>{const annual=harness('2026-09-15T12:00:00Z',2026,true,'annual',[5]);annual.c.kpiMonthlyData.i={};assert.equal(annual.q.due(annual.c.kpiKPIs[0],4,'i'),0);assert.equal(annual.q.due(annual.c.kpiKPIs[0],5,'i'),5);assert.equal(annual.q.due(annual.c.kpiKPIs[0],9,'i'),5);const twice=harness('2026-09-15T12:00:00Z',2026,true,'biannual',[4,10]);twice.c.kpiMonthlyData.i={};assert.equal(twice.q.due(twice.c.kpiKPIs[0],3,'i'),0);assert.equal(twice.q.due(twice.c.kpiKPIs[0],8,'i'),4);});
test('January manual-entry availability and raw recorded cells remain unchanged by summary exclusion',()=>{const h=harness();h.q.monthly();const html=h.nodes['kpi-monthly-body'].innerHTML;assert.match(html,/data-month="1"[^>]*>20<\/td>/);assert.doesNotMatch(html,/data-month="12"/);assert.equal(h.c.kpiMonthlyData.i[12].ytd,159);});
