const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),core=fs.readFileSync(path.join(root,'auris-core.js'),'utf8'),html=fs.readFileSync(path.join(root,'index.html'),'utf8'),upgrade=fs.readFileSync(path.join(root,'kpi-module-upgrade.js'),'utf8'),css=fs.readFileSync(path.join(root,'kpi-module-upgrade.css'),'utf8');
function harness(){
 const nodes={},listeners={};let active;
 const node=(id,inside=true)=>nodes[id]={id,inside,value:'',style:{},dataset:{},disabled:false,isConnected:true,hidden:false,focus(){active=this;},getClientRects(){return this.hidden?[]:[{}];},remove(){},setAttribute(k,v){this[k]=v;},addEventListener(k,fn){listeners[k]=fn;}};
 const launcher=node('launcher',false),title=node('entry-modal-title'),first=node('first'),last=node('last');
 for(const id of ['entry-kpi-name','entry-kpi-target','entry-month-label','entry-actual','entry-ytd','entry-comment','kpi-clear-btn','year-sel'])node(id);
 nodes['year-sel'].value='2025';const modal=node('kpi-entry-modal');modal.style.display='none';modal.contains=el=>!!el?.inside;modal.querySelector=()=>null;modal.querySelectorAll=()=>[first,last];active=launcher;
 const c={document:{getElementById:id=>nodes[id],get activeElement(){return active;}},console,Date,kpiCanEdit:()=>true,kpiIndicators:[{id:'i',kpi_id:'k',name:'Count',ytd_method:'sum'}],kpiKPIs:[{id:'k',name:'Talks'}],kpiMonthlyData:{},prof:{id:'u',company_id:'a'},ccid:()=> 'a',KPI_MONTHS:['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],toast(){},kpiFmtTarget:()=>4};vm.createContext(c);
 vm.runInContext(core.slice(core.indexOf('function closeKpiModal(id)'),core.indexOf('async function kpiDeleteObjective')),c);
 vm.runInContext(core.slice(core.indexOf('function kpiCalcYTD(indicatorId'),core.indexOf('async function kpiClearEntry()')),c);
 return {c,nodes,modal,title,first,last,launcher,listeners,focus:el=>{active=el;},get active(){return active;},open:()=>c.kpiOpenEntry('i','k',8),key(shift=false,key='Tab'){const e={key,shiftKey:shift,preventDefault(){this.prevented=true;}};listeners.keydown?.(e);return e;}};
}
test('monthly dialog has a meaningful name and a focusable title',()=>{assert.match(html,/<div id="kpi-entry-modal"[^>]*role="dialog"[^>]*aria-modal="true"[^>]*aria-labelledby="entry-modal-title"/);assert.match(html,/<span id="entry-modal-title"[^>]*tabindex="-1"/);});
test('static monthly fields have explicit associated labels and named close control',()=>{for(const id of ['entry-actual','entry-ytd','entry-comment'])assert.match(html,new RegExp('<label[^>]*for="'+id+'"'));const panel=html.slice(html.indexOf('<div id="kpi-entry-modal"'));assert.match(panel,/aria-label="Close monthly entry"[^>]*data-auris-onclick="h0143"/);});
test('enhanced root-cause and evidence controls also have associated labels',()=>{for(const id of ['entry-root-cause','entry-evidence'])assert.match(upgrade,new RegExp('<label[^>]*for="'+id+'"'));});
test('opening focuses the dialog title and retains its launcher',()=>{const h=harness();h.open();assert.equal(h.active,h.title);assert.equal(h.modal._kpiEntryReturnFocus,h.launcher);});
test('Tab from the title starts at the first enabled visible control',()=>{const h=harness();h.open();const e=h.key();assert.equal(e.prevented,true);assert.equal(h.active,h.first);});
test('Tab from the final control wraps within the form',()=>{const h=harness();h.open();h.focus(h.last);assert.equal(h.key().prevented,true);assert.equal(h.active,h.first);});
test('Shift+Tab from the first control wraps to the final control',()=>{const h=harness();h.open();h.focus(h.first);assert.equal(h.key(true).prevented,true);assert.equal(h.active,h.last);});
test('hidden or disabled controls are not used as focus destinations',()=>{const h=harness();h.open();h.first.hidden=true;h.key();assert.equal(h.active,h.last);h.last.disabled=true;h.focus(h.title);assert.equal(h.key().prevented,true);assert.equal(h.active,h.title);});
test('idle explicit close returns focus to the connected launcher',()=>{const h=harness();h.open();h.c.closeKpiModal('kpi-entry-modal');assert.equal(h.active,h.launcher);assert.equal(h.modal._kpiEntryReturnFocus,null);});
test('closing does not focus a removed launcher or steal focus after navigation',()=>{const h=harness();h.open();h.launcher.isConnected=false;h.c.closeKpiModal('kpi-entry-modal');assert.equal(h.active,h.title);const other=harness();other.open();other.modal.style.display='none';other.focus(other.launcher);other.c.closeKpiModal('kpi-entry-modal');assert.equal(other.active,other.launcher);});
test('changing reporting month inside the same form preserves original return focus',()=>{const h=harness();h.open();h.focus(h.first);h.c.kpiOpenEntry('i','k',7);assert.equal(h.modal._kpiEntryReturnFocus,h.launcher);});
test('unrelated keys do not dismiss the form or discard entries',()=>{const h=harness();h.open();h.nodes['entry-comment'].value='Retain me';assert.equal(h.key(false,'Escape').prevented,undefined);assert.equal(h.modal.style.display,'flex');assert.equal(h.nodes['entry-comment'].value,'Retain me');});
test('touch controls and inherited field typography are scoped to monthly entry',()=>{assert.match(css,/#kpi-entry-modal[^\n]*min-height:44px/);assert.match(css,/#kpi-entry-modal[^\n]*font-family:inherit/);});
