const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..');
function deferred(){let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};}
function harness({realLoader=false}={}){
  const nodes={},calls=[],notices=[],audits=[];
  const field=value=>({value:String(value??''),style:{},dataset:{},disabled:false,children:[],setAttribute(k,v){this[k]=v;},removeAttribute(k){delete this[k];},focus(){document.activeElement=this;},prepend(el){this.children.unshift(el);},remove(){this.removed=true;},addEventListener(){},closest(){return null;}});
  for(const id of ['entry-actual','entry-ytd','entry-comment','entry-root-cause','entry-evidence','entry-modal-title','entry-kpi-name','entry-kpi-target','entry-month-label','entry-kpi-target','kpi-clear-btn'])nodes[id]=field('');
  nodes['year-sel']=field(2025);
  const panel=field(''),modal=field('');modal.style.display='none';modal.querySelector=selector=>selector==='[data-kpi-entry-message]'?panel.children.find(el=>!el.removed):panel;modal.querySelectorAll=()=>controls;modal.contains=el=>controls.includes(el)||panel.children.includes(el);nodes['kpi-entry-modal']=modal;
  const save=field(''),cancel=field('');save.getAttribute=name=>name==='data-auris-onclick'?'h0145':null;cancel.getAttribute=name=>name==='data-auris-onclick'?'h0143':null;
  const controls=[...Object.values(nodes).filter(el=>el!==nodes['year-sel']&&el!==modal),save,cancel];
  controls.forEach(el=>{el.matches=selector=>selector.includes('h0143')&&el===cancel;});
  const document={readyState:'loading',activeElement:null,getElementById:id=>nodes[id]||null,querySelectorAll:()=>[],createElement:()=>field(''),addEventListener(){}};
  const kpi={id:'k',objective_id:'o',company_id:'a',name:'Talks',code:'1.1',frequency:'monthly',status:'not_started'},indicator={id:'i',kpi_id:'k',name:'Count',target_value:100,target_operator:'gte',ytd_method:'sum'};
  const c={console,Date,document,kpiKPIs:[kpi],kpiIndicators:[indicator],kpiObjectives:[{id:'o'}],kpiMonthlyData:{},kpiEntryIndicatorId:null,kpiEntryMonth:0,kpiEntryYear:2025,KPI_MONTHS:['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],kpiConfigPublished:{},prof:{id:'user-a',company_id:'a'},company:'a',ccid:()=>c.company,isSA:()=>false,isMgr:()=>true,kpiCanEdit:()=>c.allowed,allowed:true,kpiFmtTarget:()=>100,kpiGetProgress:(ind,val)=>val,toast:(...args)=>notices.push(args),toastActionError:(...args)=>notices.push(args),auditLogEvent:(...args)=>audits.push(args),setTimeout(){},api:async(url,options)=>{calls.push({url,options});return c.response(url,options);},response:async(url,options)=>{if(url.startsWith('/kpi_monthly_data')&&options){c.stored={id:'m',month:8,company_id:'a',...c.stored,...options.b};}return options?null:(c.stored?[c.stored]:[]);}};
  c.kpiLoadAll=async()=>{if(c.loadError)throw new Error('load failed');c.kpiKPIs=[kpi];c.kpiIndicators=[indicator];c.kpiObjectives=[{id:'o'}];c.kpiMonthlyData={i:{8:c.stored}};};
  c.window=c;vm.createContext(c);
  const core=fs.readFileSync(path.join(root,'auris-core.js'),'utf8');
  vm.runInContext(core.slice(core.indexOf('function closeKpiModal(id)'),core.indexOf('async function kpiDeleteObjective')),c);
  vm.runInContext(core.slice(core.indexOf('function kpiCalcYTD(indicatorId'),core.indexOf('async function kpiClearEntry()')),c);
  if(realLoader){vm.runInContext(core.slice(core.indexOf('async function kpiLoadAll('),core.indexOf('function kpiUpdateMetrics()')),c);c.kpiRenderOverview=()=>{};c.kpiRenderMonthly=()=>{};c.kpiUpdateMetrics=()=>{};}
  const source=fs.readFileSync(path.join(root,'kpi-module-upgrade.js'),'utf8'),boot="if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',kpiXBoot);else kpiXBoot();";
  assert.ok(source.includes(boot));vm.runInContext(source.replace(boot,'kpiXInstallHooks();window.qa={renderCount:0};kpiXRenderAll=function(){window.qa.renderCount++;};'),c);
  if(realLoader){c.kpiRenderOverview=()=>{};c.kpiRenderMonthly=()=>{};c.kpiUpdateMetrics=()=>{};}
  c.kpiOpenEntry('i','k',8);nodes['entry-actual'].value='100';nodes['entry-ytd'].value='';nodes['entry-comment'].value='Explanation';nodes['entry-root-cause'].value='Cause';nodes['entry-evidence'].value='Record A';
  return {c,nodes,modal,panel,calls,notices,audits,kpi,indicator,save,cancel,controls,message:()=>panel.children.find(el=>!el.removed)};
}
test('failed value write retains separated explanation fields and skips status/render follow-ups',async()=>{const h=harness();h.c.response=async()=>{throw new Error('value write failed');};await h.c.kpiSaveEntry();assert.equal(h.calls.length,1);assert.equal(h.nodes['entry-comment'].value,'Explanation');assert.equal(h.nodes['entry-root-cause'].value,'Cause');assert.equal(h.c.qa.renderCount,0);assert.match(h.message().textContent,/could not be confirmed|not saved/i);assert.equal(h.modal.style.display,'flex');});
test('retry after failed save sends each root/evidence section once',async()=>{const h=harness();h.c.response=async()=>{throw new Error('network error');};await h.c.kpiSaveEntry();await h.c.kpiSaveEntry();for(const call of h.calls.filter(x=>x.url==='/kpi_monthly_data')){assert.equal((call.options.b.comment.match(/Root cause:/g)||[]).length,1);assert.equal((call.options.b.comment.match(/Evidence:/g)||[]).length,1);}});
test('validation feedback is focused inside monthly entry without a background toast',async()=>{const h=harness();h.nodes['entry-actual'].value='0';h.nodes['entry-root-cause'].value='';await h.c.kpiSaveEntry();assert.match(h.message().textContent,/root cause/i);assert.equal(h.message().role,'alert');assert.equal(h.c.document.activeElement,h.message());assert.equal(h.calls.length,0);assert.equal(h.notices.length,0);});
test('empty actual cannot perform status updates or report success',async()=>{const h=harness();h.nodes['entry-actual'].value='';await h.c.kpiSaveEntry();assert.equal(h.calls.length,0);assert.match(h.message().textContent,/value/i);assert.equal(h.modal.style.display,'flex');});
test('permission denial cannot perform any follow-up writes',async()=>{const h=harness();h.c.allowed=false;await h.c.kpiSaveEntry();assert.equal(h.calls.length,0);assert.match(h.message().textContent,/manager/i);});
test('saved value followed by summary failure stays saved and blocks another POST',async()=>{const h=harness(),base=h.c.response;h.c.response=async(url,options)=>{if(url.startsWith('/kpis_v2'))throw new Error('summary unavailable');return base(url,options);};await h.c.kpiSaveEntry();await h.c.kpiSaveEntry();assert.equal(h.calls.filter(x=>x.url==='/kpi_monthly_data').length,1);assert.match(h.message().textContent,/value.*saved/i);assert.match(h.message().textContent,/summary|follow-up/i);assert.equal(h.save.disabled,true);assert.equal(h.cancel.disabled,false);assert.equal(h.modal.style.display,'flex');});
test('pending save cannot be submitted twice or have its fields edited',async()=>{const h=harness(),gate=deferred(),entered=deferred(),base=h.c.response;h.c.response=async(url,options)=>{if(url==='/kpi_monthly_data'){entered.resolve();await gate.promise;}return base(url,options);};h.save.focus();const work=h.c.kpiSaveEntry();await entered.promise;assert.equal(h.nodes['entry-actual'].disabled,true);assert.equal(h.cancel.disabled,true);assert.equal(h.c.document.activeElement,h.nodes['entry-modal-title']);await h.c.kpiSaveEntry();gate.resolve();await work;assert.equal(h.calls.filter(x=>x.url==='/kpi_monthly_data').length,1);});
test('company change after opening the entry blocks the value write',async()=>{const h=harness();h.c.company='b';await h.c.kpiSaveEntry();assert.equal(h.calls.length,0);assert.match(h.message().textContent,/company|account/i);});
test('account change after opening the entry blocks the value write',async()=>{const h=harness();h.c.prof={id:'user-b',company_id:'a'};await h.c.kpiSaveEntry();assert.equal(h.calls.length,0);});
test('late value response after company change does not update summaries in the new context',async()=>{const h=harness(),gate=deferred(),entered=deferred(),base=h.c.response;h.c.response=async(url,options)=>{if(url==='/kpi_monthly_data'){entered.resolve();await gate.promise;}return base(url,options);};const work=h.c.kpiSaveEntry();await entered.promise;h.c.company='b';gate.resolve();await work;assert.equal(h.calls.length,1);assert.match(h.message().textContent,/saved/i);assert.equal(h.c.qa.renderCount,0);});
test('zero remains a valid measurement and successful save closes the form',async()=>{const h=harness();h.nodes['entry-actual'].value='0';const result=await h.c.kpiSaveEntry();assert.equal(h.calls[0].options.b.actual,0);assert.equal(h.calls[0].options.b.company_id,'a');assert.equal(result.saved,true);assert.equal(result.complete,true);assert.equal(h.modal.style.display,'none');assert.equal(h.nodes['entry-comment'].value,'Explanation');});
test('editing an existing result retains PATCH semantics',async()=>{const h=harness();h.c.kpiMonthlyData={i:{8:{id:'m',actual:50,month:8}}};await h.c.kpiSaveEntry();assert.equal(h.calls[0].options.m,'PATCH');assert.match(h.calls[0].url,/indicator_id=eq.i.*year=eq.2025.*month=eq.8/);assert.equal(h.calls[0].options.b.actual,100);});
test('load failure after persistence does not claim the value was lost',async()=>{const h=harness();h.c.loadError=true;await h.c.kpiSaveEntry();assert.match(h.message().textContent,/value.*saved/i);assert.equal(h.save.disabled,true);assert.equal(h.modal.style.display,'flex');});
test('unexpected legacy rejection still restores the separated comment',async()=>{const h=harness();h.c.kpiCalcYTD=()=>{throw new Error('calculation unavailable');};await h.c.kpiSaveEntry();assert.equal(h.nodes['entry-comment'].value,'Explanation');assert.equal(h.save.disabled,false);assert.match(h.message().textContent,/calculation unavailable/i);});
test('error text is not inserted as executable HTML',async()=>{const h=harness();h.c.response=async()=>{throw new Error('<img src=x onerror=alert(1)>');};await h.c.kpiSaveEntry();assert.match(h.message().textContent,/<img/);assert.equal(h.message().innerHTML,undefined);});
test('opening another entry resets partial-success lock only after explicit close',async()=>{const h=harness(),base=h.c.response;h.c.response=async(url,options)=>{if(url.startsWith('/kpis_v2'))throw new Error('summary error');return base(url,options);};await h.c.kpiSaveEntry();h.c.closeKpiModal('kpi-entry-modal');h.c.kpiOpenEntry('i','k',8);assert.equal(h.save.disabled,false);assert.equal(h.modal._kpiEntrySaved,false);assert.equal(h.message(),undefined);});
test('existing sum, average, last, minimum and maximum YTD arithmetic is unchanged',()=>{const h=harness();for(const [method,expected] of Object.entries({sum:12,average:6,last:8,min:4,max:8})){h.indicator.ytd_method=method;assert.equal(h.c.kpiCalcYTDFromRows(h.indicator,[{month:1,actual:4},{month:2,actual:8}],2),expected);}});

function realLoaderHarness(){const h=harness({realLoader:true}),base=h.c.response;h.c.response=async(url,options)=>{if(!options&&url.startsWith('/objectives'))return [{id:'o'}];if(!options&&url.startsWith('/kpis_v2'))return [h.kpi];if(!options&&url.startsWith('/kpi_indicators'))return [h.indicator];return base(url,options);};return h;}
test('real guarded reload reports success only after all four datasets are available',async()=>{const h=realLoaderHarness(),result=await h.c.kpiSaveEntry();assert.equal(result.complete,true,h.message()?.textContent);assert.equal(h.modal.style.display,'none');const reads=h.calls.filter(x=>x.url.includes('select=*'));assert.equal(reads.length,4);reads.forEach(x=>assert.match(x.url,/company_id=eq.a/));assert.equal(h.c.kpiMonthlyData.i[8].actual,100);});
test('real guarded reload failure retains saved cache and prevents another value creation',async()=>{const h=realLoaderHarness(),base=h.c.response;h.c.response=async(url,options)=>{if(!options&&url.startsWith('/objectives'))throw new Error('objective read failed');return base(url,options);};const result=await h.c.kpiSaveEntry();assert.equal(result.saved,true);assert.equal(result.complete,false);assert.equal(h.c.kpiMonthlyData.i[8].actual,100);assert.match(h.message().textContent,/objective read failed/);await h.c.kpiSaveEntry();assert.equal(h.calls.filter(x=>x.url==='/kpi_monthly_data').length,1);});
test('saved row missing on real reload is partial success, not a closed successful form',async()=>{const h=realLoaderHarness(),base=h.c.response;h.c.response=async(url,options)=>{if(url.startsWith('/kpi_monthly_data?select'))return [];return base(url,options);};const result=await h.c.kpiSaveEntry();assert.equal(result.saved,true);assert.equal(result.complete,false);assert.equal(h.modal.style.display,'flex');assert.match(h.message().textContent,/not visible/);});
test('real reload does not overwrite new-company caches with a late response',async()=>{const h=realLoaderHarness(),gate=deferred(),entered=deferred(),base=h.c.response;h.c.response=async(url,options)=>{if(url.startsWith('/objectives?select')){entered.resolve();await gate.promise;}return base(url,options);};const work=h.c.kpiSaveEntry();await entered.promise;h.c.company='b';h.c.kpiKPIs=[{id:'new-company-kpi'}];h.c.kpiMonthlyData={newCompany:true};gate.resolve();const result=await work;assert.equal(result.complete,false);assert.equal(h.c.kpiKPIs[0].id,'new-company-kpi');assert.equal(h.c.kpiMonthlyData.newCompany,true);assert.equal(h.c.qa.renderCount,0);});
test('YTD read failure after saving is a visible partial result',async()=>{const h=harness(),base=h.c.response;h.c.response=async(url,options)=>{if(url.includes('order=month'))throw new Error('YTD read failed');return base(url,options);};const result=await h.c.kpiSaveEntry();assert.equal(result.saved,true);assert.equal(result.complete,false);assert.match(h.message().textContent,/YTD read failed/);assert.equal(h.save.disabled,true);});
test('YTD loop stops before another month write after company changes',async()=>{const h=harness(),base=h.c.response;h.c.response=async(url,options)=>{if(!options&&url.includes('order=month'))return [{month:8,actual:100,ytd:0},{month:9,actual:100,ytd:0}];if(options?.m==='PATCH'&&url.startsWith('/kpi_monthly_data')){h.c.company='b';return null;}return base(url,options);};await h.c.kpiSaveEntry();const ytdWrites=h.calls.filter(x=>x.url.startsWith('/kpi_monthly_data')&&x.options?.m==='PATCH');assert.equal(ytdWrites.length,1);assert.match(h.message().textContent,/saved/i);});
test('published status synchronization failure also retains a saved form',async()=>{const h=harness(),base=h.c.response;h.kpi.frequency='annual';let statuses=0;h.c.response=async(url,options)=>{if(url.startsWith('/kpis_v2')&&++statuses===2)throw new Error('published status sync failed');return base(url,options);};const result=await h.c.kpiSaveEntry();assert.equal(statuses,2,JSON.stringify({result,message:h.message()?.textContent,calls:h.calls}));assert.equal(result.saved,true);assert.equal(result.complete,false);assert.match(h.message().textContent,/published status sync failed/);assert.equal(h.modal.style.display,'flex');assert.equal(h.save.disabled,true);});
test('pending save cannot be replaced by a newly opened reporting month',async()=>{const h=harness(),gate=deferred(),entered=deferred(),base=h.c.response;h.c.response=async(url,options)=>{if(url==='/kpi_monthly_data'){entered.resolve();await gate.promise;}return base(url,options);};const work=h.c.kpiSaveEntry();await entered.promise;assert.equal(h.c.kpiOpenEntry('i','k',7),false);assert.equal(h.c.kpiEntryMonth,8);assert.equal(h.nodes['entry-comment'].value,'Explanation');gate.resolve();await work;});
test('company switch while configuration loads cannot run follow-up status writes',async()=>{const h=harness();h.c.kpiConfigLoad=async()=>{h.c.company='b';};await h.c.kpiSaveEntry();assert.equal(h.calls.filter(x=>x.url.startsWith('/kpis_v2')).length,1);assert.equal(h.c.qa.renderCount,0);assert.match(h.message().textContent,/saved/i);});
test('annual late-entry audit is preserved only on successful persistence and refresh',async()=>{const h=harness();h.kpi.frequency='annual';await h.c.kpiSaveEntry();assert.equal(h.audits.length,1);assert.equal(h.audits[0][0],'late_entry');assert.equal(h.audits[0][3].reporting_month,8);const failed=harness();failed.kpi.frequency='annual';failed.c.response=async()=>{throw new Error('write failed');};await failed.c.kpiSaveEntry();assert.equal(failed.audits.length,0);});
test('annual duplicate-month guard remains in force with in-form feedback',async()=>{const h=harness();h.kpi.frequency='annual';h.c.kpiMonthlyData={i:{7:{actual:1}}};await h.c.kpiSaveEntry();assert.equal(h.calls.length,0);assert.match(h.message().textContent,/already has a result in Jul/);});
test('reporting year change prevents the value write',async()=>{const h=harness();h.nodes['year-sel'].value='2026';await h.c.kpiSaveEntry();assert.equal(h.calls.length,0);assert.equal(h.modal.style.display,'flex');});
test('a missing signed-in account cannot save a monthly result',async()=>{const h=harness();h.c.prof={company_id:'a'};h.c.closeKpiModal('kpi-entry-modal');h.c.kpiOpenEntry('i','k',8);await h.c.kpiSaveEntry();assert.equal(h.calls.length,0);});
test('reopening a partial save uses the saved row instead of creating another',async()=>{const h=harness(),base=h.c.response;h.c.response=async(url,options)=>{if(url.startsWith('/kpis_v2'))throw new Error('summary error');return base(url,options);};await h.c.kpiSaveEntry();h.c.closeKpiModal('kpi-entry-modal');h.c.kpiOpenEntry('i','k',8);await h.c.kpiSaveEntry();assert.equal(h.calls.filter(x=>x.url==='/kpi_monthly_data').length,1);assert.equal(h.calls.filter(x=>x.url.startsWith('/kpi_monthly_data?')&&x.options?.m==='PATCH').length,1);});
