const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8'),editor=read('kpi-definition-editor.js');
function harness(){
 const all=[],listeners={},messages=[];let active;
 function node(id=''){
  const n={id,nodeType:1,style:{},dataset:{},attributes:{},children:[],disabled:false,isConnected:true,tabIndex:0,value:'',
   setAttribute(k,v){this.attributes[k]=String(v);},getAttribute(k){return this.attributes[k]??null;},
   appendChild(child){this.children.push(child);child.parentElement=this;return child;},
   insertAdjacentElement(where,child){assert.equal(where,'afterend');const siblings=this.parentElement.children;siblings.splice(siblings.indexOf(this)+1,0,child);child.parentElement=this.parentElement;},
   remove(){this.parentElement.children.splice(this.parentElement.children.indexOf(this),1);this.isConnected=false;if(this.contains(active))active=null;this.parentElement=null;},
   contains(child){return child===this||this.children.some(n=>n.contains(child));},focus(){active=this;},
   getClientRects(){return this.hidden||this.style.display==='none'?[]:[{}];},
   matches(s){return s===':disabled'?this.disabled:false;},
   closest(s){for(let p=this;p;p=p.parentElement){if(s==='[data-ind-row]'&&p.getAttribute('data-ind-row'))return p;}return null;},
   querySelector(s){if(this.fields&&s in this.fields)return this.fields[s];const match=s.match(/^\[([^=\]]+)(?:="([^"]+)")?\]$/);return this.children.find(n=>match&&(match[2]?n.getAttribute(match[1])===match[2]:n.getAttribute(match[1])!==null))||null;},
   get parentNode(){return this.parentElement;},addEventListener(){},set innerHTML(value){this.markup=value;if(value.includes('ind-name-input')){this.fields={};const controls=node();this.appendChild(controls);for(const s of ['.ind-name-input','.ind-target-input','.ind-op-input','.ind-unit-input','.ind-ytd-input','button','[data-indicator-heading]']){const child=node();this.fields[s]=child;(s==='button'?controls:this).appendChild(child);}this.fields.button.setAttribute('data-auris-generated-onclick','g0062');}},get innerHTML(){return this.markup||'';}
  };all.push(n);return n;
 }
 const modal=node('kpi-edit-modal'),list=node('kpi-indicators-list'),add=node('add'),title=node('kpi-modal-title'),launcher=node('launcher');
 modal.style.display='flex';modal._kpiDefinitionContext={valid:true};modal.appendChild(add);modal.appendChild(list);modal.appendChild(title);add.setAttribute('data-auris-onclick','h0140');
 const c={document:{getElementById:id=>all.find(n=>n.id===id&&n.isConnected)||null,createElement:()=>node(),get activeElement(){return active;},addEventListener(type,fn){(listeners[type]??=[]).push(fn);}},messages};c.window=c;vm.createContext(c);vm.runInContext(editor,c);
 c.kpiDefinitionCheckContext=()=>{if(c.contextError)throw new Error(c.contextError);};c.kpiDefinitionFeedback=message=>messages.push(message);c.kpiXCaptureEditorDraft=()=>{c.captures++;};c.captures=0;
 vm.runInContext(read('auris-static-event-handlers.js'),c);vm.runInContext(read('auris-generated-event-handlers.js'),c);launcher.focus();
 const click=n=>{const e={target:n,preventDefault(){this.defaultPrevented=true;}};for(const fn of listeners.click||[])fn(e);return e;};
 return {c,node,modal,list,add,title,launcher,messages,click,get active(){return active;},rows:()=>list.children,status:()=>all.find(n=>n.id==='kpi-indicator-status'),row:(name='Existing',id='i')=>c.kpiAddIndicatorRow(name,4,'gte','','sum',id)};
}
test('row groups and every repeated control are numbered distinctly without changing stored identity',()=>{const h=harness();h.row('First','i');h.row('Second','j');h.rows().forEach((r,i)=>{const number=i+1;assert.equal(r.getAttribute('role'),'group');assert.equal(r.getAttribute('aria-label'),'Measurement indicator '+number);assert.equal(r.querySelector('[data-indicator-heading]').textContent,'Indicator '+number);for(const [selector,label]of [['.ind-name-input','Measurement indicator name'],['.ind-target-input','Indicator target'],['.ind-op-input','Target operator'],['.ind-unit-input','Indicator unit'],['.ind-ytd-input','YTD calculation'],['button','Remove indicator']])assert.equal(r.querySelector(selector).getAttribute('aria-label'),label+' '+number);assert.equal(r.getAttribute('data-indicator-id'),i?'j':'i');});});
test('programmatic rows preserve focus and do not announce or capture partial drafts',()=>{const h=harness();h.row();h.row('Restored','j');assert.equal(h.active,h.launcher);assert.equal(h.status(),undefined);assert.equal(h.c.captures,0);assert.equal(h.rows().length,2);});
test('Add indicator CSP action focuses and announces the new name without persistence',()=>{const h=harness();h.row();h.add.focus();h.click(h.add);assert.equal(h.rows().length,2);assert.equal(h.active,h.rows()[1].querySelector('.ind-name-input'));assert.match(h.status().textContent,/Indicator 2 added/);assert.equal(h.status().getAttribute('role'),'status');assert.equal(h.status().parentElement,h.modal);assert.equal(h.c.captures,1);});
for(const [label,index,next]of [['first',0,0],['middle',1,1],['last',2,1]])test('removing '+label+' row focuses the nearest remaining name and renumbers fields',()=>{const h=harness();['a','b','c'].forEach(id=>h.row(id,id));const removed=h.rows()[index],button=removed.querySelector('button'),retained=h.rows().filter(r=>r!==removed);button.focus();h.click(button);assert.deepEqual(h.rows(),retained);assert.equal(h.active,h.rows()[next].querySelector('.ind-name-input'));assert.equal(h.rows()[1].querySelector('button').getAttribute('aria-label'),'Remove indicator 2');assert.match(h.status().textContent,new RegExp('Indicator '+(index+1)+' removed from this draft'));assert.equal(h.c.captures,1);});
test('removing the only row focuses Add indicator and the announcement is not a saved row',()=>{const h=harness();h.row();h.click(h.rows()[0].querySelector('button'));assert.equal(h.rows().length,0);assert.equal(h.active,h.add);assert.ok(!h.list.children.includes(h.status()));h.click(h.add);assert.equal(h.rows().length,1);assert.equal(h.active,h.rows()[0].querySelector('.ind-name-input'));assert.match(h.status().textContent,/Indicator 1 added/);});
test('add uses the current builder wrapper, not a frozen original',()=>{const h=harness(),original=h.c.kpiAddIndicatorRow;let called=0;h.c.kpiAddIndicatorRow=(...args)=>{called++;return original(...args);};h.click(h.add);assert.equal(called,1);assert.equal(h.active,h.rows()[0].querySelector('.ind-name-input'));});
for(const state of ['_kpiDefinitionBusy','_kpiDefinitionWritten'])for(const action of ['add','remove'])test(state+' blocks '+action+' without changing focus or draft',()=>{const h=harness();h.row();const button=action==='add'?h.add:h.rows()[0].querySelector('button');button.focus();h.modal[state]=true;h.click(button);assert.equal(h.rows().length,1);assert.equal(h.active,button);assert.equal(h.c.captures,0);});
for(const action of ['add','remove'])test('hidden form blocks '+action,()=>{const h=harness();h.row();h.modal.style.display='none';h.click(action==='add'?h.add:h.rows()[0].querySelector('button'));assert.equal(h.rows().length,1);assert.equal(h.c.captures,0);});
for(const action of ['add','remove'])test('disabled controls block '+action,()=>{const h=harness();h.row();const button=action==='add'?h.add:h.rows()[0].querySelector('button');button.disabled=true;h.click(button);assert.equal(h.rows().length,1);assert.equal(h.c.captures,0);});
for(const action of ['add','remove'])test('changed company/account/permission context blocks '+action+' with in-form feedback',()=>{const h=harness();h.row();h.c.contextError='The company, account or permission changed.';h.click(action==='add'?h.add:h.rows()[0].querySelector('button'));assert.equal(h.rows().length,1);assert.match(h.messages[0],/changed/);assert.equal(h.c.captures,0);});
test('detached and foreign remove controls cannot remove any draft row',()=>{const h=harness();h.row();const detached=h.node(),foreignRow=h.node(),foreignButton=h.node();detached.setAttribute('data-auris-generated-onclick','g0062');foreignRow.setAttribute('data-ind-row','1');foreignButton.setAttribute('data-auris-generated-onclick','g0062');foreignRow.appendChild(foreignButton);h.click(detached);h.click(foreignButton);assert.equal(h.rows().length,1);assert.equal(h.c.captures,0);});
test('child icons dispatch to the owning remove button once',()=>{const h=harness();h.row();h.row('Second','j');const button=h.rows()[0].querySelector('button'),icon=h.node();button.appendChild(icon);h.click(icon);assert.equal(h.rows().length,1);assert.equal(h.c.captures,1);assert.equal(h.active,h.rows()[0].querySelector('.ind-name-input'));});
test('repeat removal of a detached row makes no further changes',()=>{const h=harness();h.row();h.row('Second','j');const button=h.rows()[0].querySelector('button');h.click(button);h.click(button);assert.equal(h.rows().length,1);assert.equal(h.c.captures,1);});
test('unavailable neighbouring controls fall back to the editor title',()=>{const h=harness();h.row();h.add.disabled=true;h.click(h.rows()[0].querySelector('button'));assert.equal(h.active,h.title);});
test('row labels and announcements never interpolate a user supplied name as HTML',()=>{const h=harness(),name='<img src=x onerror=alert(1)>';h.row(name);h.row('Second','j');const row=h.rows()[0];assert.equal(row.querySelector('.ind-name-input').value,name);assert.ok(!row.innerHTML.includes(name));h.click(row.querySelector('button'));assert.ok(!h.status().textContent.includes(name));});
test('restoring a row clears a stale removal message without stealing focus or capturing intermediate rows',()=>{const h=harness();h.row();h.click(h.rows()[0].querySelector('button'));assert.match(h.status().textContent,/removed/);h.row('Restored','i');assert.equal(h.status().textContent,'');assert.equal(h.active,h.add);assert.equal(h.c.captures,1);assert.equal(h.rows()[0].getAttribute('data-indicator-id'),'i');});
