const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),core=fs.readFileSync(path.join(root,'auris-core.js'),'utf8'),editor=fs.readFileSync(path.join(root,'kpi-definition-editor.js'),'utf8'),upgrade=fs.readFileSync(path.join(root,'kpi-module-upgrade.js'),'utf8');
function harness(){
 const nodes={},calls=[],notices=[];let active=null;
 function node(id,value=''){return nodes[id]={id,value,style:{},dataset:{},disabled:false,children:[],setAttribute(k,v){this[k]=String(v);},getAttribute(k){return this[k]||null;},removeAttribute(k){delete this[k];},focus(){active=this;},prepend(n){this.children.unshift(n);},appendChild(n){this.children.push(n);},remove(){this.removed=true;},matches(s){return s.includes('h0139')&&id==='close';}};}
 for(const [id,value]of Object.entries({'kpi-name':'Safety','kpi-obj-sel':'o','kpi-code':'1.1','kpi-description':'Purpose','kpi-freq':'monthly','kpi-resp':'Person','kpi-data-provider':'Person','kpi-data-source':'Manual','kpi-reviewer':'Person','kpi-approver':'Person','kpi-status':'not_started','kpi-approval-status':'draft','kpi-modal-title':'','year-sel':'2026','save':'','close':''}))node(id,value);
 const list=node('kpi-indicators-list'),card=node('card'),modal=node('kpi-edit-modal');modal.style.display='flex';modal._kpiDefinitionContext={companyId:'c',actorId:'u',year:2026,kpiId:'k'};
 const controls=Object.values(nodes).filter(n=>!['card','kpi-edit-modal','kpi-indicators-list'].includes(n.id));modal.querySelector=s=>s==='[data-kpi-definition-message]'?card.children.find(n=>!n.removed):card;modal.querySelectorAll=()=>controls;
 const original={id:'i',kpi_id:'k',company_id:'c',name:'Original',target_value:4,target_operator:'gte',unit:null,ytd_method:'sum',sort_order:0};
 function row(id,name){const n=node('row-'+list.children.length);n.setAttribute('data-indicator-id',id||'');const values={'.ind-name-input':name,'.ind-target-input':'4','.ind-op-input':'gte','.ind-unit-input':'','.ind-ytd-input':'sum'};n.querySelector=s=>s in values?{value:values[s]}:null;list.children.push(n);return n;}
 row('i','Renamed');
 const c={console:{error(){}},Date,document:{get activeElement(){return active;},getElementById:id=>nodes[id]||null,createElement:()=>node('message')},prof:{id:'u',company_id:'c'},isSA:()=>false,sephsCompanyContext:null,company:'c',kpiObjectiveCompany:()=>c.company,kpiObjectiveViewYear:()=>Number(nodes['year-sel'].value),isMgr:()=>c.allowed,allowed:true,KpiGovernedWorkflow:{canEdit:()=>c.editable},editable:true,kpiEditKpiId:'k',kpiObjectives:[{id:'o',company_id:'c',year:2026}],kpiKPIs:[{id:'k',company_id:'c',year:2026,status:'not_started',approval_status:'draft'}],kpiIndicators:[{...original}],kpiMonthlyData:{i:{8:{actual:4,ytd:4}}},toast:(...a)=>notices.push(a),toastActionError:(...a)=>notices.push(a),api:async(u,o)=>{calls.push({url:u,options:o});return c.response(u,o);},closeKpiModal:()=>{modal.style.display='none';},kpiLoadAll:async()=>{},kpiRenderOverview(){},kpiRenderMonthly(){},kpiUpdateMetrics(){},kpiRecalcAllYTD:async()=>{},stored:[{...original}],parent:{id:'k',company_id:'c',year:2026,status:'not_started',approval_status:'draft'},response:async(u,o)=>{
  if(u.startsWith('/kpi_monthly_data'))return u.includes('indicator_id=in.')?[{indicator_id:'i',company_id:'c',year:2026,month:8,actual:4,ytd:4}]:[];
  if(u.startsWith('/kpis_v2')){if(o)c.parent={...c.parent,...o.b};return [{...c.parent}];}
  if(u.startsWith('/kpi_indicators')){const id=new URL('http://synthetic.local'+u).searchParams.get('id')?.slice(3);if(o?.m==='PATCH'){const index=c.stored.findIndex(i=>i.id===id);c.stored[index]={...c.stored[index],...o.b};return [{...c.stored[index]}];}if(o?.m==='POST'){const n={id:'new-i',...o.b};c.stored.push(n);return [n];}if(o?.m==='DELETE'){const record=c.stored.find(i=>i.id===id);c.stored=c.stored.filter(i=>i.id!==id);return [record];}return c.stored.map(n=>({...n}));}
  throw new Error('Unexpected '+u);
 }};
 c.window=c;c.ccid=()=>c.company;vm.createContext(c);vm.runInContext(editor,c);
 return {c,nodes,list,modal,controls,calls,notices,original,row,writes:()=>calls.filter(x=>x.options),message:()=>card.children.find(n=>!n.removed)};
}
test('renaming an indicator updates its original ID and leaves its monthly history attached',async()=>{const h=harness();assert.equal((await h.c.kpiSaveKPI()).complete,true);const writes=h.writes().filter(x=>x.url.startsWith('/kpi_indicators'));assert.equal(writes.length,1);assert.equal(writes[0].options.m,'PATCH');assert.match(writes[0].url,/id=eq.i/);assert.equal(writes[0].options.b.name,'Renamed');assert.equal(h.c.kpiMonthlyData.i[8].actual,4);});
test('same-name indicators are distinguished by ID rather than name',async()=>{const h=harness();h.c.stored.push({...h.original,id:'j'});h.c.kpiIndicators.push({...h.original,id:'j'});h.row('j','Original');assert.equal((await h.c.kpiSaveKPI()).complete,true);const writes=h.writes().filter(x=>x.url.startsWith('/kpi_indicators'));assert.equal(writes.length,2);assert.match(writes[0].url,/id=eq.i/);assert.match(writes[1].url,/id=eq.j/);});
test('retained IDs cannot point to another KPI',async()=>{const h=harness();h.list.children[0].setAttribute('data-indicator-id','foreign');await h.c.kpiSaveKPI();assert.equal(h.writes().length,0);assert.match(h.message().textContent,/indicator/i);});
test('duplicate row IDs are rejected before any write',async()=>{const h=harness();h.row('i','Duplicate');await h.c.kpiSaveKPI();assert.equal(h.writes().length,0);assert.match(h.message().textContent,/duplicate/i);});
test('removing an indicator with recorded data fails before the parent write',async()=>{const h=harness(),base=h.c.response;h.list.children=[];h.row('', 'New indicator');h.c.response=async(u,o)=>u.startsWith('/kpi_monthly_data')?[{id:'record'}]:base(u,o);await h.c.kpiSaveKPI();assert.equal(h.writes().length,0);assert.match(h.message().textContent,/monthly.*restore|restore.*monthly/i);assert.equal(h.modal.style.display,'flex');});
test('history lookup failure cannot be treated as no history',async()=>{const h=harness(),base=h.c.response;h.list.children=[];h.row('', 'New');h.c.response=async(u,o)=>u.startsWith('/kpi_monthly_data')?null:base(u,o);await h.c.kpiSaveKPI();assert.equal(h.writes().length,0);assert.ok(h.message());});
test('blank names on retained indicators are validation errors, not silent deletion',async()=>{const h=harness();h.list.children=[];h.row('i','');await h.c.kpiSaveKPI();assert.equal(h.calls.length,0);assert.ok(h.message());});
test('preflight and write endpoints are scoped to company and parent KPI',async()=>{const h=harness();await h.c.kpiSaveKPI();for(const call of h.calls.filter(x=>x.url.startsWith('/kpi_indicators'))){assert.match(call.url,/company_id=eq.c/);assert.match(call.url,/kpi_id=eq.k/);}assert.match(h.writes()[0].url,/company_id=eq.c/);assert.equal('created_by' in h.writes()[0].options.b,false);});
for(const [label,change]of [['company',c=>c.company='other'],['account',c=>c.prof.id='other'],['year',c=>c.document.getElementById('year-sel').value='2027'],['permission',c=>c.allowed=false],['workflow',c=>c.editable=false]])test(label+' change blocks save',async()=>{const h=harness();change(h.c);await h.c.kpiSaveKPI();assert.equal(h.writes().length,0);assert.ok(h.message());});
test('duplicate saves and closing are blocked while history is checked',async()=>{const h=harness(),base=h.c.response;let release;h.c.response=(u,o)=>u.startsWith('/kpi_indicators')&&!o?new Promise(r=>release=()=>r(h.c.stored)):base(u,o);const first=h.c.kpiSaveKPI();await Promise.resolve();await h.c.kpiSaveKPI();assert.equal(h.modal._kpiDefinitionBusy,true);assert.equal(h.controls.every(n=>n.disabled),true);h.c.response=base;release();await first;assert.equal(h.writes().filter(x=>x.url.startsWith('/kpis_v2')).length,1);});
test('partial persistence retains a disabled form and does not repeat creation',async()=>{const h=harness(),base=h.c.response;h.c.response=async(u,o)=>u.startsWith('/kpi_indicators')&&o?Promise.reject(new Error('Indicator save unavailable')):base(u,o);await h.c.kpiSaveKPI();await h.c.kpiSaveKPI();assert.equal(h.writes().filter(x=>x.url.startsWith('/kpis_v2')).length,1);assert.equal(h.nodes.save.disabled,true);assert.equal(h.nodes.close.disabled,false);assert.match(h.message().textContent,/part|some|not.*complete/i);assert.equal(h.notices.length,0);});
test('empty update representation is never treated as success',async()=>{const h=harness(),base=h.c.response;h.c.response=async(u,o)=>o?[]:base(u,o);await h.c.kpiSaveKPI();assert.equal(h.notices.length,0);assert.equal(h.nodes.save.disabled,true);assert.ok(h.message());});
test('changed company after a write stops subsequent indicator requests',async()=>{const h=harness(),base=h.c.response;h.c.response=async(u,o)=>{const response=await base(u,o);if(o&&u.startsWith('/kpis_v2'))h.c.company='other';return response;};await h.c.kpiSaveKPI();assert.equal(h.writes().length,1);assert.equal(h.c.kpiIndicators[0].name,'Original');assert.equal(h.notices.length,0);});
test('row builder stores identity and assigns names as values, not markup',()=>{const created=[],c={document:{getElementById:()=>({children:[],appendChild:n=>created.push(n)}),createElement:()=>({style:{},attributes:{},setAttribute(k,v){this.attributes[k]=v;},querySelector:()=>({})})}};vm.createContext(c);vm.runInContext(editor.slice(editor.indexOf('function kpiAddIndicatorRow('),editor.indexOf('function openKpiAddModal(')),c);c.kpiAddIndicatorRow('A "quoted" <name>',4,'gte','','sum','i');assert.equal(created[0].attributes['data-indicator-id'],'i');assert.ok(!created[0].innerHTML.includes('A "quoted" <name>'));});
test('drafts capture stable indicator IDs',()=>{assert.match(upgrade,/indicatorId:row\.getAttribute\('data-indicator-id'\)/);});
test('historical removal offers restoration without throwing away other draft rows',async()=>{const h=harness(),base=h.c.response;h.list.children=[];h.row('','New draft row');h.c.response=async(u,o)=>u.startsWith('/kpi_monthly_data')?[{id:'history'}]:base(u,o);h.c.kpiAddIndicatorRow=(name,target,op,unit,ytd,id)=>h.row(id,name);await h.c.kpiSaveKPI();const alert=h.message();assert.equal(alert.children[0].textContent,'Restore indicator');alert.children[0].onclick();assert.equal(h.list.children.length,2);assert.equal(h.list.children[0].querySelector('.ind-name-input').value,'New draft row');assert.equal(h.list.children[1].getAttribute('data-indicator-id'),'i');assert.equal(h.writes().length,0);});
test('saving during people refresh leaves the draft editable and makes no request',async()=>{const h=harness();h.nodes['kpi-resp'].setAttribute('aria-busy','true');await h.c.kpiSaveKPI();assert.equal(h.calls.length,0);assert.equal(h.nodes.save.disabled,false);assert.match(h.message().textContent,/people list.*loading/i);});
test('a new indicator is created without changing existing IDs',async()=>{const h=harness();h.row('','New measure');assert.equal((await h.c.kpiSaveKPI()).complete,true);assert.deepEqual(h.c.stored.map(i=>i.id),['i','new-i']);assert.equal(h.c.kpiMonthlyData.i[8].actual,4);});
test('a new KPI captures creator and receives its indicator without an existing ID',async()=>{const h=harness(),base=h.c.response;h.c.kpiEditKpiId=null;h.modal._kpiDefinitionContext.kpiId=null;h.c.stored=[];h.list.children=[];h.row('','New measure');h.c.response=async(u,o)=>u.startsWith('/kpi_monthly_data')?[]:base(u,o);assert.equal((await h.c.kpiSaveKPI()).complete,true);assert.equal(h.writes()[0].options.m,'POST');assert.equal(h.writes()[0].options.b.created_by,'u');assert.equal(h.c.stored[0].kpi_id,'k');});
test('unused removed indicators are deleted only by exact scoped ID',async()=>{const h=harness(),base=h.c.response;h.c.stored.push({...h.original,id:'unused',name:'Unused'});h.c.kpiIndicators.push({...h.original,id:'unused',name:'Unused'});assert.equal((await h.c.kpiSaveKPI()).complete,true);const deletion=h.writes().find(r=>r.options.m==='DELETE');assert.match(deletion.url,/id=eq.unused&kpi_id=eq.k&company_id=eq.c/);assert.equal(h.c.kpiMonthlyData.i[8].actual,4);});
test('a failed final refresh retains saved state and leaves the original caches intact',async()=>{const h=harness(),base=h.c.response;h.c.response=async(u,o)=>!o&&u.startsWith('/kpis_v2')?Promise.reject(new Error('Refresh unavailable')):base(u,o);assert.equal((await h.c.kpiSaveKPI()).complete,false);assert.equal(h.c.kpiIndicators[0].name,'Original');assert.equal(h.nodes.save.disabled,true);assert.equal(h.notices.length,0);});
test('foreign monthly rows cannot be published into the local history cache',async()=>{const h=harness(),base=h.c.response;h.c.response=async(u,o)=>u.includes('indicator_id=in.')?[{indicator_id:'i',company_id:'foreign',year:2026,month:8,actual:99}]:base(u,o);assert.equal((await h.c.kpiSaveKPI()).complete,false);assert.equal(h.c.kpiMonthlyData.i[8].actual,4);});
test('null targets do not validate as numeric zero',()=>{const h=harness();assert.equal(h.c.kpiDefinitionRowsMatch([{id:'i',target_value:null}],{target_value:0}),false);assert.equal(h.c.kpiDefinitionRowsMatch([{id:'i',target_value:0}],{target_value:null}),false);});
test('advanced target operators retain their original selected values when editing',()=>{const source=editor.slice(editor.indexOf('function kpiAddIndicatorRow('),editor.indexOf('function openKpiAddModal('));for(const op of ['zero','trend_up','trend_down'])assert.ok(source.includes('operator==="'+op+'"?"selected"'));});
test('pending editor close uses the core busy guard',()=>{const h=harness();h.modal._kpiDefinitionBusy=true;vm.runInContext(core.slice(core.indexOf('function closeKpiModal('),core.indexOf('function openKpiModal(')),h.c);assert.equal(h.c.closeKpiModal('kpi-edit-modal'),false);assert.equal(h.modal.style.display,'flex');});
test('draft restoration preserves IDs and legacy drafts only recover unambiguous exact names',()=>{const rows=[],storage={savedAt:Date.now(),fields:{},indicators:[{indicatorId:'i',name:'Renamed'},{name:'Existing'},{name:'Ambiguous'}]},nodes={'kpi-indicators-list':{innerHTML:''},'kpi-x-editor-draft-note':{}},c={Date,sessionStorage:{getItem:()=>JSON.stringify(storage)},document:{getElementById:id=>nodes[id]},kpiXEditorDraftKey:()=>'',kpiXClearEditorDraft(){},kpiIndicators:[{id:'i',kpi_id:'k',name:'Old'},{id:'j',kpi_id:'k',name:'Existing'},{id:'a',kpi_id:'k',name:'Ambiguous'},{id:'b',kpi_id:'k',name:'Ambiguous'}],kpiAddIndicatorRow:(...args)=>rows.push(args)};vm.createContext(c);vm.runInContext(upgrade.slice(upgrade.indexOf('function kpiXRestoreEditorDraft('),upgrade.indexOf('function kpiXClearEditorDraft(')),c);c.kpiXRestoreEditorDraft('k');assert.equal(rows[0][5],'i');assert.equal(rows[1][5],'j');assert.ok(!rows[2][5]);});
