const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const read=file=>fs.readFileSync(path.join(__dirname,'..',file),'utf8');
const current={companyId:'co-a',userId:'user-a',name:'Reviewer',role:'manager'};
const requirements=[
  {id:'req-1',company_id:'co-a',req_ref:'OSH-001',legislation:'OSH Act 2005',title:'Provide safe systems of work',section:'12',category:'health_safety',legislation_type:'statutory',jurisdiction:'Mauritius',obligation_type:'mandatory',frequency:'ongoing',applicable:true,status:'non_compliant',compliance_score:20,controls:'',evidence_required:'Inspection record',further_controls:'Complete assessment',gap:true,gap_identified:true,responsibility:'HSE Manager',target_date:'2026-09-10',review_date:'2026-09-01',last_assessed_date:'2026-08-01',updated_at:'2026-09-10T10:00:00Z'},
  {id:'req-2',company_id:'co-a',req_ref:'OSH-002',legislation:'OSH Act 2005',title:'Maintain consultation records',section:'22',category:'consultation',status:'partial',compliance_score:60,controls:'Committee minutes',review_date:'2026-10-01',last_assessed_date:'2026-08-15'},
  {id:'req-3',company_id:'co-a',req_ref:'ISO-001',legislation:'ISO 45001',title:'Management review',section:'9.3',category:'iso',status:'compliant',compliance_score:100,applicable:true,review_date:'2027-01-01',last_assessed_date:'2026-09-01'},
  {id:'archived',company_id:'co-a',req_ref:'OLD-001',legislation:'Old Act',status:'archived',notes:'Archived from register'},
  {id:'foreign',company_id:'co-b',req_ref:'OTHER',legislation:'Other company',status:'non_compliant'}
];
function runtime(){
  const identity={company:{id:'co-a'},profile:{id:'user-a',full_name:'Reviewer'},role:'manager'};let mounted,allowed=true,authenticated=true;
  const window={Date,navigator:{onLine:true},AurisPlatformServices:{ready:()=>true,auth:{isAuthenticated:()=>authenticated,current:()=>identity},rbac:{requireAccess:key=>{assert.equal(key,'legal');if(!allowed)throw Error('Access denied');}}},AurisViewEngine:{mount:(host,data,options)=>{mounted={data,options};return mounted;}}};
  vm.runInNewContext(read('auris-legal-list-workspace.js'),window);
  return {api:window.AurisLegalListWorkspace,identity,mounted:()=>mounted,deny:()=>{allowed=false;},signOut:()=>{authenticated=false;},window};
}
test('projection is tenant scoped and exposes legal status, gaps and deadlines',()=>{const r=runtime(),before=JSON.stringify(requirements),data=r.api.project(requirements,current,{},new Date('2026-09-16T12:00:00Z'));assert.deepEqual(Array.from(data,x=>x.id),['req-1','req-2','req-3']);assert.equal(data[0].reference,'OSH-001');assert.equal(data[0].status,'Non-compliant');assert.equal(data[0].gap,'Open gap');assert.equal(data[0].target,'Overdue');assert.equal(data[0].review,'Overdue');assert.deepEqual(Array.from(data[0].attention_flags),['non_compliant','open_gap','review_overdue','target_overdue']);assert.equal(JSON.stringify(requirements),before);});
test('legal filters combine legislation, category, status and attention',()=>{const r=runtime(),select=filters=>r.api.project(requirements,current,{filters},new Date('2026-09-16T12:00:00Z')).map(x=>x.id);assert.deepEqual(select({legislation:'OSH Act 2005'}),['req-1','req-2']);assert.deepEqual(select({category:'consultation',status:'partial'}),['req-2']);assert.deepEqual(select({attention:'open_gap'}),['req-1']);assert.deepEqual(select({search:'management',status:'compliant'}),['req-3']);assert.deepEqual(select({archived:'true'}),['req-1','req-2','req-3','archived']);});
test('unknown legal values remain visible without unsafe relabelling',()=>{const r=runtime(),data=r.api.project([{id:'x',company_id:'co-a',legislation:'Unknown',status:'awaiting_review',category:'special'}],current,{});assert.equal(data.length,1);assert.equal(data[0].status,'awaiting review');assert.equal(data[0].category,'special');});
test('shared legal register exposes guarded open and manager edit actions',async()=>{const r=runtime(),calls=[];r.api.mount({},requirements,{canEdit:true,openRecord:(id,c)=>calls.push(['open',id,c.companyId]),editRecord:(id,c)=>calls.push(['edit',id,c.companyId])});const m=r.mounted();assert.equal(m.options.moduleKey,'legal-compliance');assert.deepEqual(Array.from(m.options.actions,x=>x.key),['open','edit']);await m.options.onAction('open',m.data[0]);await m.options.onAction('edit',m.data[0]);assert.deepEqual(calls,[['open','req-1','co-a'],['edit','req-1','co-a']]);for(const change of [x=>x.identity.company.id='co-b',x=>x.identity.profile.id='other',x=>x.identity.role='viewer',x=>x.deny(),x=>x.signOut()]){const x=runtime();x.api.mount({},requirements,{canEdit:true,openRecord:()=>assert.fail('stale action')});const view=x.mounted();change(x);await assert.rejects(view.options.onAction('open',view.data[0]),/changed|denied|Sign in/);}});
test('release wiring publishes the Legal Compliance register before the core loader',()=>{const html=read('index.html'),core=read('auris-core.js');assert.ok(html.indexOf('auris-legal-list-workspace.js?')<html.indexOf('auris-core.js?'));assert.match(core,/AurisLegalListWorkspace\.mount\(el,lrAllData/);assert.match(read('sw-assets.js'),/auris-legal-list-workspace\.js/);assert.match(read('scripts/verify-production-smoke.cjs'),/auris-legal-list-workspace\.js/);assert.match(read('scripts/verify-staging-acceptance.cjs'),/auris-legal-list-workspace\.js/);assert.doesNotMatch(read('auris-legal-list-workspace.js'),/\bfetch\(|\bapi\.request\(|\bPOST|\bPATCH|\bDELETE/);});
