const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),read=file=>fs.readFileSync(path.join(root,file),'utf8');
function runtime(){const window={console,Date,URL,Promise,Set};window.globalThis=window;vm.runInNewContext(read('auris-integration-engine.js'),window);vm.runInNewContext(read('auris-master-data-service.js'),window);return window;}
const options={context:()=>({companyId:'co-a',userId:'admin-a',role:'hse_manager'})};
test('shared service validates all governed master-data domains',()=>{const api=runtime().AurisMasterData;assert.equal(Object.keys(api.domains).length,8);const row=api.record({domain:'location',code:'site-01',name:'Main Factory',effectiveFrom:'2026-09-01'},options);assert.equal(row.code,'SITE-01');assert.equal(row.companyId,'co-a');assert.throws(()=>api.record({domain:'unknown',code:'X',name:'Bad'},options),/Unsupported/);assert.throws(()=>api.record({domain:'location',code:'X',name:'Bad',effectiveFrom:'2026-10-01',effectiveTo:'2026-09-01'},options),/precede/);assert.throws(()=>api.record({domain:'location',code:'X',name:'Bad'},{context:()=>({companyId:'co-b',role:'employee'})}),/restricted/);});
test('duplicate detection remains company and domain scoped',()=>{const api=runtime().AurisMasterData,candidate={id:'a',domain:'department',code:'OPS',name:'Operations'},records=[{id:'b',company_id:'co-a',domain:'department',code:'OPS-2',name:'Operations',status:'active',revision:2},{id:'c',company_id:'co-b',domain:'department',code:'OPS',name:'Operations',status:'active'}];const matches=api.duplicateCandidates(candidate,records,options);assert.equal(matches.length,1);assert.equal(matches[0].id,'b');assert.match(api.deepLink({id:'record-1',code:'OPS',companyId:'co-a'}),/^\?goto=master-data&record=record-1/);});
test('mapped CSV reuse accepts reviewed fields and rejects invalid records',()=>{const api=runtime().AurisMasterData,map={Code:'code',Name:'name','Effective From':'effective_from'},plan=api.importPlan('asset','Code,Name,Effective From\r\nEQ-1,Forklift,2026-09-01',map,options);assert.equal(plan.executable,true);assert.equal(plan.accepted[0].domain,'asset');assert.equal(plan.accepted[0].code,'EQ-1');assert.throws(()=>api.importPlan('asset','Code,Name\r\nEQ-1,Forklift',{Code:'code',Name:'unsafe'},options),/not approved/);});
test('database contract preserves tenant isolation revisions dependencies merging and independent import approval',()=>{const sql=read('supabase/migrations/20260902060000_modular_foundation_25_master_data.sql');for(const marker of ['master_data_records','master_data_revisions','master_data_dependencies','master_data_import_batches','master_data_import_rows','capture_master_data_revision','save_master_data_record','set_master_data_record_status','set_master_data_dependency','merge_master_data_records','stage_master_data_import','set_master_data_import_status','requester cannot decide','still referenced by active company records','mapping_fingerprint','master_data.dependency_changed','count(distinct value)','enable row level security','audit_events'])assert.match(sql,new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i'));assert.match(sql,/grant execute on function public\.merge_master_data_records[\s\S]*to authenticated/i);assert.doesNotMatch(sql,/grant\s+(insert|update|delete)\s+on\s+public\.master_data_/i);});
test('administration UI exposes domains evidence governed import and responsive states',()=>{const centre=read('auris-master-data-centre.js'),css=read('auris-master-data-centre.css'),html=read('index.html'),registry=read('auris-module-registry.js'),manifest=read('sw-assets.js');for(const marker of ['Canonical records','Dependency safety','Possible duplicates','Copy exact link','Governed CSV intake','Preview mapped import','Stage for independent review','Approve & apply','merge_master_data_records'])assert.match(centre,new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i'));assert.match(css,/@media\(max-width:420px\)/);assert.match(css,/focus-visible/);assert.match(html,/id="page-master-data"/);assert.match(html,/modular-foundation-25/);assert.match(registry,/{key:'master-data'[\s\S]*loader:'loadMasterDataCentre'/);assert.match(manifest,/auris-master-data-service\.js/);});
