const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const read=file=>fs.readFileSync(path.join(__dirname,'..',file),'utf8');
const current={companyId:'co-a',userId:'user-a',name:'Reviewer',role:'manager'};
const meetings=[
  {id:'mom-1',company_id:'co-a',meeting_ref:'MOM-001',title:'Monthly HSE Committee',meeting_type:'hse_committee',meeting_date:'2026-09-01T09:00:00Z',location:'Boardroom',chaired_by:'Asha',attendees:'Asha, Ben',minutes:'',recommendations:[{desc:'Repair guard',resp:'Facilities',date:'2026-09-10',status:'open'}],next_meeting_date:'2026-09-20',status:'draft',created_at:'2026-09-01'},
  {id:'mom-2',company_id:'co-a',title:'Management review',meeting_type:'management_review',meeting_date:'2026-09-12T09:00:00Z',location:'Online',chaired_by:'Ben',attendees:'Ben',minutes:'Decisions recorded',recommendations:[{desc:'Share minutes',resp:'Asha',date:'2026-10-01',status:'done'}],next_meeting_date:'2026-10-30',status:'completed',created_at:'2026-09-12'},
  {id:'foreign',company_id:'co-b',title:'Other company',meeting_type:'hse_committee'}
];
function runtime(){
  const identity={company:{id:'co-a'},profile:{id:'user-a',full_name:'Reviewer'},role:'manager'};let mounted,allowed=true,authenticated=true;
  const window={Date,navigator:{onLine:true},AurisPlatformServices:{ready:()=>true,auth:{isAuthenticated:()=>authenticated,current:()=>identity},rbac:{requireAccess:key=>{assert.equal(key,'meetings');if(!allowed)throw Error('Access denied');}}},AurisViewEngine:{mount:(host,data,options)=>{mounted={data,options};return mounted;}}};
  vm.runInNewContext(read('auris-meetings-list-workspace.js'),window);
  return {api:window.AurisMeetingsListWorkspace,identity,mounted:()=>mounted,deny:()=>{allowed=false;},signOut:()=>{authenticated=false;},window};
}
test('projection is tenant scoped and preserves minutes, action and next meeting meaning',()=>{const r=runtime(),before=JSON.stringify(meetings),data=r.api.project(meetings,current,{},new Date('2026-09-16T12:00:00Z'));assert.deepEqual(Array.from(data,x=>x.id),['mom-1','mom-2']);assert.equal(data[0].reference,'MOM-001');assert.equal(data[0].open_actions,1);assert.equal(data[0].overdue_actions,1);assert.equal(data[0].next_meeting,'Due soon');assert.deepEqual(Array.from(data[0].attention_flags),['minutes_missing','minutes_overdue','next_meeting_due_soon','action_overdue']);assert.equal(data[1].status,'Completed');assert.equal(JSON.stringify(meetings),before);});
test('meeting filters combine type, status, attention and search',()=>{const r=runtime(),select=filters=>r.api.project(meetings,current,{filters},new Date('2026-09-16T12:00:00Z')).map(x=>x.id);assert.deepEqual(select({type:'management_review'}),['mom-2']);assert.deepEqual(select({status:'draft'}),['mom-1']);assert.deepEqual(select({attention:'action_overdue'}),['mom-1']);assert.deepEqual(select({search:'boardroom'}),['mom-1']);});
test('unknown meeting values remain visible without unsafe relabelling',()=>{const r=runtime(),data=r.api.project([{id:'x',company_id:'co-a',title:'Special forum',meeting_type:'special',status:'in_review',meeting_date:'bad',recommendations:'bad'}],current,{});assert.equal(data.length,1);assert.equal(data[0].type,'special');assert.equal(data[0].status,'in review');assert.equal(data[0].meeting_date,'');});
test('shared HSE meeting register exposes guarded actions and protects sessions',async()=>{const r=runtime(),calls=[];r.api.mount({},meetings,{canEdit:true,openRecord:(id,c)=>calls.push(['open',id,c.companyId]),editRecord:(id,c)=>calls.push(['edit',id,c.companyId])});const m=r.mounted();assert.equal(m.options.moduleKey,'hse-meetings');assert.deepEqual(Array.from(m.options.actions,x=>x.key),['open','edit']);await m.options.onAction('open',m.data[0]);await m.options.onAction('edit',m.data[0]);assert.deepEqual(calls,[['open','mom-1','co-a'],['edit','mom-1','co-a']]);for(const change of [x=>x.identity.company.id='co-b',x=>x.identity.profile.id='other',x=>x.identity.role='viewer',x=>x.deny(),x=>x.signOut()]){const x=runtime();x.api.mount({},meetings,{canEdit:true,openRecord:()=>assert.fail('stale action')});const view=x.mounted();change(x);await assert.rejects(view.options.onAction('open',view.data[0]),/changed|denied|Sign in/);}});
test('release wiring publishes the meetings register before the core loader',()=>{const html=read('index.html'),core=read('auris-core.js');assert.ok(html.indexOf('auris-meetings-list-workspace.js?')<html.indexOf('auris-core.js?'));assert.match(core,/AurisMeetingsListWorkspace\.mount\(el,mtgMinutesData/);assert.match(read('sw-assets.js'),/auris-meetings-list-workspace\.js/);assert.match(read('scripts/verify-production-smoke.cjs'),/auris-meetings-list-workspace\.js/);assert.match(read('scripts/verify-staging-acceptance.cjs'),/auris-meetings-list-workspace\.js/);assert.doesNotMatch(read('auris-meetings-list-workspace.js'),/\bfetch\(|\bapi\.request\(|\bPOST|\bPATCH|\bDELETE/);});
