const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const full=fs.readFileSync(require('node:path').join(__dirname,'../auris-core.js'),'utf8'),source=full.slice(full.indexOf('/* Mobile field interface:'));
function runtime(){const ctx={URL,Date,Promise,console,setTimeout,clearTimeout,prof:{id:'u1',full_name:'Test User'},co:{name:'Test company'},ccid:()=> 'c1',activeRole:()=> 'employee',canAccessPage:p=>['actions','inspection','meetings','events'].includes(p),location:{origin:'https://example.com'},window:{addEventListener:()=>{},matchMedia:()=>({addEventListener:()=>{}})},document:{addEventListener:()=>{}},api:async()=>[]};vm.createContext(ctx);vm.runInContext(source,ctx);ctx.mobileFieldHome=()=>{};return ctx;}
test('mobile summaries filter tenant and assign personal actions at the API boundary',async()=>{const r=runtime(),calls=[];r.api=async path=>{calls.push(path);return [{id:'a',company_id:'c1'},{id:'b',company_id:'c2'}];};await r.mobileFieldRefresh();assert.ok(calls[0].includes('assigned_to_id=eq.u1'));assert.ok(calls.every(p=>p.includes('company_id=eq.c1')));assert.equal(r.mobileFieldState.rows.actions.length,1);});
test('mobile refresh discards late responses after role/company context changes',async()=>{const r=runtime();r.api=async()=>{r.ccid=()=> 'c2';return [{company_id:'c1'}];};await r.mobileFieldRefresh();assert.equal(Object.keys(r.mobileFieldState.rows).length,0);});
test('failed requests show unavailable rather than zero data',async()=>{const r=runtime();r.api=async()=>{throw Error('offline');};await r.mobileFieldRefresh();assert.ok(r.mobileFieldState.errors.includes('actions'));assert.equal(r.mobileFieldState.rows.actions,undefined);});
test('QR links must be same origin, record aware and role allowed',()=>{const r=runtime();assert.equal(r.mobileFieldQrUrl('https://example.com/?goto=events&record=a').searchParams.get('record'),'a');for(const url of ['https://evil.example/?goto=events&record=a','javascript:alert(1)','https://example.com/?goto=admin&record=a','https://example.com/'])assert.throws(()=>r.mobileFieldQrUrl(url));});

function launchRuntime(){const r=runtime();r.mobileFieldClose=()=>{};r.mobileFieldFocusForm=()=>{};r.document.getElementById=()=>({classList:{contains:()=>true}});r.isSA=()=>false;r.canAccessPage=()=>true;return r;}
test('report waits for deferred module loading before opening and selecting its form',async()=>{const r=launchRuntime(),calls=[];let finish;r.mobileNavTo=()=>new Promise(resolve=>{finish=resolve;});r.imsNewIncident=()=>calls.push('new');r.imv2SwitchTab=tab=>calls.push(tab);r.imsSelectType=type=>calls.push(type);const pending=r.mobileFieldAct('report','near_miss');assert.deepEqual(calls,[]);finish({ok:true});await pending;assert.deepEqual(calls,['new','report','near_miss']);});
test('cancelled navigation and changed company cannot initialize a form',async()=>{for(const mode of ['cancel','company']){const r=launchRuntime();let opened=false;r.inspNew=()=>{opened=true;};r.mobileNavTo=async()=>{if(mode==='company')r.ccid=()=> 'c2';return {ok:mode!=='cancel'};};await r.mobileFieldAct('inspection','');assert.equal(opened,false);}});
test('each create shortcut invokes its form after navigation',async()=>{for(const [action,fn] of [['observation','obsNew'],['inspection','inspNew'],['risk','raNew'],['talk','tbtNew']]){const r=launchRuntime(),calls=[];r.mobileNavTo=async()=>{calls.push('ready');return {ok:true};};r[fn]=()=>calls.push(fn);await r.mobileFieldAct(action,'');assert.deepEqual(calls,['ready',fn]);}});
test('software admin must select a company before creating records',async()=>{const r=launchRuntime();r.isSA=()=>true;r.sephsCompanyContext=null;let selected=false;r.mobileFieldCompanies=async()=>{selected=true;};r.toast=()=>{};r.mobileNavTo=()=>{throw Error('must not navigate');};await r.mobileFieldAct('inspection','');assert.equal(selected,true);});
test('company selection rejects ordinary users and unlisted company ids',async()=>{const r=launchRuntime();await assert.rejects(r.mobileFieldPickCompany('c2'));r.isSA=()=>true;await assert.rejects(r.mobileFieldPickCompany('c2'));});

test('header company selection uses shared context without navigating to Home',async()=>{
 const r=launchRuntime();r.isSA=()=>true;r.saCompanyList=[{id:'c2',name:'Company B'}];r.document.querySelector=()=>null;r.document.getElementById=()=>null;r.mobileCompanyHeaderSync=()=>{};
 let selected;r.saCompanyPick=async id=>{selected=id;};r.mobileNavTo=()=>{throw Error('must keep current module');};r.mobileFieldState.site='Old site';r.mobileFieldState.rows={actions:[{}]};
 await r.mobileCompanyHeaderPick('c2');assert.equal(selected,'c2');assert.equal(r.mobileFieldState.site,'');assert.equal(Object.keys(r.mobileFieldState.rows).length,0);
});
test('header company selection rejects unauthorized, unknown and active-form switches',async()=>{
 const r=launchRuntime();r.saCompanyList=[{id:'c2'}];await assert.rejects(r.mobileCompanyHeaderPick('c2'));r.isSA=()=>true;await assert.rejects(r.mobileCompanyHeaderPick('other'));await assert.rejects(r.mobileCompanyHeaderPick(''));r.document.querySelector=()=>({});await assert.rejects(r.mobileCompanyHeaderPick('c2'),/Save or close/);
});
