const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const read=file=>fs.readFileSync(path.join(__dirname,'..',file),'utf8');
const current={companyId:'co-a',userId:'user-a',name:'Reviewer',role:'manager'};
const surveys=[
  {id:'noise-1',company_id:'co-a',survey_ref:'NS-001',survey_type:'occupational',site:'Workshop',survey_date:'2026-08-20',conducted_by:'Asha',instrument_used:'Meter 1',calibration_date:'2025-07-01',measurements:[{loc:'Compressor',source:'Press',leq:90,duration:8}],hpe_assessment:[{result:'inadequate'}],layout_title:'Workshop map',notes:'High exposure'},
  {id:'noise-2',company_id:'co-a',survey_type:'environmental',site:'Boundary',survey_date:'2026-09-10',conducted_by:'Ben',instrument_used:'Meter 2',calibration_date:'2026-08-01',measurements:[{loc:'North gate',leq:72,duration:4}],hpe_assessment:[{result:'adequate'}],notes:''},
  {id:'foreign',company_id:'co-b',site:'Other site',survey_type:'occupational'}
];
function runtime(){
  const identity={company:{id:'co-a'},profile:{id:'user-a',full_name:'Reviewer'},role:'manager'};let mounted,allowed=true,authenticated=true;
  const window={Date,navigator:{onLine:true},AurisPlatformServices:{ready:()=>true,auth:{isAuthenticated:()=>authenticated,current:()=>identity},rbac:{requireAccess:key=>{assert.equal(key,'noise');if(!allowed)throw Error('Access denied');}}},AurisViewEngine:{mount:(host,data,options)=>{mounted={data,options};return mounted;}}};
  vm.runInNewContext(read('auris-noise-list-workspace.js'),window);
  return {api:window.AurisNoiseListWorkspace,identity,mounted:()=>mounted,deny:()=>{allowed=false;},signOut:()=>{authenticated=false;},window};
}
test('projection is tenant scoped and preserves noise exposure, calibration and HPE meaning',()=>{const r=runtime(),before=JSON.stringify(surveys),data=r.api.project(surveys,current,{},new Date('2026-09-16T12:00:00Z'));assert.deepEqual(Array.from(data,x=>x.id),['noise-1','noise-2']);assert.equal(data[0].reference,'NS-001');assert.equal(data[0].max_leq,90);assert.equal(data[0].hpe,'Not adequate');assert.equal(data[0].calibration,'Overdue');assert.deepEqual(Array.from(data[0].attention_flags),['exposure_high','hpe_inadequate','calibration_overdue']);assert.equal(data[1].layout,'No plan');assert.equal(JSON.stringify(surveys),before);});
test('noise filters combine type, HPE, calibration, attention and search',()=>{const r=runtime(),select=filters=>r.api.project(surveys,current,{filters},new Date('2026-09-16T12:00:00Z')).map(x=>x.id);assert.deepEqual(select({type:'environmental'}),['noise-2']);assert.deepEqual(select({hpe:'inadequate'}),['noise-1']);assert.deepEqual(select({calibration:'overdue'}),['noise-1']);assert.deepEqual(select({attention:'exposure_high'}),['noise-1']);assert.deepEqual(select({search:'compressor'}),['noise-1']);});
test('unknown noise values remain visible without unsafe relabelling',()=>{const r=runtime(),data=r.api.project([{id:'x',company_id:'co-a',survey_type:'special',site:'Plant',measurements:'bad',hpe_assessment:'bad',calibration_date:'bad'}],current,{});assert.equal(data.length,1);assert.equal(data[0].type,'special');assert.equal(data[0].hpe,'Missing data');assert.equal(data[0].calibration,'Not recorded');});
test('shared noise register exposes guarded actions and protects sessions',async()=>{const r=runtime(),calls=[];r.api.mount({},surveys,{canEdit:true,openRecord:(id,c)=>calls.push(['open',id,c.companyId]),printRecord:(id,c)=>calls.push(['print',id,c.companyId]),editRecord:(id,c)=>calls.push(['edit',id,c.companyId])});const m=r.mounted();assert.equal(m.options.moduleKey,'noise-surveys');assert.deepEqual(Array.from(m.options.actions,x=>x.key),['open','print','edit']);await m.options.onAction('open',m.data[0]);await m.options.onAction('print',m.data[0]);await m.options.onAction('edit',m.data[0]);assert.deepEqual(calls,[['open','noise-1','co-a'],['print','noise-1','co-a'],['edit','noise-1','co-a']]);for(const change of [x=>x.identity.company.id='co-b',x=>x.identity.profile.id='other',x=>x.identity.role='viewer',x=>x.deny(),x=>x.signOut()]){const x=runtime();x.api.mount({},surveys,{canEdit:true,openRecord:()=>assert.fail('stale action')});const view=x.mounted();change(x);await assert.rejects(view.options.onAction('open',view.data[0]),/changed|denied|Sign in/);}});
test('release wiring publishes the noise register before the core loader',()=>{const html=read('index.html'),core=read('auris-core.js');assert.ok(html.indexOf('auris-noise-list-workspace.js?')<html.indexOf('auris-core.js?'));assert.match(core,/AurisNoiseListWorkspace\.mount\(el,d/);assert.match(read('sw-assets.js'),/auris-noise-list-workspace\.js/);assert.match(read('scripts/verify-production-smoke.cjs'),/auris-noise-list-workspace\.js/);assert.match(read('scripts/verify-staging-acceptance.cjs'),/auris-noise-list-workspace\.js/);assert.doesNotMatch(read('auris-noise-list-workspace.js'),/\bfetch\(|\bapi\.request\(|\bPOST|\bPATCH|\bDELETE/);});
