const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const read=file=>fs.readFileSync(path.join(__dirname,'..',file),'utf8');
const current={companyId:'co-a',userId:'user-a',name:'Reviewer',role:'manager'};
const records=[
  {id:'med-1',company_id:'co-a',exam_ref:'MED-001',employee_name:'Alice Worker',employee_id:'A-1',department:'Production',job_title:'Operator',exam_type:'periodic',exam_date:'2026-01-10',next_exam_date:'2026-09-10',fitness_status:'fit_with_restrictions',follow_up_required:true,report_ref:'REP-1',status:'active',medical_notes:'Sensitive notes',updated_at:'2026-09-01'},
  {id:'med-2',company_id:'co-a',record_ref:'MED-002',employee_name:'Bob Worker',department:'Stores',exam_type:'pre_employment',exam_date:'2026-09-12',next_exam_date:'2026-10-20',fitness_status:'fit',status:'active'},
  {id:'foreign',company_id:'co-b',employee_name:'Foreign worker',status:'active'}
];
function runtime(){
  const identity={company:{id:'co-a'},profile:{id:'user-a',full_name:'Reviewer'},role:'manager'};let mounted,allowed=true,authenticated=true;
  const window={Date,navigator:{onLine:true},AurisPlatformServices:{ready:()=>true,auth:{isAuthenticated:()=>authenticated,current:()=>identity},rbac:{requireAccess:key=>{assert.equal(key,'ohealth');if(!allowed)throw Error('Access denied');}}},AurisViewEngine:{mount:(host,data,options)=>{mounted={data,options};return mounted;}}};
  vm.runInNewContext(read('auris-ohealth-list-workspace.js'),window);
  return {api:window.AurisOhealthListWorkspace,identity,mounted:()=>mounted,deny:()=>{allowed=false;},signOut:()=>{authenticated=false;},window};
}
test('projection is tenant scoped and preserves fitness, due dates and follow-up attention',()=>{const r=runtime(),before=JSON.stringify(records),data=r.api.project(records,current,{},new Date('2026-09-16T12:00:00Z'));assert.deepEqual(Array.from(data,x=>x.id),['med-1','med-2']);assert.equal(data[0].reference,'MED-001');assert.equal(data[0].fitness,'Fit with restrictions');assert.equal(data[0].next_exam,'Overdue');assert.deepEqual(Array.from(data[0].attention_flags),['exam_overdue','restricted','follow_up_required']);assert.equal(data[0].report_reference,'REP-1');assert.equal(JSON.stringify(records),before);});
test('medical surveillance filters combine exam type, due state and search',()=>{const r=runtime(),select=filters=>r.api.project(records,current,{filters},new Date('2026-09-16T12:00:00Z')).map(x=>x.id);assert.deepEqual(select({type:'periodic'}),['med-1']);assert.deepEqual(select({type:'overdue'}),['med-1']);assert.deepEqual(select({type:'due_60'}),['med-1','med-2']);assert.deepEqual(select({search:'stores',fitness:'fit'}),['med-2']);});
test('unknown medical values remain visible without unsafe relabelling',()=>{const r=runtime(),data=r.api.project([{id:'x',company_id:'co-a',employee_name:'Unknown',exam_type:'special_case',fitness_status:'awaiting_review',status:'pending'}],current,{});assert.equal(data.length,1);assert.equal(data[0].exam_type,'special case');assert.equal(data[0].fitness,'awaiting review');});
test('shared medical surveillance register exposes guarded actions and protects sessions',async()=>{const r=runtime(),calls=[];r.api.mount({},records,{canEdit:true,openRecord:(id,c)=>calls.push(['open',id,c.companyId]),editRecord:(id,c)=>calls.push(['edit',id,c.companyId])});const m=r.mounted();assert.equal(m.options.moduleKey,'occupational-health');assert.deepEqual(Array.from(m.options.actions,x=>x.key),['open','edit']);await m.options.onAction('open',m.data[0]);await m.options.onAction('edit',m.data[0]);assert.deepEqual(calls,[['open','med-1','co-a'],['edit','med-1','co-a']]);for(const change of [x=>x.identity.company.id='co-b',x=>x.identity.profile.id='other',x=>x.identity.role='viewer',x=>x.deny(),x=>x.signOut()]){const x=runtime();x.api.mount({},records,{canEdit:true,openRecord:()=>assert.fail('stale action')});const view=x.mounted();change(x);await assert.rejects(view.options.onAction('open',view.data[0]),/changed|denied|Sign in/);}});
test('release wiring publishes the medical surveillance register before the core loader',()=>{const html=read('index.html'),core=read('auris-core.js');assert.ok(html.indexOf('auris-ohealth-list-workspace.js?')<html.indexOf('auris-core.js?'));assert.match(core,/AurisOhealthListWorkspace\.mount\(el,ohMsData/);assert.match(read('sw-assets.js'),/auris-ohealth-list-workspace\.js/);assert.match(read('scripts/verify-production-smoke.cjs'),/auris-ohealth-list-workspace\.js/);assert.match(read('scripts/verify-staging-acceptance.cjs'),/auris-ohealth-list-workspace\.js/);assert.doesNotMatch(read('auris-ohealth-list-workspace.js'),/\bfetch\(|\bapi\.request\(|\bPOST|\bPATCH|\bDELETE/);});
