const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const read=file=>fs.readFileSync(path.join(__dirname,'..',file),'utf8');
const current={companyId:'co-a',userId:'user-a',name:'Reviewer',role:'manager'};
const issuance=[
  {id:'ppe-1',company_id:'co-a',issuance_ref:'ISS-001',ppe_name:'Safety helmet',ppe_category:'head',employee_name:'Alice Worker',employee_id:'A-1',department:'Production',job_title:'Operator',quantity:1,size:'M',serial_number:'H-1',issued_date:'2026-08-01',expiry_date:'2026-09-10',expected_replacement_date:'2026-10-01',condition_on_issue:'new',employee_signature:false,status:'active',updated_at:'2026-09-01'},
  {id:'ppe-2',company_id:'co-a',issuance_ref:'ISS-002',ppe_name:'Safety boots',ppe_category:'feet',employee_name:'Bob Worker',department:'Stores',quantity:2,issued_date:'2026-08-10',expiry_date:'2027-08-10',expected_replacement_date:'2027-08-10',condition_on_issue:'good',employee_signature:true,status:'returned'},
  {id:'foreign',company_id:'co-b',issuance_ref:'ISS-X',ppe_name:'Foreign PPE',status:'active'}
];
function runtime(){
  const identity={company:{id:'co-a'},profile:{id:'user-a',full_name:'Reviewer'},role:'manager'};let mounted,allowed=true,authenticated=true;
  const window={Date,navigator:{onLine:true},AurisPlatformServices:{ready:()=>true,auth:{isAuthenticated:()=>authenticated,current:()=>identity},rbac:{requireAccess:key=>{assert.equal(key,'ppe');if(!allowed)throw Error('Access denied');}}},AurisViewEngine:{mount:(host,data,options)=>{mounted={data,options};return mounted;}}};
  vm.runInNewContext(read('auris-ppe-list-workspace.js'),window);
  return {api:window.AurisPpeListWorkspace,identity,mounted:()=>mounted,deny:()=>{allowed=false;},signOut:()=>{authenticated=false;},window};
}
test('projection is tenant scoped and preserves PPE issuance, expiry and acknowledgement meaning',()=>{const r=runtime(),before=JSON.stringify(issuance),data=r.api.project(issuance,current,{},new Date('2026-09-16T12:00:00Z'));assert.deepEqual(Array.from(data,x=>x.id),['ppe-1','ppe-2']);assert.equal(data[0].reference,'ISS-001');assert.equal(data[0].expiry,'Expired');assert.equal(data[0].replacement,'Due soon');assert.deepEqual(Array.from(data[0].attention_flags),['expiry_overdue','replacement_due_soon','acknowledgement_missing']);assert.equal(data[0].employee,'Alice Worker');assert.equal(data[0].quantity,1);assert.equal(JSON.stringify(issuance),before);});
test('PPE filters combine status, attention and search',()=>{const r=runtime(),select=filters=>r.api.project(issuance,current,{filters},new Date('2026-09-16T12:00:00Z')).map(x=>x.id);assert.deepEqual(select({status:'returned'}),['ppe-2']);assert.deepEqual(select({attention:'acknowledgement_missing'}),['ppe-1']);assert.deepEqual(select({search:'stores',status:'returned'}),['ppe-2']);});
test('unknown PPE values remain visible without unsafe relabelling',()=>{const r=runtime(),data=r.api.project([{id:'x',company_id:'co-a',ppe_name:'Unknown',status:'awaiting_review',condition_on_issue:'mystery'}],current,{});assert.equal(data.length,1);assert.equal(data[0].status,'awaiting review');assert.equal(data[0].condition,'mystery');});
test('shared PPE register exposes guarded open and manager edit actions',async()=>{const r=runtime(),calls=[];r.api.mount({},issuance,{canEdit:true,openRecord:(id,c)=>calls.push(['open',id,c.companyId]),editRecord:(id,c)=>calls.push(['edit',id,c.companyId])});const m=r.mounted();assert.equal(m.options.moduleKey,'ppe-management');assert.deepEqual(Array.from(m.options.actions,x=>x.key),['open','edit']);await m.options.onAction('open',m.data[0]);await m.options.onAction('edit',m.data[0]);assert.deepEqual(calls,[['open','ppe-1','co-a'],['edit','ppe-1','co-a']]);for(const change of [x=>x.identity.company.id='co-b',x=>x.identity.profile.id='other',x=>x.identity.role='viewer',x=>x.deny(),x=>x.signOut()]){const x=runtime();x.api.mount({},issuance,{canEdit:true,openRecord:()=>assert.fail('stale action')});const view=x.mounted();change(x);await assert.rejects(view.options.onAction('open',view.data[0]),/changed|denied|Sign in/);}});
test('release wiring publishes the PPE register before the core loader',()=>{const html=read('index.html'),core=read('auris-core.js');assert.ok(html.indexOf('auris-ppe-list-workspace.js?')<html.indexOf('auris-core.js?'));assert.match(core,/AurisPpeListWorkspace\.mount\(el,ppeIssData/);assert.match(read('sw-assets.js'),/auris-ppe-list-workspace\.js/);assert.match(read('scripts/verify-production-smoke.cjs'),/auris-ppe-list-workspace\.js/);assert.match(read('scripts/verify-staging-acceptance.cjs'),/auris-ppe-list-workspace\.js/);assert.doesNotMatch(read('auris-ppe-list-workspace.js'),/\bfetch\(|\bapi\.request\(|\bPOST|\bPATCH|\bDELETE/);});
