const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');
const root=path.resolve(__dirname,'..'),read=file=>fs.readFileSync(path.join(root,file),'utf8');
function runtime(){const values=new Map(),window={console,Date,Number,localStorage:{getItem:key=>values.get(key)||null,setItem:(key,value)=>values.set(key,value)},document:null};window.globalThis=window;vm.runInNewContext(read('auris-reporting-engine.js'),window);return {window,values};}
const definition={rowKey:'id',modes:['kpi','pivot','chart'],defaultMode:'kpi',defaultDimension:'module',defaultMeasure:'open',dimensions:[{key:'module',label:'Application'},{key:'status',label:'Status'}],measures:[{key:'items',label:'Items',operation:'count'},{key:'open',label:'Open',operation:'sum',field:'open_count'},{key:'average_age',label:'Average age',operation:'average',field:'age'}]};
const rows=[{id:'1',company_id:'co-a',module:'events',status:'open',open_count:1,age:4,secret:'alpha'},{id:'2',company_id:'co-a',module:'events',status:'closed',open_count:0,age:8,secret:'beta'},{id:'3',company_id:'co-a',module:'risk',status:'open',open_count:1,age:3,secret:'gamma'},{id:'x',company_id:'co-b',module:'events',status:'open',open_count:1,age:99,secret:'OTHER COMPANY SECRET'}];
test('report definition validates reviewed dimensions measures and modes',()=>{const api=runtime().window.AurisReportingEngine,def=api.definition(definition);assert.deepEqual(Array.from(def.modes),['kpi','pivot','chart']);assert.throws(()=>api.definition({dimensions:[{key:'../bad'}],measures:[{key:'items'}]}),/Invalid dimension key/);assert.throws(()=>api.definition({dimensions:[{key:'module'}],measures:[{key:'items',operation:'median'}]}),/Unsupported report operation/);});
test('aggregation filters the company before every calculation',()=>{const api=runtime().window.AurisReportingEngine,state={mode:'pivot',dimension:'module',measure:'open',saved:[]},view=api.aggregate(rows,definition,state,{companyId:'co-a'});assert.equal(view.rows.length,3);assert.equal(view.excluded,1);assert.equal(view.totals.items,3);assert.equal(view.totals.open,2);assert.equal(view.totals.average_age,5);assert.deepEqual(Array.from(view.groups,group=>[group.key,group.rows.length,group.values.open]),[['events',2,1],['risk',1,1]]);assert.equal(view.groups.some(group=>group.rows.some(row=>row.company_id==='co-b')),false);});
test('CSV export contains aggregate evidence but never raw records',()=>{const api=runtime().window.AurisReportingEngine,state={mode:'pivot',dimension:'module',measure:'open',saved:[]},view=api.aggregate(rows,definition,state,{companyId:'co-a'}),csv=api.csv(view);assert.match(csv,/"Application","Items","Open","Average age","Record count"/);assert.match(csv,/"events","2","1","6","2"/);for(const forbidden of ['alpha','beta','gamma','OTHER COMPANY SECRET'])assert.equal(csv.includes(forbidden),false);});
test('diagnostics report tenant exclusions without leaking excluded values',()=>{const api=runtime().window.AurisReportingEngine;api.configure({context:()=>({companyId:'co-a',userId:'u1'})});const result=api.diagnostics(rows,definition,{moduleKey:'work'});assert.equal(result.records,3);assert.equal(result.excluded,1);assert.equal(result.groups,2);assert.equal(JSON.stringify(result).includes('OTHER COMPANY SECRET'),false);});
test('My Work adopts reporting with exact grouped drill-down and controlled export',()=>{const html=read('index.html'),work=read('auris-work-centre.js'),engine=read('auris-reporting-engine.js'),css=read('auris-reporting-engine.css'),manifest=read('sw-assets.js');assert.ok(html.indexOf('auris-reporting-engine.js?v=20260901-17')<html.indexOf('auris-work-centre.js?v=20260901-11'));assert.match(html,/auris-reporting-engine\.css\?v=20260901-17/);for(const marker of ["['analysis','Analysis']",'data-work-report-engine','AurisReportingEngine.mount','onExport:downloadReport','onDrillDown:function(rows)','state.reportSelection=rows.map','data-work-clear-report','exact records selected'])assert.match(work,new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.doesNotMatch(engine,/<[^>]+\sstyle=/i);assert.match(css,/are-chart svg/);assert.match(css,/@media\(max-width:700px\)/);assert.match(css,/focus-visible/);assert.match(manifest,/auris-reporting-engine\.js/);assert.match(manifest,/auris-reporting-engine\.css/);});
