const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),read=file=>fs.readFileSync(path.join(root,file),'utf8');
function runtime(){const window={console,Date,URL,Promise,Set};window.globalThis=window;vm.runInNewContext(read('auris-integration-engine.js'),window);return window.AurisIntegrationEngine;}
const context={context:()=>({companyId:'co-a',userId:'scheduler-a',role:'hse_manager'})};
function profile(){return {id:'mapping-24',company_id:'co-a',name:'Contractor actions',operation:'create',field_map:{Reference:'action_ref',Summary:'title',State:'status'},value_map:{status:{Working:'in_progress'}},mapping_fingerprint:'1234567890abcdef1234567890abcdef',status:'active',revision:4};}
function connection(){return {id:'connection-24',companyId:'co-a',endpointUrl:'https://feeds.example.com/actions.csv',approvedHost:'feeds.example.com',credentialRef:'tenant-feed',inboundCsvEnabled:true,events:['action.updated'],status:'active',revision:3};}

test('schedule definitions are bounded, tenant governed and dependency aware',()=>{const api=runtime(),draft=api.exchangeSchedule({name:'Daily contractor actions',mappingProfileId:'mapping-24',connectionId:'connection-24',cadence:'daily',timezone:'Asia/Dubai',localTime:'08:30',weekday:2,retryLimit:3},context);assert.equal(draft.status,'draft');assert.equal(draft.timezone,'Asia/Dubai');assert.equal(draft.retryLimit,3);assert.throws(()=>api.exchangeSchedule({...draft,timezone:'../bad'},context),/IANA timezone/);assert.throws(()=>api.exchangeSchedule({...draft,localTime:'25:70'},context),/HH:MM/);assert.throws(()=>api.exchangeSchedule({...draft,status:'active',mappingProfile:{...profile(),company_id:'co-b'},connection:connection()},context),/active company mapping/);});

test('an exact active schedule prepares mapped rows without approving or applying them',()=>{const api=runtime(),schedule={id:'schedule-24',name:'Daily contractor actions',mappingProfileId:'mapping-24',connectionId:'connection-24',cadence:'daily',timezone:'Asia/Dubai',localTime:'08:30',weekday:2,retryLimit:3,status:'active',revision:5,mappingProfile:profile(),connection:connection()},prepared=api.scheduledMappedImport(schedule,profile(),'Reference,Summary,State\nEXT-24,Guard inspection,Working',context);assert.equal(prepared.scheduleRevision,5);assert.equal(prepared.mappingRevision,4);assert.equal(prepared.rowCount,1);assert.equal(prepared.rows[0].status,'in_progress');assert.equal(prepared.rows[0].company_id,undefined);});

test('database scheduling is tenant isolated, idempotent, timezone aware, revision pinned and independently approved',()=>{const sql=read('supabase/migrations/20260902050000_modular_foundation_24_scheduled_exchange.sql');for(const marker of ['inbound_csv_enabled','set_integration_csv_source','skip_outbound_for_csv_source','data_exchange_schedules','data_exchange_runs','row level security','next_data_exchange_run','at time zone','save_data_exchange_schedule','set_data_exchange_schedule_status','requester cannot decide','queue_data_exchange_run','idempotency_key','claim_due_data_exchange_runs','FOR UPDATE SKIP LOCKED','connection_revision','mapping_revision','mapping_fingerprint','dependency_revision_changed','stage_scheduled_exchange_run','pending_review','fail_scheduled_exchange_run','audit_events'])assert.match(sql,new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i'));assert.match(sql,/create policy data_exchange_schedules_company_admin[\s\S]*actor\.company_id=data_exchange_schedules\.company_id/i);assert.match(sql,/Only a SEPHS platform administrator may approve a scheduled CSV source/i);assert.match(sql,/revoke all on function public\.claim_due_data_exchange_runs[\s\S]*from public,anon,authenticated/i);assert.match(sql,/grant execute on function public\.stage_scheduled_exchange_run[\s\S]*to service_role/i);assert.doesNotMatch(sql,/execute\s+format|\beval\b/i);});

test('worker uses protected streaming bounded HTTPS reads and stages but never approves or applies',()=>{const workerSource=read('api/process-exchange-schedules.js'),worker=require('../api/process-exchange-schedules.js')._test,vercel=JSON.parse(read('vercel.json'));for(const marker of ['AURIS_INTEGRATION_SECRETS_JSON','dns.lookup','privateAddress','redirect:\'manual\'','REQUEST_TIMEOUT_MS','MAX_BODY_BYTES','content-length','getReader','controller.abort','text/csv','scheduledMappedImport','stage_scheduled_exchange_run','fail_scheduled_exchange_run'])assert.match(workerSource,new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.doesNotMatch(workerSource,/set_data_import_status|apply_governed_data_batch/);for(const address of ['127.0.0.1','10.0.0.2','172.20.0.1','192.168.0.4','::1','fd00::1'])assert.equal(worker.privateAddress(address),true);assert.equal(worker.safeError(new Error('fetch https://feeds.example.com/private token abcdefghijklmnop')),'fetch [endpoint] token [redacted]');assert.equal(vercel.crons.find(row=>row.path==='/api/process-exchange-schedules').schedule,'*/5 * * * *');});

test('Integration Centre exposes schedule governance, run history and responsive controls',()=>{const centre=read('auris-integration-centre.js'),css=read('auris-integration-centre.css'),html=read('index.html');for(const marker of ['Approve as CSV source','excluded from outbound webhook delivery','set_integration_csv_source','Governed recurring data intake','Save schedule draft','Preview: the next run','Run history','schedule-review','schedule-active','schedule-rejected','schedule-run','schedule-paused','queue_data_exchange_run','data_exchange_schedules','data_exchange_runs','independent batch approval'])assert.match(centre,new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i'));assert.match(css,/aic-schedule-editor/);assert.match(css,/@media\(max-width:420px\)/);assert.match(html,/modular-foundation-27/);assert.match(html,/auris-integration-centre\.js\?v=20260902-24/);});
