const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const read=file=>fs.readFileSync(path.join(__dirname,'..',file),'utf8');
const current={companyId:'co-a',userId:'user-a',name:'Reviewer',role:'manager'};
const plans=[
  {id:'tp-1',company_id:'co-a',training_ref:'TRN-001',training_topic:'Permit refresher',training_type:'refresher',priority:'high',target_group:'Supervisors',trainer:'Asha',planned_date:'2026-09-01',actual_date:'',status:'confirmed',location:'Training room',objective:'Refresh permit controls',created_at:'2026-08-01'},
  {id:'tp-2',company_id:'co-a',training_ref:'TRN-002',training_topic:'Manual handling',training_type:'internal',priority:'critical',target_group:'All staff',trainer:'Ben',planned_date:'2026-10-10',actual_date:'2026-09-12',status:'completed',location:'Online',created_at:'2026-09-01'},
  {id:'tp-3',company_id:'co-a',training_topic:'First aid',training_type:'external_course',priority:'medium',status:'completed',actual_date:'',created_at:'2026-09-01'},
  {id:'foreign',company_id:'co-b',training_topic:'Other company',status:'planned'}
];
const records=[{id:'rec-2',company_id:'co-a',training_topic:'Manual handling',training_date:'2026-09-12',certificate:'CERT-2'}];
function runtime(){
  const identity={company:{id:'co-a'},profile:{id:'user-a',full_name:'Reviewer'},role:'manager'};let mounted,allowed=true,authenticated=true;
  const window={Date,navigator:{onLine:true},AurisPlatformServices:{ready:()=>true,auth:{isAuthenticated:()=>authenticated,current:()=>identity},rbac:{requireAccess:key=>{assert.equal(key,'training');if(!allowed)throw Error('Access denied');}}},AurisViewEngine:{mount:(host,data,options)=>{mounted={data,options};return mounted;}}};
  vm.runInNewContext(read('auris-training-plan-list-workspace.js'),window);
  return {api:window.AurisTrainingPlanListWorkspace,identity,mounted:()=>mounted,deny:()=>{allowed=false;},signOut:()=>{authenticated=false;},window};
}
test('projection is tenant scoped and preserves plan, evidence and attention meaning',()=>{const r=runtime(),before=JSON.stringify(plans),data=r.api.project(plans,current,{records},new Date('2026-09-16T12:00:00Z'));assert.deepEqual(Array.from(data,x=>x.id),['tp-1','tp-2','tp-3']);assert.equal(data[0].reference,'TRN-001');assert.equal(data[0].attention,'Planned date overdue');assert.ok(data[0].attention_flags.includes('planned_overdue'));assert.equal(data[1].evidence,'1 record');assert.equal(data[1].certificate_evidence,'Certificate evidence');assert.equal(data[2].attention,'Evidence missing');assert.ok(data[2].attention_flags.includes('actual_date_missing'));assert.ok(data[2].attention_flags.includes('evidence_missing'));assert.equal(JSON.stringify(plans),before);});
test('training plan filters combine type, status, priority, attention and search',()=>{const r=runtime(),select=filters=>r.api.project(plans,current,{records,filters},new Date('2026-09-16T12:00:00Z')).map(x=>x.id);assert.deepEqual(select({type:'refresher'}),['tp-1']);assert.deepEqual(select({status:'completed',priority:'critical'}),['tp-2']);assert.deepEqual(select({attention:'planned_overdue'}),['tp-1']);assert.deepEqual(select({search:'training room'}),['tp-1']);});
test('unknown training values remain visible without unsafe relabelling',()=>{const r=runtime(),data=r.api.project([{id:'x',company_id:'co-a',training_topic:'Special briefing',training_type:'special',status:'in_review',priority:'urgent',planned_date:'bad'}],current,{});assert.equal(data.length,1);assert.equal(data[0].training_type,'special');assert.equal(data[0].status,'in review');assert.equal(data[0].priority,'urgent');assert.equal(data[0].planned_date,'');});
test('shared training plan register exposes guarded actions and protects sessions',async()=>{const r=runtime(),calls=[];r.api.mount({},plans,{records,canEdit:true,openRecord:(id,c)=>calls.push(['open',id,c.companyId]),editRecord:(id,c)=>calls.push(['edit',id,c.companyId])});const m=r.mounted();assert.equal(m.options.moduleKey,'training-plan');assert.deepEqual(Array.from(m.options.actions,x=>x.key),['open','edit']);await m.options.onAction('open',m.data[0]);await m.options.onAction('edit',m.data[0]);assert.deepEqual(calls,[['open','tp-1','co-a'],['edit','tp-1','co-a']]);for(const change of [x=>x.identity.company.id='co-b',x=>x.identity.profile.id='other',x=>x.identity.role='viewer',x=>x.deny(),x=>x.signOut()]){const x=runtime();x.api.mount({},plans,{canEdit:true,openRecord:()=>assert.fail('stale action')});const view=x.mounted();change(x);await assert.rejects(view.options.onAction('open',view.data[0]),/changed|denied|Sign in/);}});
test('release wiring publishes the training plan register before the core loader',()=>{const html=read('index.html'),core=read('auris-core.js');assert.ok(html.indexOf('auris-training-plan-list-workspace.js?')<html.indexOf('auris-core.js?'));assert.match(core,/AurisTrainingPlanListWorkspace\.mount\(el,tpAllData/);assert.match(read('sw-assets.js'),/auris-training-plan-list-workspace\.js/);assert.match(read('scripts/verify-production-smoke.cjs'),/auris-training-plan-list-workspace\.js/);assert.match(read('scripts/verify-staging-acceptance.cjs'),/auris-training-plan-list-workspace\.js/);assert.doesNotMatch(read('auris-training-plan-list-workspace.js'),/\bfetch\(|\bapi\.request\(|\bPOST|\bPATCH|\bDELETE/);});
