const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const root=path.resolve(__dirname,'..');
const read=file=>fs.readFileSync(path.join(root,file),'utf8');
function environment(){const values=new Map(),window={console,Date,localStorage:{getItem:key=>values.get(key)||null,setItem:(key,value)=>values.set(key,value)},document:null};window.globalThis=window;vm.runInNewContext(read('auris-view-engine.js'),window);return {window,values};}
const definition={rowKey:'key',views:['list','card','board','calendar','activity'],defaultView:'list',titleField:'title',subtitleField:'ref',groupField:'status',dateField:'due_date',activityField:'updated_at',fields:[{key:'title',label:'Title'},{key:'ref',label:'Reference'},{key:'status',label:'Status'},{key:'due_date',label:'Due',type:'date'},{key:'updated_at',label:'Updated',type:'date'}]};
const rows=[{key:'a',company_id:'co-a',title:'Action A',ref:'A-1',status:'open',due_date:'2026-09-02',updated_at:'2026-09-01'},{key:'b',company_id:'co-b',title:'Action B',ref:'B-1',status:'closed',due_date:'2026-09-03',updated_at:'2026-09-01'}];
test('view definition validates five supported declarative modes',()=>{const {window}=environment(),def=window.AurisViewEngine.definition(definition);assert.deepEqual(Array.from(def.views),['list','card','board','calendar','activity']);assert.throws(()=>window.AurisViewEngine.definition({fields:[{key:'bad key'}]}),/Invalid view field/);});
test('view model excludes other-company records and groups deterministically',()=>{const {window}=environment(),def=window.AurisViewEngine.definition(definition),state={mode:'board',groupBy:'status',sortBy:'title',sortDirection:'asc',saved:[]},model=window.AurisViewEngine.model(rows,def,state,{companyId:'co-a',userId:'u1'});assert.deepEqual(model.rows.map(row=>row.key),['a']);assert.deepEqual(Object.keys(model.groups),['open']);});
test('diagnostics report tenant exclusions without leaking excluded records',()=>{const {window}=environment();window.AurisViewEngine.configure({context:()=>({companyId:'co-a',userId:'u1'})});const result=window.AurisViewEngine.diagnostics(rows,definition,{moduleKey:'work'});assert.equal(result.records,1);assert.equal(result.excluded,1);assert.equal(result.mode,'list');});
test('My Work adopts the engine without losing governed source actions',()=>{const html=read('index.html'),work=read('auris-work-centre.js'),css=read('auris-view-engine.css'),manifest=read('sw-assets.js');assert.ok(html.indexOf('auris-view-engine.js?v=20260901-15')<html.indexOf('auris-work-centre.js?v=20260901-11'));assert.match(html,/auris-view-engine\.css\?v=20260901-15/);for(const marker of ["views:['list','card','board','calendar','activity']",'data-work-view-engine','openSource(row.key)','promptActivity(row.key,action)','onApplyFilters'])assert.match(work,new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.match(css,/@media\(max-width:700px\)/);assert.match(manifest,/auris-view-engine\.js/);assert.match(manifest,/auris-view-engine\.css/);});
