begin;
do $$begin if current_database()<>'auris360_migration_replay' then raise exception 'Disposable replay database required';end if;end;$$;
create or replace function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create function pg_temp.review_audit_failure() returns trigger language plpgsql as $$begin
 if current_setting('test.review_audit_failure',true)='on' then raise exception 'Synthetic review audit failure';end if;return new;end;$$;
create trigger test_review_audit_failure before insert on public.audit_events for each row execute function pg_temp.review_audit_failure();
do $$
declare tenant uuid:=gen_random_uuid(); foreign_tenant uuid:=gen_random_uuid(); owner_id uuid:=gen_random_uuid(); reviewer uuid:=gen_random_uuid(); approver uuid:=gen_random_uuid(); stranger uuid:=gen_random_uuid();
 o uuid; k uuid; i uuid; data_id uuid; config_id uuid; p jsonb; r public.kpi_monthly_reviews; old_revision integer; audit_count integer; before jsonb;
begin
 insert into auth.users(id) values(owner_id),(reviewer),(approver),(stranger);
 insert into public.companies(id,name) values(tenant,'Monthly review replay'),(foreign_tenant,'Foreign review replay');
 insert into public.profiles(id,company_id,full_name,role,status) values(owner_id,tenant,'Report owner','admin','active'),(reviewer,tenant,'Report reviewer','manager','active'),(approver,tenant,'Report approver','admin','active'),(stranger,foreign_tenant,'Foreign admin','admin','active');
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 insert into public.objectives(company_id,name,year) values(tenant,'Review objective',2025) returning id into o;
 insert into public.kpis_v2(company_id,objective_id,name,year,frequency) values(tenant,o,'Review KPI',2025,'monthly') returning id into k;
 insert into public.kpi_indicators(company_id,kpi_id,name,target_value,target_operator) values(tenant,k,'Count',1,'gte') returning id into i;
 insert into public.kpi_config_versions(company_id,version_no,status,configuration) values(tenant,1,'published',jsonb_build_object('workflow',jsonb_build_object('stage1',owner_id,'stage2',reviewer,'stage3',approver,'self_approval',false))) returning id into config_id;
 p:=public.get_kpi_monthly_review(tenant,2025,8);
 if (p->>'missing')::integer<>1 then raise exception 'Missing result not detected';end if;
 begin perform public.transition_kpi_monthly_review(tenant,2025,8,null,null,p->>'fingerprint','submit','');raise exception 'Incomplete submission accepted';exception when sqlstate '22023' then null;end;
 insert into public.kpi_monthly_data(company_id,kpi_id,indicator_id,year,month,actual,ytd) values(tenant,k,i,2025,7,1,1),(tenant,k,i,2025,8,2,3);
 select id into data_id from public.kpi_monthly_data where indicator_id=i and month=8;
 p:=public.get_kpi_monthly_review(tenant,2025,8);
 update public.kpi_monthly_data set actual=3,ytd=4 where id=data_id;
 begin perform public.transition_kpi_monthly_review(tenant,2025,8,null,null,p->>'fingerprint','submit','');raise exception 'Stale preview accepted';exception when sqlstate 'PT409' then null;end;
 p:=public.get_kpi_monthly_review(tenant,2025,8);
 perform set_config('test.review_audit_failure','on',true);
 begin perform public.transition_kpi_monthly_review(tenant,2025,8,null,null,p->>'fingerprint','submit','');raise exception 'Audit failure accepted';exception when raise_exception then if sqlerrm<>'Synthetic review audit failure' then raise;end if;end;
 perform set_config('test.review_audit_failure','off',true);
 if exists(select 1 from public.kpi_monthly_reviews where company_id=tenant) then raise exception 'Submission partly committed';end if;
 r:=public.transition_kpi_monthly_review(tenant,2025,8,null,null,p->>'fingerprint','submit','');
 if r.status<>'submitted' or r.revision<>1 or r.snapshot#>>'{0,result,actual}'<>'3' then raise exception 'Snapshot not saved';end if;
 -- Legacy and source writes cannot bypass review protection with their old capability.
 perform set_config('auris.kpi_result_write','allowed',true);
 begin update public.kpi_monthly_data set actual=99 where id=data_id;raise exception 'Reviewed result changed';exception when sqlstate 'PT409' then if sqlerrm<>'AURIS_MONTH_REVIEW_FROZEN' then raise;end if;end;
 begin delete from public.kpi_monthly_data where indicator_id=i and month=7;raise exception 'Contributing history deleted';exception when sqlstate 'PT409' then null;end;
 begin update public.kpi_indicators set target_value=99 where id=i;raise exception 'Reviewed target changed';exception when sqlstate 'PT409' then null;end;
 begin update public.kpis_v2 set name='Changed' where id=k;raise exception 'Reviewed definition changed';exception when sqlstate 'PT409' then null;end;
 perform set_config('auris.kpi_result_write','',true);
 -- Future reporting remains available; the reviewed snapshot and totals remain intact.
 perform public.mutate_kpi_monthly_result(tenant,k,i,2025,9,(select definition_revision from public.kpis_v2 where id=k),null,null,'save','{"actual":4}');
 if (select snapshot from public.kpi_monthly_reviews where id=r.id)<>r.snapshot then raise exception 'Snapshot changed after later reporting';end if;
 begin perform public.transition_kpi_monthly_review(tenant,2025,8,r.id,r.revision,r.fingerprint,'verify','');raise exception 'Owner self-verified';exception when sqlstate '42501' then null;end;
 perform set_config('request.jwt.claim.sub',stranger::text,true);
 begin perform public.get_kpi_monthly_review(tenant,2025,8);raise exception 'Foreign read accepted';exception when sqlstate '42501' then null;end;
 begin perform public.transition_kpi_monthly_review(tenant,2025,8,r.id,r.revision,r.fingerprint,'verify','');raise exception 'Foreign decision accepted';exception when sqlstate '42501' then null;end;
 perform set_config('request.jwt.claim.sub',reviewer::text,true);
 before:=to_jsonb(r);select count(*) into audit_count from public.audit_events where related_id=r.id;
 perform set_config('test.review_audit_failure','on',true);
 begin perform public.transition_kpi_monthly_review(tenant,2025,8,r.id,r.revision,r.fingerprint,'verify','');raise exception 'Decision audit failure accepted';exception when raise_exception then if sqlerrm<>'Synthetic review audit failure' then raise;end if;end;
 perform set_config('test.review_audit_failure','off',true);
 if before<>(select to_jsonb(t) from public.kpi_monthly_reviews t where id=r.id) or audit_count<>(select count(*) from public.audit_events where related_id=r.id) then raise exception 'Decision partly committed';end if;
 begin perform public.transition_kpi_monthly_review(tenant,2025,8,r.id,r.revision,r.fingerprint,'request_revision','');raise exception 'Missing reason accepted';exception when sqlstate '22023' then null;end;
 r:=public.transition_kpi_monthly_review(tenant,2025,8,r.id,r.revision,r.fingerprint,'request_revision','Correct the source reference');
 update public.kpi_monthly_data set comment='Corrected source' where id=data_id;
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 p:=public.get_kpi_monthly_review(tenant,2025,8);
 r:=public.transition_kpi_monthly_review(tenant,2025,8,r.id,r.revision,p->>'fingerprint','submit','Corrected reference');
 perform set_config('request.jwt.claim.sub',reviewer::text,true);
 old_revision:=r.revision;
 r:=public.transition_kpi_monthly_review(tenant,2025,8,r.id,r.revision,r.fingerprint,'verify','Reviewed');
 begin perform public.transition_kpi_monthly_review(tenant,2025,8,r.id,old_revision,r.fingerprint,'reject','Stale');raise exception 'Stale decision accepted';exception when sqlstate 'PT409' then null;end;
 perform set_config('request.jwt.claim.sub',approver::text,true);
 r:=public.transition_kpi_monthly_review(tenant,2025,8,r.id,r.revision,r.fingerprint,'approve','Approved evidence');
 if r.verified_by<>reviewer or r.approved_by<>approver then raise exception 'Wrong actors recorded';end if;
 begin delete from public.kpi_monthly_data where id=data_id;raise exception 'Approved result cleared';exception when sqlstate 'PT409' then null;end;
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 r:=public.transition_kpi_monthly_review(tenant,2025,8,r.id,r.revision,r.fingerprint,'request_reopen','Correction requested');
 begin update public.kpi_monthly_data set actual=10 where id=data_id;raise exception 'Request alone unlocked result';exception when sqlstate 'PT409' then null;end;
 perform set_config('request.jwt.claim.sub',approver::text,true);
 r:=public.transition_kpi_monthly_review(tenant,2025,8,r.id,r.revision,r.fingerprint,'deny_reopen','Evidence remains correct');
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 r:=public.transition_kpi_monthly_review(tenant,2025,8,r.id,r.revision,r.fingerprint,'request_reopen','New source evidence');
 perform set_config('request.jwt.claim.sub',approver::text,true);
 r:=public.transition_kpi_monthly_review(tenant,2025,8,r.id,r.revision,r.fingerprint,'allow_reopen','Correction authorised');
 update public.kpi_monthly_data set comment='Reopened correction' where id=data_id;
 -- Historical route remains fixed even if company configuration is replaced.
 if r.route->>'reviewer'<>reviewer::text or r.snapshot#>>'{0,result,comment}'<>'Corrected source' then raise exception 'Stored evidence changed';end if;
 if has_table_privilege('authenticated','public.kpi_monthly_reviews','INSERT') or has_table_privilege('authenticated','public.kpi_monthly_reviews','UPDATE') or has_table_privilege('authenticated','public.kpi_monthly_reviews','DELETE') then raise exception 'Direct review mutation granted';end if;
 if has_function_privilege('anon','public.transition_kpi_monthly_review(uuid,integer,integer,uuid,integer,text,text,text)','EXECUTE') then raise exception 'Anonymous transition granted';end if;
 raise notice 'Monthly review: submission, frozen history, future reporting, assignments, stale decisions, audit rollback, revision and controlled reopening passed.';
end;$$;
rollback;
