// AURIS360 governed import executor. Approved batches are applied atomically by service role only.
module.exports=async function handler(req,res){if(!process.env.CRON_SECRET||req.headers.authorization!=='Bearer '+process.env.CRON_SECRET)return res.status(401).json({error:'Unauthorized'});if(!['GET','POST'].includes(String(req.method||'GET').toUpperCase()))return res.status(405).json({error:'GET or POST only'});try{validateEnvironment();return res.status(200).json(await processImports());}catch(error){return res.status(500).json({error:safeError(error)});}};
function validateEnvironment(){var missing=['SUPABASE_URL','SUPABASE_SERVICE_KEY'].filter(function(name){return !process.env[name];});if(missing.length)throw new Error('Import worker configuration is incomplete.');}
function client(){var key=process.env.SUPABASE_SERVICE_KEY;return {base:String(process.env.SUPABASE_URL).replace(/\/$/,''),headers:{apikey:key,Authorization:'Bearer '+key,'Content-Type':'application/json'}};}
async function rpc(name,body){var api=client(),response=await fetch(api.base+'/rest/v1/rpc/'+name,{method:'POST',headers:api.headers,body:JSON.stringify(body||{})}),text=await response.text();if(!response.ok)throw new Error('Import '+name+' failed with upstream status '+response.status);return text?JSON.parse(text):null;}
function errorCode(error){var value=String(error&&error.message||error||'controlled_failure').toLowerCase();if(value.includes('conflict'))return 'reference_conflict';if(value.includes('lease'))return 'lease_invalid';if(value.includes('timeout'))return 'worker_timeout';return 'controlled_failure';}
function safeError(error){return String(error&&error.message||error||'Unknown error').replace(/(Bearer|apikey|token|secret|password)\s+[^\s,;]+/gi,'$1 [redacted]').replace(/https?:\/\/[^\s]+/gi,'[endpoint]').slice(0,300);}
async function processImports(){var claimed=await rpc('claim_data_import_batches',{p_limit:5,p_worker_id:process.env.VERCEL_REGION||'vercel'}),completed=0,failed=0;for(var batch of claimed||[]){try{await rpc('apply_governed_data_batch',{p_batch_id:batch.id,p_lease_token:batch.lease_token});completed++;}catch(error){failed++;try{await rpc('fail_data_import_batch',{p_batch_id:batch.id,p_lease_token:batch.lease_token,p_error_code:errorCode(error)});}catch(_){} }}return {ok:true,claimed:(claimed||[]).length,completed:completed,failed:failed};}
module.exports._test={safeError:safeError,errorCode:errorCode};
